import type { PassivePlanResult } from '../passive-planning/types'
import type { PassiveTargetAnalysis } from '../passive-targeting/types'
import { REAL_PASSIVE_PIPELINE_VERSION } from './config'
import type { PlanningDiagnostics,RequiredTargetDiagnostic,TargetingDiagnostics,RealPassivePipelineInput,PipelineDiagnostics } from './types'
export const emptyTargetingDiagnostics=(input:RealPassivePipelineInput):TargetingDiagnostics=>({evaluatedNodeCount:0,validCandidateCount:0,blockedCandidateCount:0,unresolvedStatLineCount:0,classificationCoveragePercent:0,minimumScoreFilter:input.minimumTargetScore,minimumConfidenceFilter:input.minimumConfidence,forwardedCandidateCount:0})
export const targetingDiagnostics=(input:RealPassivePipelineInput,result:PassiveTargetAnalysis):TargetingDiagnostics=>({evaluatedNodeCount:result.coverage.evaluatedNodeCount,validCandidateCount:result.eligibleCandidates.length,blockedCandidateCount:result.blockedCandidates.length,unresolvedStatLineCount:result.coverage.unresolvedStatLineCount,classificationCoveragePercent:result.coverage.classificationCoveragePercent,minimumScoreFilter:input.minimumTargetScore,minimumConfidenceFilter:input.minimumConfidence,forwardedCandidateCount:result.allCandidates.length})
export const emptyPlanningDiagnostics=():PlanningDiagnostics=>({candidatePoolSize:0,selectedTargetCount:0,pathSearchCount:0,pathCacheHitCount:0,usedPointBudget:0,remainingPointBudget:0,selectionStepCount:0,skippedTargetCount:0,stoppingReason:'not-run'})
export const planningDiagnostics=(result:PassivePlanResult):PlanningDiagnostics=>({candidatePoolSize:result.candidateCount,selectedTargetCount:result.selectedTargetIds.length,pathSearchCount:result.pathSearchCount,pathCacheHitCount:result.pathCacheHitCount,usedPointBudget:result.usedPointBudget,remainingPointBudget:result.remainingPointBudget,selectionStepCount:result.selectionSteps.length,skippedTargetCount:result.skippedTargetIds.length,stoppingReason:result.status})
export function requiredDiagnostics(input:RealPassivePipelineInput,targeting:PassiveTargetAnalysis|null,planning:PassivePlanResult|null):RequiredTargetDiagnostic[]{return[...(input.requiredTargetNodeIds??[])].sort().map(nodeId=>{const tree=input.passiveTree.nodes.find(node=>node.id===nodeId),target=targeting?.allCandidates.find(value=>value.nodeId===nodeId),selected=planning?.selectedTargetIds.includes(nodeId)??false,over=planning?.status==='required-target-over-budget',unreachable=planning?.status==='required-target-unreachable';return{nodeId,treeStatus:tree?'present':'missing',targetingStatus:target?.eligibility??'missing',planningStatus:selected?'selected':planning?(over||unreachable?'failed':'skipped'):'not-run',selected,pathStatus:selected?'connected':over?'over-budget':unreachable?'unreachable':'not-run',violationCodes:[...(!tree?['required-target-not-in-tree']:[]),...(!target?['required-target-not-targeted']:[]),...(target?.eligibility==='blocked'?target.violations.map(value=>value.code):[]),...(over?['required-target-over-budget']:[]),...(unreachable?['required-target-unreachable']:[])],warningCodes:target?.warnings.map(value=>value.code)??[]}})}
function stable(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`}
export function deterministicHash(value:unknown):string{const source=stable(value);let hash=2166136261;for(let i=0;i<source.length;i++){hash^=source.charCodeAt(i);hash=Math.imul(hash,16777619)}return`fnv1a32-${(hash>>>0).toString(16).padStart(8,'0')}`}
export const pipelineDiagnostics=(sourceVersion:string,graphReused:boolean,deterministicResultHash:string,totalDurationMs?:number):PipelineDiagnostics=>({graphReused,totalDurationMs,deterministicResultHash,sourceVersion,pipelineVersion:REAL_PASSIVE_PIPELINE_VERSION})
