import { buildPassiveGraph } from '../passive-pathfinding/graph'
import type { PassiveGraph,PassivePathSource } from '../passive-pathfinding/types'
import { planPassiveTargets } from '../passive-planning/planner'
import { evaluatePassiveTargets } from '../passive-targeting/evaluator'
import { REAL_PASSIVE_PIPELINE_VERSION } from './config'
import { deterministicHash,emptyPlanningDiagnostics,emptyTargetingDiagnostics,pipelineDiagnostics,planningDiagnostics,requiredDiagnostics,targetingDiagnostics } from './diagnostics'
import { validateRealPassivePipelineInput } from './input-validator'
import { resolveRealPassiveStartNode } from './start-node-resolver'
import type { GraphDiagnostics,PipelineIssue,PipelineStage,PipelineStageId,RealPassivePipelineInput,RealPassivePipelineResult,RealPassivePipelineStatus,StartNodeResolution } from './types'

const stageIds:PipelineStageId[]=['validate-input','resolve-start-node','prepare-graph','evaluate-targets','prepare-planning-input','create-passive-plan','validate-output','complete']
const stages=():PipelineStage[]=>stageIds.map(stageId=>({stageId,status:'pending',durationMs:0,warningCodes:[],violationCodes:[],inputSummary:{},outputSummary:{}}))
function finish(values:PipelineStage[],id:PipelineStageId,inputSummary:PipelineStage['inputSummary'],outputSummary:PipelineStage['outputSummary'],violations:string[]=[],durationMs=0){const value=values.find(item=>item.stageId===id)!;value.status=violations.length?'blocked':'complete';value.durationMs=durationMs;value.inputSummary=inputSummary;value.outputSummary=outputSummary;value.violationCodes=[...violations].sort()}
const issue=(code:string,stageId:PipelineStageId,sourceModule:PipelineIssue['sourceModule']='pipeline',nodeId?:string):PipelineIssue=>({code,stageId,sourceModule,...(nodeId?{nodeId}:{})})
const blankStart=(classId:string):StartNodeResolution=>({resolvedStartNodeId:null,resolutionSource:null,classId,warnings:[],violations:[]})
const blankGraph=():GraphDiagnostics=>({graphSource:'none',graphReused:false,graphBuildCount:0,graphNodeCount:0,graphConnectionCount:0})
function failed(input:RealPassivePipelineInput,status:RealPassivePipelineStatus,values:PipelineStage[],violations:PipelineIssue[],start=blankStart(input?.characterClassId??''),graph=blankGraph()):RealPassivePipelineResult{const hash=deterministicHash({requestId:input?.requestId,sourceVersion:input?.sourceVersion,status,start,violations});return{requestId:input?.requestId??'',sourceVersion:input?.sourceVersion??'',characterClassId:input?.characterClassId??'',ascendancyId:input?.ascendancyId,characterLevel:input?.characterLevel??0,pointBudget:input?.pointBudget??0,resolvedStartNodeId:start.resolvedStartNodeId,startNodeResolution:start,targetProfile:input?.targetProfile,planningMode:input?.planningMode,targetingResult:null,planningResult:null,selectedTargetIds:[],allocatedNodeIds:[],allocatedConnectionIds:[],usedPointBudget:0,remainingPointBudget:Math.max(0,input?.pointBudget??0),requiredTargetDiagnostics:input?.passiveTree?requiredDiagnostics(input,null,null):[],pipelineStages:values,graphDiagnostics:graph,targetingDiagnostics:input?emptyTargetingDiagnostics(input):({} as ReturnType<typeof emptyTargetingDiagnostics>),planningDiagnostics:emptyPlanningDiagnostics(),pipelineDiagnostics:pipelineDiagnostics(input?.sourceVersion??'',graph.graphReused,hash),warnings:[],violations,status,optimalityClaim:'unknown',pipelineVersion:REAL_PASSIVE_PIPELINE_VERSION}}

function validateOutput(input:RealPassivePipelineInput,graph:PassiveGraph,result:ReturnType<typeof planPassiveTargets>):string[]{const errors:string[]=[];const nodeIds=result.mergedNodeIds,connectionIds=result.mergedConnectionIds;if(new Set(nodeIds).size!==nodeIds.length)errors.push('duplicate-allocated-node-id');if(new Set(connectionIds).size!==connectionIds.length)errors.push('duplicate-allocated-connection-id');if(nodeIds.some(id=>!graph.nodes.has(id)))errors.push('allocated-node-not-in-graph');if(connectionIds.some(id=>!graph.connections.has(id)))errors.push('allocated-connection-not-in-graph');if(result.selectedTargetIds.some(id=>!graph.nodes.has(id)))errors.push('selected-target-not-in-graph');if(result.usedPointBudget>input.pointBudget)errors.push('pipeline-budget-exceeded');if(nodeIds.some(id=>['ascendancy','ascendancy-start'].includes(graph.nodes.get(id)?.nodeType??'')))errors.push('ascendancy-node-in-normal-plan');if(result.sourceVersion!==input.sourceVersion)errors.push('planning-source-version-mismatch');const allowed=new Set(nodeIds),seen=new Set<string>([result.startNodeId]);let changed=true;while(changed){changed=false;for(const id of connectionIds){const edge=graph.connections.get(id);if(!edge)continue;if(seen.has(edge.fromNodeId)&&allowed.has(edge.toNodeId)&&!seen.has(edge.toNodeId)){seen.add(edge.toNodeId);changed=true}if(seen.has(edge.toNodeId)&&allowed.has(edge.fromNodeId)&&!seen.has(edge.fromNodeId)){seen.add(edge.fromNodeId);changed=true}}}if(nodeIds.some(id=>!seen.has(id)))errors.push('allocated-subtree-disconnected');return[...new Set(errors)].sort()}

export function runRealPassivePipeline(input:RealPassivePipelineInput):RealPassivePipelineResult{
 const pipelineStarted=performance.now(),values=stages(),validationStarted=performance.now(),inputErrors=validateRealPassivePipelineInput(input);finish(values,'validate-input',{pointBudget:input?.pointBudget??-1,characterLevel:input?.characterLevel??-1},{treeNodes:input?.passiveTree?.nodes?.length??0,treeConnections:input?.passiveTree?.connections?.length??0},inputErrors,performance.now()-validationStarted)
 if(inputErrors.length){const status=inputErrors.includes('source-version-mismatch')?'source-version-mismatch':'invalid-input';return failed(input,status,values,inputErrors.map(code=>issue(code,'validate-input')))}
 const startStarted=performance.now(),start=resolveRealPassiveStartNode(input);finish(values,'resolve-start-node',{classId:input.characterClassId,explicit:Boolean(input.startNodeId)},{resolved:start.resolvedStartNodeId??''},start.violations,performance.now()-startStarted)
 if(!start.resolvedStartNodeId)return failed(input,'start-node-unresolved',values,start.violations.map(code=>issue(code,'resolve-start-node')),start)
 let graph:PassiveGraph,graphInfo:GraphDiagnostics;const graphStarted=performance.now()
 try{if(input.passiveGraph){graph=input.passiveGraph;graphInfo={graphSource:'provided',graphReused:true,graphBuildCount:0,graphNodeCount:graph.nodeCount,graphConnectionCount:graph.connectionCount}}else{graph=buildPassiveGraph(input.passiveTree as unknown as PassivePathSource);graphInfo={graphSource:'built',graphReused:false,graphBuildCount:1,graphNodeCount:graph.nodeCount,graphConnectionCount:graph.connectionCount}}}catch{return failed(input,'blocked',values,[issue('graph-preparation-failed','prepare-graph')],start)}
 const graphErrors=[...(graph.nodeCount!==input.passiveTree.nodes.length?['graph-node-count-mismatch']:[]),...(graph.connectionCount!==input.passiveTree.connections.length?['graph-connection-count-mismatch']:[]),...(!graph.nodes.has(start.resolvedStartNodeId)?['start-node-not-in-graph']:[])];finish(values,'prepare-graph',{provided:Boolean(input.passiveGraph)},{nodeCount:graph.nodeCount,connectionCount:graph.connectionCount},graphErrors,performance.now()-graphStarted);if(graphErrors.length)return failed(input,'blocked',values,graphErrors.map(code=>issue(code,'prepare-graph')),start,graphInfo)
 const targetingStarted=performance.now();let targeting;try{targeting=evaluatePassiveTargets({buildProfile:input.buildProfile,characterClassId:input.characterClassId,ascendancyId:input.ascendancyId,characterLevel:input.characterLevel,targetProfile:input.targetProfile,passiveNodes:input.passiveTree.nodes,preparedContext:input.preparedTargetingContext,excludedNodeIds:input.excludedTargetNodeIds,requiredNodeTypes:input.requiredNodeTypes,maximumResults:input.maximumTargetingResults,minimumConfidence:input.minimumConfidence,analyzerContext:input.analyzerContext,sourceVersion:input.sourceVersion})}catch{return failed(input,'targeting-failed',values,[issue('targeting-execution-failed','evaluate-targets','targeting')],start,graphInfo)}
 finish(values,'evaluate-targets',{nodeCount:input.passiveTree.nodes.length},{eligible:targeting.eligibleCandidates.length,blocked:targeting.blockedCandidates.length},[],performance.now()-targetingStarted);finish(values,'prepare-planning-input',{targetCandidates:targeting.allCandidates.length},{candidatePoolLimit:input.candidatePoolLimit,pointBudget:input.pointBudget})
 const planningStarted=performance.now(),planning=planPassiveTargets({requestId:input.requestId,buildProfile:input.buildProfile,characterClassId:input.characterClassId,ascendancyId:input.ascendancyId,startNodeId:start.resolvedStartNodeId,pointBudget:input.pointBudget,targetProfile:input.targetProfile,targetingResult:targeting,passiveGraph:graph,alreadyAllocatedNodeIds:input.alreadyAllocatedNodeIds,blockedNodeIds:input.blockedNodeIds,requiredTargetNodeIds:input.requiredTargetNodeIds,excludedTargetNodeIds:input.excludedTargetNodeIds,maximumSelectedTargets:input.maximumSelectedTargets,candidatePoolLimit:input.candidatePoolLimit,minimumTargetScore:input.minimumTargetScore,minimumConfidence:input.minimumConfidence,planningMode:input.planningMode,analyzerContext:input.analyzerContext,sourceVersion:input.sourceVersion,allowReoptimizationTargets:input.allowKeystoneReoptimization});finish(values,'create-passive-plan',{candidatePoolLimit:input.candidatePoolLimit},{selected:planning.selectedTargetIds.length,status:planning.status},planning.violations,performance.now()-planningStarted)
 const outputValidationStarted=performance.now(),outputErrors=validateOutput(input,graph,planning);finish(values,'validate-output',{selected:planning.selectedTargetIds.length},{valid:outputErrors.length===0},outputErrors,performance.now()-outputValidationStarted)
 const required=requiredDiagnostics(input,targeting,planning),requiredFailed=required.some(value=>!value.selected),allErrors=[...outputErrors.map(code=>issue(code,'validate-output')),...planning.violations.map(code=>issue(code,'create-passive-plan','planning'))]
 const status:RealPassivePipelineStatus=outputErrors.length?'planning-failed':requiredFailed?'required-target-failed':planning.status==='no-eligible-targets'?'no-eligible-targets':planning.status==='budget-exhausted'?'budget-exhausted':planning.status==='complete'?'complete':planning.status==='partial'?'partial':planning.status==='invalid-input'?'planning-failed':'planning-failed'
 finish(values,'complete',{validated:outputErrors.length===0},{status},[],performance.now()-pipelineStarted);const warnings:PipelineIssue[]=[...planning.warnings.map(code=>issue(code,'create-passive-plan','planning')),...targeting.allCandidates.flatMap(target=>target.warnings.map(value=>issue(value.code,'evaluate-targets','targeting',target.nodeId)))]
 const core={requestId:input.requestId,sourceVersion:input.sourceVersion,start,selectedTargetIds:planning.selectedTargetIds,allocatedNodeIds:planning.mergedNodeIds,allocatedConnectionIds:planning.mergedConnectionIds,targeting:targeting.allCandidates.map(value=>({nodeId:value.nodeId,totalScore:value.totalScore,eligibility:value.eligibility,confidence:value.confidence,reasons:value.reasons.map(reason=>reason.code),violations:value.violations.map(item=>item.code)})),planning,required,status,warnings,violations:allErrors};const hash=deterministicHash(core)
 return{requestId:input.requestId,sourceVersion:input.sourceVersion,characterClassId:input.characterClassId,ascendancyId:input.ascendancyId,characterLevel:input.characterLevel,pointBudget:input.pointBudget,resolvedStartNodeId:start.resolvedStartNodeId,startNodeResolution:start,targetProfile:input.targetProfile,planningMode:input.planningMode,targetingResult:targeting,planningResult:planning,selectedTargetIds:[...planning.selectedTargetIds],allocatedNodeIds:[...planning.mergedNodeIds],allocatedConnectionIds:[...planning.mergedConnectionIds],usedPointBudget:planning.usedPointBudget,remainingPointBudget:planning.remainingPointBudget,requiredTargetDiagnostics:required,pipelineStages:values,graphDiagnostics:graphInfo,targetingDiagnostics:targetingDiagnostics(input,targeting),planningDiagnostics:planningDiagnostics(planning),pipelineDiagnostics:pipelineDiagnostics(input.sourceVersion,graphInfo.graphReused,hash,performance.now()-pipelineStarted),warnings,violations:allErrors,status,optimalityClaim:planning.optimalityClaim,pipelineVersion:REAL_PASSIVE_PIPELINE_VERSION}
}
