import type { AnalyzerContext, BuildProfile, Confidence } from '../common/types'
import type { PassiveGraph, PassivePathSourceConnection } from '../passive-pathfinding/types'
import type { PassivePlanResult, PassivePlanningMode } from '../passive-planning/types'
import type { PassiveTargetAnalysis, PassiveTargetNode, PassiveTargetNodeType } from '../passive-targeting/types'
import type { PreparedPassiveTargetingContext } from '../passive-targeting/types'

export interface RealPassiveTree { metadata:{releaseTag:string;[key:string]:unknown};nodes:PassiveTargetNode[];connections:PassivePathSourceConnection[] }
export interface RealPassivePipelineInput { requestId:string;sourceVersion:string;buildProfile:BuildProfile;characterClassId:string;ascendancyId?:string;characterLevel:number;startNodeId?:string;pointBudget:number;targetProfile:'mapping'|'boss'|'balanced';planningMode:PassivePlanningMode;passiveTree:RealPassiveTree;passiveGraph?:PassiveGraph;preparedTargetingContext?:PreparedPassiveTargetingContext;alreadyAllocatedNodeIds?:string[];blockedNodeIds?:string[];requiredTargetNodeIds?:string[];excludedTargetNodeIds?:string[];requiredNodeTypes?:PassiveTargetNodeType[];maximumTargetingResults?:number;candidatePoolLimit:number;maximumSelectedTargets:number;minimumTargetScore:number;minimumConfidence:Confidence;allowKeystoneReoptimization:boolean;analyzerContext:AnalyzerContext }
export interface StartNodeResolution { resolvedStartNodeId:string|null;resolutionSource:'explicit'|'official-class-mapping'|null;classId:string;warnings:string[];violations:string[] }
export type PipelineStageId='validate-input'|'resolve-start-node'|'prepare-graph'|'evaluate-targets'|'prepare-planning-input'|'create-passive-plan'|'validate-output'|'complete'
export interface PipelineStage { stageId:PipelineStageId;status:'pending'|'complete'|'blocked';durationMs:number;warningCodes:string[];violationCodes:string[];inputSummary:Record<string,string|number|boolean>;outputSummary:Record<string,string|number|boolean> }
export interface GraphDiagnostics { graphSource:'provided'|'built'|'none';graphReused:boolean;graphBuildCount:number;graphNodeCount:number;graphConnectionCount:number }
export interface TargetingDiagnostics { evaluatedNodeCount:number;validCandidateCount:number;blockedCandidateCount:number;unresolvedStatLineCount:number;classificationCoveragePercent:number;minimumScoreFilter:number;minimumConfidenceFilter:Confidence;forwardedCandidateCount:number;preparedContextReused:boolean;preparedContextBuildCount:number }
export interface PlanningDiagnostics { candidatePoolSize:number;selectedTargetCount:number;pathSearchCount:number;pathCacheHitCount:number;usedPointBudget:number;remainingPointBudget:number;selectionStepCount:number;skippedTargetCount:number;stoppingReason:string }
export interface RequiredTargetDiagnostic { nodeId:string;treeStatus:'present'|'missing';targetingStatus:'eligible'|'blocked'|'socket-target'|'missing';planningStatus:'selected'|'skipped'|'failed'|'not-run';selected:boolean;pathStatus:'connected'|'unreachable'|'over-budget'|'not-run';violationCodes:string[];warningCodes:string[] }
export interface PipelineIssue { code:string;sourceModule:'pipeline'|'targeting'|'pathfinding'|'planning';stageId:PipelineStageId;nodeId?:string }
export type RealPassivePipelineStatus='complete'|'partial'|'blocked'|'invalid-input'|'source-version-mismatch'|'start-node-unresolved'|'targeting-failed'|'no-eligible-targets'|'required-target-failed'|'planning-failed'|'budget-exhausted'
export interface PipelineDiagnostics { graphReused:boolean;totalDurationMs?:number;deterministicResultHash:string;sourceVersion:string;pipelineVersion:string }
export interface RealPassivePipelineResult { requestId:string;sourceVersion:string;characterClassId:string;ascendancyId?:string;characterLevel:number;pointBudget:number;resolvedStartNodeId:string|null;startNodeResolution:StartNodeResolution;targetProfile:RealPassivePipelineInput['targetProfile'];planningMode:PassivePlanningMode;targetingResult:PassiveTargetAnalysis|null;planningResult:PassivePlanResult|null;selectedTargetIds:string[];allocatedNodeIds:string[];allocatedConnectionIds:string[];usedPointBudget:number;remainingPointBudget:number;requiredTargetDiagnostics:RequiredTargetDiagnostic[];pipelineStages:PipelineStage[];graphDiagnostics:GraphDiagnostics;targetingDiagnostics:TargetingDiagnostics;planningDiagnostics:PlanningDiagnostics;pipelineDiagnostics:PipelineDiagnostics;warnings:PipelineIssue[];violations:PipelineIssue[];status:RealPassivePipelineStatus;optimalityClaim:'heuristic'|'shortest-per-step'|'unknown';pipelineVersion:string }
