import type { ModifierDefinition } from '../../domain'
import { equipmentAnalyzer } from '../equipment/analyzer'
import { skillAnalyzer } from '../skills/analyzer'
import { supportAnalyzer } from '../supports/analyzer'
import { passiveAnalyzer } from '../passives/analyzer'
import { jewelAnalyzer } from '../jewels/analyzer'
import { uniqueAnalyzer } from '../uniques/analyzer'
import { rotationGenerator } from '../rotations/generator'
import { explanationGenerator } from '../explanations/generator'
import type { AnalyzerContext, BuildAnalysis, EngineRequest } from '../common/types'
import { runRealPassivePlanningIntegration } from './real-passive-integration'
import { estimateHitDamage } from '../damage-estimation'
export const ENGINE_VERSION = '0.1.0-placeholder'
export function analyzeBuild(request: EngineRequest, context: AnalyzerContext = { engineVersion: ENGINE_VERSION, fixtureMode: true }, modifiers: ModifierDefinition[] = []): BuildAnalysis {
  const orchestratorStarted=performance.now(),moduleTrace: string[] = []; const runtime = { ...context, trace: moduleTrace }; const equipment = equipmentAnalyzer.analyze(request, runtime, modifiers)
  const weaponTypes=request.weaponContext?.availableWeaponTypes??['any']; const weaponSets=request.weaponContext?.availableWeaponSets??['set-1']
  const realPassivePlanning=runRealPassivePlanningIntegration(request.realPassivePlanning,equipment.value.buildProfile,runtime,undefined,{'set-1':equipment.value.equipmentAnalysis.profileSet1,'set-2':equipment.value.equipmentAnalysis.profileSet2})
  const buildProfile=realPassivePlanning?.profileFeedback?.effectiveBuildProfile??equipment.value.buildProfile
  const equipmentAnalysis=realPassivePlanning?.profileFeedback?{...equipment.value.equipmentAnalysis,combinedProfile:buildProfile,profileSet1:realPassivePlanning.profileFeedback.effectiveWeaponSetProfiles['set-1'],profileSet2:realPassivePlanning.profileFeedback.effectiveWeaponSetProfiles['set-2']}:equipment.value.equipmentAnalysis
  const skillAnalysis = skillAnalyzer.analyzeRanked(buildProfile, request.candidates.skills, runtime, { equipmentAnalysis, character: request.input.character, goalProfile: request.input.goalProfile, availableWeaponTypes: weaponTypes }); const skills = skillAnalysis.allCandidates; const desiredSkillId=request.input.character.desiredMainSkillId; const selectedRecommendation = skills.find(item=>item.skillId===desiredSkillId)??skills.find(item => item.valid); const selectedSkill = request.candidates.skills.find(item => item.id === selectedRecommendation?.skillId) ?? request.candidates.skills[0]
  const supportAnalysis = selectedSkill ? supportAnalyzer.analyzeRanked(selectedSkill, buildProfile, request.candidates.supports, runtime, { skillRecommendation: selectedRecommendation, equipmentAnalysis, character: request.input.character, goalProfile: request.input.goalProfile, availableWeaponTypes: weaponTypes }) : { allCandidates: [], eligibleCandidates: [], blockedCandidates: [], topCandidates: [], topDamageSupports: [], topMappingSupports: [], topBossSupports: [], topUtilitySupports: [], topDefensiveSupports: [], status: 'placeholder' as const, analyzerVersion: 'none' }; const supports = supportAnalysis.allCandidates
  const selectedSupports = supportAnalysis.topCandidates; const passiveAnalysis = passiveAnalyzer.analyzeRanked(buildProfile, request.candidates.passives, runtime, { equipmentAnalysis, skillRecommendation: selectedRecommendation, supportRecommendations: selectedSupports, character: request.input.character, goalProfile: request.input.goalProfile }); const passives = passiveAnalysis.allCandidates
  const jewelAnalysis = jewelAnalyzer.analyzeRanked(buildProfile, request.candidates.jewels, runtime, { equipmentAnalysis, skillRecommendation: selectedRecommendation, supportRecommendations: selectedSupports, passiveAnalysis, character: request.input.character, technicalSelections:request.input.selectedJewels }); const jewels = jewelAnalysis.allCandidates; const uniqueAnalysis = uniqueAnalyzer.analyzeRanked(buildProfile, request.input, request.candidates.uniques, runtime, { equipmentAnalysis, skillRecommendation: selectedRecommendation, supportRecommendations: selectedSupports, passiveAnalysis, jewelAnalysis, availableWeaponTypes: weaponTypes }); const uniques = uniqueAnalysis.allCandidates
  const configuredSkillIds=new Set([desiredSkillId,...request.input.skillSetups.map(setup=>setup.skillId)].filter((value):value is string=>Boolean(value))); const rotationCandidates=[...(selectedRecommendation?.valid?[selectedRecommendation]:[]),...skillAnalysis.eligibleCandidates.filter(item=>item.skillId!==selectedRecommendation?.skillId&&configuredSkillIds.has(item.skillId))]; const selectedRotationSkills = rotationCandidates.filter((item, index, all) => { const definition = request.candidates.skills.find(skill => skill.id === item.skillId); const role = definition?.tags.includes('debuff') ? 'debuff' : definition?.tags.includes('buff') ? 'buff' : definition?.tags.includes('movement') ? 'movement' : definition?.tags.includes('defensive') ? 'defensive' : item.recommendedRole; return all.findIndex(candidate => { const candidateDefinition = request.candidates.skills.find(skill => skill.id === candidate.skillId); const candidateRole = candidateDefinition?.tags.includes('debuff') ? 'debuff' : candidateDefinition?.tags.includes('buff') ? 'buff' : candidateDefinition?.tags.includes('movement') ? 'movement' : candidateDefinition?.tags.includes('defensive') ? 'defensive' : candidate.recommendedRole; return candidateRole === role }) === index })
  const rotationAnalysis = rotationGenerator.generate({ buildProfile, skillAnalysis, selectedSkills: selectedRotationSkills, skillDefinitions: request.candidates.skills, selectedSupports, uniqueAnalysis, profileClarity: equipmentAnalysis.profileClarity, availableWeaponSets: weaponSets }, runtime); const rotations = { rotationAnalysis, mappingRotation: rotationAnalysis.mappingRotation, bossRotation: rotationAnalysis.bossRotation }; const allRecommendations = [...skills, ...supports, ...passives, ...jewels, ...uniques]
  const warnings = [...equipment.violations, ...skillAnalysis.allCandidates.flatMap(item => item.warnings), ...supportAnalysis.allCandidates.flatMap(item => item.warnings), ...passiveAnalysis.allCandidates.flatMap(item => item.warnings), ...allRecommendations.flatMap(item => item.violations), ...rotationAnalysis.warnings, ...rotationAnalysis.violations]
  const displayNames = Object.fromEntries([...request.candidates.skills, ...request.candidates.supports, ...request.candidates.jewels, ...request.candidates.uniques, ...request.candidates.passives.flatMap(item => [...(item.nodes ?? []), ...(item.cluster ? [{ id: item.cluster.clusterId, displayNameDe: item.cluster.clusterId }] : [])])].map(item => [item.id, item.displayNameDe])); const explanations = explanationGenerator.generate({ reasons: [...equipment.reasons, ...allRecommendations.flatMap(item => item.reasons)], violations: warnings, equipmentAnalysis, skillAnalysis, supportAnalysis, passiveAnalysis, jewelAnalysis, uniqueAnalysis, rotationAnalysis, displayNames }, runtime)
  if(realPassivePlanning?.performance)realPassivePlanning.performance.orchestratorDurationMs=performance.now()-orchestratorStarted
  const damageEstimate=estimateHitDamage({equipment:request.input.equipment,setups:request.input.skillSetups,skills:request.candidates.skills,fallbackSkillId:selectedRecommendation?.skillId})
  return { equipmentAnalysis, buildProfile, skillAnalysis, skillRecommendations: skills, supportAnalysis, supportRecommendations: supports, passiveAnalysis, passiveRecommendations: passives, jewelAnalysis, jewelRecommendations: jewels, uniqueAnalysis, uniqueRecommendations: uniques, ...rotations, explanations, warnings, status: 'placeholder', engineVersion: context.engineVersion, moduleTrace, damageEstimate, ...(realPassivePlanning?{realPassivePlanning}:{}) }
}
