import { describe,expect,it } from 'vitest'
import { analyzeBuild } from './analyze-build'
import { engineModifierFixtures,fixtureA } from '../fixtures'
import { REAL_PASSIVE_FIXTURE_GRAPH,REAL_PASSIVE_FIXTURE_TREE } from '../real-passive-pipeline/fixtures'
import type { AnalyzerContext } from '../common/types'
import { runRealPassivePlanningIntegration,type RealPassivePlanningConfiguration } from './real-passive-integration'
import { preparePassiveTargetingContext } from '../passive-targeting/prepared-context'
import { runRealPassivePipeline } from '../real-passive-pipeline/pipeline'

const context=():AnalyzerContext=>({engineVersion:'5I-test',fixtureMode:true})
const configuration=(value:Partial<RealPassivePlanningConfiguration>={}):RealPassivePlanningConfiguration=>({enabled:true,requestId:'5I-fixture',passiveTree:REAL_PASSIVE_FIXTURE_TREE,sourceVersion:'fixture',pointBudget:4,characterContext:{classId:'1',characterLevel:90},planningMode:'balanced',targetProfile:'balanced',candidatePoolLimit:10,maximumSelectedTargets:2,minimumTargetScore:0,minimumConfidence:'low',allowKeystoneReoptimization:false,...value})
const run=(value?:RealPassivePlanningConfiguration)=>analyzeBuild({...fixtureA,...(value?{realPassivePlanning:value}:{})},context(),engineModifierFixtures)

describe('reale Passive-Orchestratorintegration',()=>{
  it('ändert alte Aufrufe nicht und erzeugt keine Pipelineausgabe',()=>{const result=run();expect(result.realPassivePlanning).toBeUndefined();expect(result.moduleTrace).toEqual(['equipment','skills','supports','passives','jewels','uniques','rotations','explanations'])})
  it('führt eine deaktivierte Konfiguration nicht aus',()=>expect(run(configuration({enabled:false})).realPassivePlanning).toEqual({enabled:false,status:'disabled',detailMode:'compact',pipelineResult:null,issues:[],projection:null,performance:null}))
  it('verwendet Compact als kontrollierten Standard',()=>{const result=run(configuration()).realPassivePlanning!;expect(result.status).toBe('partial');expect(result.detailMode).toBe('compact');expect(result.pipelineResult?.status).toBe('partial');expect(result.pipelineResult?.optimalityClaim).toBe('heuristic');expect(result.pipelineResult?.pipelineDiagnostics.deterministicResultHash).toMatch(/^fnv1a32-/);expect(result.pipelineResult?.targetingResult).toBeUndefined();expect(result.performance?.graphBuildCount).toBe(1)})
  it('priorisiert Ressourcen nur im kontrollierten alternativen Planungslauf',()=>{const profile=run().buildProfile,seen:number[]=[];runRealPassivePlanningIntegration(configuration({resourcePriority:'undercoverage'}),profile,context(),value=>{seen.push(value.buildProfile.requirements.resourceNeed);return runRealPassivePipeline(value)});expect(seen).toEqual([100]);expect(profile.requirements.resourceNeed).not.toBe(100)})
  it('stellt Full gezielt mit bisherigem Diagnoseumfang bereit',()=>{const result=run(configuration({resultDetailMode:'full'})).realPassivePlanning!;expect(result.detailMode).toBe('full');expect(result.pipelineResult?.targetingResult?.allCandidates).toHaveLength(9);expect(result.pipelineResult?.planningResult).toBeDefined()})
  it('blockiert fehlendes und ungültiges Budget vor dem Pipelineaufruf',()=>{expect(run(configuration({pointBudget:undefined})).realPassivePlanning).toMatchObject({status:'invalid-input',pipelineResult:null,issues:[{code:'missing-point-budget'}]});expect(run(configuration({pointBudget:-1})).realPassivePlanning?.pipelineResult).toMatchObject({status:'invalid-input',violations:expect.arrayContaining([expect.objectContaining({code:'invalid-point-budget',stageId:'validate-input'})])})})
  it('meldet fehlenden Baum strukturiert',()=>expect(run(configuration({passiveTree:undefined})).realPassivePlanning).toMatchObject({status:'invalid-input',issues:expect.arrayContaining([expect.objectContaining({code:'missing-passive-tree',stageId:'validate-input'})])}))
  it('erhält Versionsdiagnosen unverändert',()=>expect(run(configuration({sourceVersion:'other'})).realPassivePlanning?.pipelineResult).toMatchObject({status:'source-version-mismatch',violations:expect.arrayContaining([expect.objectContaining({code:'source-version-mismatch',stageId:'validate-input'})])}))
  it('verwendet explizite oder eindeutige offizielle Startauflösung und rät nicht',()=>{expect(run(configuration({startNodeId:'S'})).realPassivePlanning?.pipelineResult?.startNodeResolution.resolutionSource).toBe('explicit');expect(run(configuration()).realPassivePlanning?.pipelineResult?.startNodeResolution.resolutionSource).toBe('official-class-mapping');expect(run(configuration({characterContext:{classId:'missing',characterLevel:90}})).realPassivePlanning?.pipelineResult).toMatchObject({status:'start-node-unresolved',startNodeResolution:{resolvedStartNodeId:null}})})
  it('erhält Required-Zieldiagnosen und Aszendenzgrenze',()=>{const required=run(configuration({requiredTargetNodeIds:['L']})).realPassivePlanning?.pipelineResult;expect(required?.requiredTargetDiagnostics).toEqual(expect.arrayContaining([expect.objectContaining({nodeId:'L',selected:true})]));const foreign=run(configuration({requiredTargetNodeIds:['AX']})).realPassivePlanning?.pipelineResult;expect(foreign?.requiredTargetDiagnostics[0]).toMatchObject({nodeId:'AX',selected:false})})
  it('verwendet einen passenden vorbereiteten Graphen ohne Aufbau',()=>{const result=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture'})).realPassivePlanning!;expect(result.pipelineResult?.graphDiagnostics).toMatchObject({graphSource:'provided',graphReused:true,graphBuildCount:0});expect(result.performance?.graphReused).toBe(true)})
  it('weist einen vorbereiteten Graphen anderer Version vor dem Lauf zurück',()=>expect(run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'other'})).realPassivePlanning).toMatchObject({status:'invalid-input',pipelineResult:null,issues:[{code:'prepared-graph-source-version-mismatch'}]}))
  it('hält synthetische Analyse und realen Plan strikt getrennt',()=>{const result=run(configuration());expect(result.passiveAnalysis).toBeDefined();expect(result.realPassivePlanning?.pipelineResult?.selectedTargetIds).toBeDefined();expect(result.passiveRecommendations).not.toBe(result.realPassivePlanning?.pipelineResult?.selectedTargetIds)})
  it('teilt normale Punkte in einen gemeinsamen Stamm und zwei Waffen-Set-Pläne',()=>{const result=run(configuration({pointBudget:4,weaponSetPointBudget:2})).realPassivePlanning!,plans=result.weaponSetPlanning!;expect(plans.specializationPointLimit).toBe(2);expect(plans.sharedPointBudget).toBe(2);expect(plans.set1.pointBudget).toBe(4);expect(plans.set2.pointBudget).toBe(4);expect(plans.set1.usedPointBudget).toBeLessThanOrEqual(4);expect(plans.set2.usedPointBudget).toBeLessThanOrEqual(4);expect(plans.shared.allocatedNodeIds.every(id=>plans.set1.allocatedNodeIds.includes(id)&&plans.set2.allocatedNodeIds.includes(id))).toBe(true)})
  it('erfindet ohne unterschiedliche Waffenprofile keine künstlich verschiedenen Set-Ziele',()=>{const profile=run().buildProfile,result=runRealPassivePlanningIntegration(configuration({pointBudget:4,weaponSetPointBudget:2}),profile,context())!,plans=result.weaponSetPlanning!;expect(plans).toBeDefined();expect(plans.set1.usedPointBudget).toBeLessThanOrEqual(4);expect(plans.set2.usedPointBudget).toBeLessThanOrEqual(4);expect(plans.set1.selectedTargetIds).toEqual(plans.set2.selectedTargetIds)})
  it('teilt nur den geometrischen Pfadcache zwischen den getrennt bewerteten Set-Plänen',()=>{const profile=run().buildProfile,seen:unknown[]=[];runRealPassivePlanningIntegration(configuration({pointBudget:4,weaponSetPointBudget:2}),profile,context(),value=>{if(value.planningScope==='weapon-set')seen.push(value.pathCache);return runRealPassivePipeline(value)});expect(seen).toHaveLength(2);expect(seen[0]).toBeDefined();expect(seen[0]).toBe(seen[1])})
  it('plant bei unterschiedlichen Skilltreibern tatsächlich unterschiedliche Waffenset-Ziele',()=>{
    const profile=run().buildProfile,set1=structuredClone(profile),set2=structuredClone(profile),specific:ReturnType<typeof runRealPassivePipeline>[]=[]
    for(const key of ['physical','fire','cold','lightning','chaos'] as const){set1.damageTypes[key]=key==='lightning'?100:0;set2.damageTypes[key]=key==='cold'?100:0}
    set1.mechanics.projectile=100;set1.mechanics.attack=100;set1.mechanics.spell=0
    set2.mechanics.projectile=0;set2.mechanics.attack=0;set2.mechanics.spell=100
    const result=runRealPassivePlanningIntegration(configuration({pointBudget:4,weaponSetPointBudget:2,planningMode:'damage-first',maximumSelectedTargets:1}),profile,context(),value=>{const planned=runRealPassivePipeline(value);if(value.planningScope==='weapon-set')specific.push(planned);return planned},{'set-1':set1,'set-2':set2})!,plans=result.weaponSetPlanning!
    expect(specific).toHaveLength(2)
    expect(specific[0].violations).toEqual([])
    expect(specific[1].violations).toEqual([])
    expect(specific[0].selectedTargetIds).not.toEqual(specific[1].selectedTargetIds)
    expect(specific[1].selectedTargetIds.some(id=>id==='C'||id==='C1')).toBe(true)
    expect(plans.set1.selectedTargetIds).toContain('L')
    expect(plans.set1.selectedTargetIds).not.toEqual(plans.set2.selectedTargetIds)
  })
  it('verwendet für Waffenset-Punkte weder Juwelenfassungen noch Keystones',()=>{const profile=run().buildProfile,result=runRealPassivePlanningIntegration(configuration({pointBudget:4,weaponSetPointBudget:2,requiredTargetNodeIds:['J','K'],allowKeystoneReoptimization:true}),profile,context())!,plans=result.weaponSetPlanning!;const shared=new Set(plans.shared.allocatedNodeIds);for(const plan of [plans.set1,plans.set2]){const specific=plan.allocatedNodeIds.filter(id=>!shared.has(id));expect(specific).not.toContain('J');expect(specific).not.toContain('K')}})
  it('erzeugt ohne Waffen-Set-Punkte keinen zweiten Plan',()=>expect(run(configuration({weaponSetPointBudget:0})).realPassivePlanning?.weaponSetPlanning).toBeUndefined())
  it('erzeugt einen getrennten Aszendenzplan mit höchstens acht Punkten',()=>{const result=run(configuration({characterContext:{classId:'1',ascendancyId:'foreign',characterLevel:90},ascendancyPointBudget:1})).realPassivePlanning!;expect(result.ascendancyPlanning).toMatchObject({planningScope:'ascendancy',pointBudget:1,usedPointBudget:1,remainingPointBudget:0});expect(result.pipelineResult?.allocatedNodeIds).not.toEqual(expect.arrayContaining(['AS','AX']))})
  it('führt belegte Aszendenz- und Baumskalierungen in das wirksame Profil zurück',()=>{const baseline=run().buildProfile.damageTypes.lightning,result=run(configuration({characterContext:{classId:'1',ascendancyId:'foreign',characterLevel:90},ascendancyPointBudget:1,pointBudget:2}));const feedback=result.realPassivePlanning!.profileFeedback!;expect(feedback.ascendancy?.appliedNodeIds).toEqual(['AX']);expect(feedback.ascendancy?.fieldDeltas).toEqual(expect.arrayContaining([expect.objectContaining({field:'damageTypes.lightning',delta:20})]));expect(feedback.shared?.appliedNodeIds.length).toBeGreaterThan(0);expect(result.buildProfile).toEqual(feedback.effectiveBuildProfile);expect(result.buildProfile.damageTypes.lightning).toBeGreaterThan(baseline)})
  it('überträgt gemeinsame, Aszendenz- und set-spezifische Wirkungen getrennt in beide Waffenprofile',()=>{const result=run(configuration({characterContext:{classId:'1',ascendancyId:'foreign',characterLevel:90},ascendancyPointBudget:1,pointBudget:4,weaponSetPointBudget:2})).realPassivePlanning!,profiles=result.profileFeedback!.effectiveWeaponSetProfiles;expect(profiles['set-1'].damageTypes.lightning).toBeGreaterThan(0);expect(profiles['set-2'].damageTypes.lightning).toBeGreaterThan(0);expect(result.profileFeedback?.set1).toBeDefined();expect(result.profileFeedback?.set2).toBeDefined();expect(result.weaponSetPlanning?.set1.pointBudget).toBe(4);expect(result.weaponSetPlanning?.set2.pointBudget).toBe(4)})
  it('verwendet einen passenden vorbereiteten Targeting-Kontext ohne Neuaufbau',()=>{const prepared=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes,'fixture'),result=run(configuration({preparedTargetingContext:prepared})).realPassivePlanning!;expect(result.performance).toMatchObject({targetingContextReused:true,targetingContextBuildCount:0});expect(result.pipelineResult?.targetingDiagnostics).toMatchObject({preparedContextReused:true,preparedContextBuildCount:0})})
  it('weist einen Targeting-Kontext eines anderen Baums kontrolliert zurück',()=>{const prepared=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes.slice(0,-1),'fixture'),result=run(configuration({preparedTargetingContext:prepared})).realPassivePlanning!;expect(result.pipelineResult).toMatchObject({status:'invalid-input',violations:expect.arrayContaining([expect.objectContaining({code:'prepared-targeting-context-tree-mismatch'})])})})
  it('liefert mit und ohne Graph denselben fachlichen Pipelinehash',()=>{const built=run(configuration()).realPassivePlanning!,reused=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture'})).realPassivePlanning!;expect(reused.pipelineResult?.pipelineDiagnostics.deterministicResultHash).toBe(built.pipelineResult?.pipelineDiagnostics.deterministicResultHash);expect(reused.pipelineResult?.selectedTargetIds).toEqual(built.pipelineResult?.selectedTargetIds)})
  it('teilt bei mehreren Profilen nur den unveränderlichen Graphen',()=>{const first=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture',requestId:'first'})).realPassivePlanning!,second=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture',requestId:'second',pointBudget:2})).realPassivePlanning!;expect(first.pipelineResult).not.toBe(second.pipelineResult);expect(first.pipelineResult?.pipelineDiagnostics.deterministicResultHash).not.toBe(second.pipelineResult?.pipelineDiagnostics.deterministicResultHash);expect(REAL_PASSIVE_FIXTURE_GRAPH.nodeCount).toBe(9)})
  it('eskaliert ausschließlich unerwartete interne Fehler in den fatalen Pfad',()=>{const profile=run().buildProfile;expect(()=>runRealPassivePlanningIntegration(configuration(),profile,context(),()=>{throw new Error('unexpected')})).toThrow('unexpected')})
})
