import { describe,expect,it } from 'vitest'
import { analyzeBuild } from './analyze-build'
import { engineModifierFixtures,fixtureA } from '../fixtures'
import { REAL_PASSIVE_FIXTURE_GRAPH,REAL_PASSIVE_FIXTURE_TREE } from '../real-passive-pipeline/fixtures'
import type { AnalyzerContext } from '../common/types'
import { runRealPassivePlanningIntegration,type RealPassivePlanningConfiguration } from './real-passive-integration'
import { preparePassiveTargetingContext } from '../passive-targeting/prepared-context'

const context=():AnalyzerContext=>({engineVersion:'5I-test',fixtureMode:true})
const configuration=(value:Partial<RealPassivePlanningConfiguration>={}):RealPassivePlanningConfiguration=>({enabled:true,requestId:'5I-fixture',passiveTree:REAL_PASSIVE_FIXTURE_TREE,sourceVersion:'fixture',pointBudget:4,characterContext:{classId:'1',characterLevel:90},planningMode:'balanced',targetProfile:'balanced',candidatePoolLimit:10,maximumSelectedTargets:2,minimumTargetScore:0,minimumConfidence:'low',allowKeystoneReoptimization:false,...value})
const run=(value?:RealPassivePlanningConfiguration)=>analyzeBuild({...fixtureA,...(value?{realPassivePlanning:value}:{})},context(),engineModifierFixtures)

describe('reale Passive-Orchestratorintegration',()=>{
  it('ändert alte Aufrufe nicht und erzeugt keine Pipelineausgabe',()=>{const result=run();expect(result.realPassivePlanning).toBeUndefined();expect(result.moduleTrace).toEqual(['equipment','skills','supports','passives','jewels','uniques','rotations','explanations'])})
  it('führt eine deaktivierte Konfiguration nicht aus',()=>expect(run(configuration({enabled:false})).realPassivePlanning).toEqual({enabled:false,status:'disabled',detailMode:'compact',pipelineResult:null,issues:[],projection:null,performance:null}))
  it('verwendet Compact als kontrollierten Standard',()=>{const result=run(configuration()).realPassivePlanning!;expect(result.status).toBe('partial');expect(result.detailMode).toBe('compact');expect(result.pipelineResult?.status).toBe('partial');expect(result.pipelineResult?.optimalityClaim).toBe('heuristic');expect(result.pipelineResult?.pipelineDiagnostics.deterministicResultHash).toMatch(/^fnv1a32-/);expect(result.pipelineResult?.targetingResult).toBeUndefined();expect(result.performance?.graphBuildCount).toBe(1)})
  it('stellt Full gezielt mit bisherigem Diagnoseumfang bereit',()=>{const result=run(configuration({resultDetailMode:'full'})).realPassivePlanning!;expect(result.detailMode).toBe('full');expect(result.pipelineResult?.targetingResult?.allCandidates).toHaveLength(9);expect(result.pipelineResult?.planningResult).toBeDefined()})
  it('blockiert fehlendes und ungültiges Budget vor dem Pipelineaufruf',()=>{expect(run(configuration({pointBudget:undefined})).realPassivePlanning).toMatchObject({status:'invalid-input',pipelineResult:null,issues:[{code:'missing-point-budget'}]});expect(run(configuration({pointBudget:-1})).realPassivePlanning?.pipelineResult).toMatchObject({status:'invalid-input',violations:expect.arrayContaining([expect.objectContaining({code:'invalid-point-budget',stageId:'validate-input'})])})})
  it('meldet fehlenden Baum strukturiert',()=>expect(run(configuration({passiveTree:undefined})).realPassivePlanning).toMatchObject({status:'invalid-input',issues:expect.arrayContaining([expect.objectContaining({code:'missing-passive-tree',stageId:'validate-input'})])}))
  it('erhält Versionsdiagnosen unverändert',()=>expect(run(configuration({sourceVersion:'other'})).realPassivePlanning?.pipelineResult).toMatchObject({status:'source-version-mismatch',violations:expect.arrayContaining([expect.objectContaining({code:'source-version-mismatch',stageId:'validate-input'})])}))
  it('verwendet explizite oder eindeutige offizielle Startauflösung und rät nicht',()=>{expect(run(configuration({startNodeId:'S'})).realPassivePlanning?.pipelineResult?.startNodeResolution.resolutionSource).toBe('explicit');expect(run(configuration()).realPassivePlanning?.pipelineResult?.startNodeResolution.resolutionSource).toBe('official-class-mapping');expect(run(configuration({characterContext:{classId:'missing',characterLevel:90}})).realPassivePlanning?.pipelineResult).toMatchObject({status:'start-node-unresolved',startNodeResolution:{resolvedStartNodeId:null}})})
  it('erhält Required-Zieldiagnosen und Aszendenzgrenze',()=>{const required=run(configuration({requiredTargetNodeIds:['L']})).realPassivePlanning?.pipelineResult;expect(required?.requiredTargetDiagnostics).toEqual(expect.arrayContaining([expect.objectContaining({nodeId:'L',selected:true})]));const foreign=run(configuration({requiredTargetNodeIds:['AX']})).realPassivePlanning?.pipelineResult;expect(foreign?.requiredTargetDiagnostics[0]).toMatchObject({nodeId:'AX',selected:false})})
  it('verwendet einen passenden vorbereiteten Graphen ohne Aufbau',()=>{const result=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture'})).realPassivePlanning!;expect(result.pipelineResult?.graphDiagnostics).toMatchObject({graphSource:'provided',graphReused:true,graphBuildCount:0});expect(result.performance?.graphReused).toBe(true)})
  it('weist einen vorbereiteten Graphen anderer Version vor dem Lauf zurück',()=>expect(run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'other'})).realPassivePlanning).toMatchObject({status:'invalid-input',pipelineResult:null,issues:[{code:'prepared-graph-source-version-mismatch'}]}))
  it('hält synthetische Analyse und realen Plan strikt getrennt',()=>{const result=run(configuration());expect(result.passiveAnalysis).toBeDefined();expect(result.realPassivePlanning?.pipelineResult?.selectedTargetIds).toBeDefined();expect(result.passiveRecommendations).not.toBe(result.realPassivePlanning?.pipelineResult?.selectedTargetIds)})
  it('verwendet einen passenden vorbereiteten Targeting-Kontext ohne Neuaufbau',()=>{const prepared=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes,'fixture'),result=run(configuration({preparedTargetingContext:prepared})).realPassivePlanning!;expect(result.performance).toMatchObject({targetingContextReused:true,targetingContextBuildCount:0});expect(result.pipelineResult?.targetingDiagnostics).toMatchObject({preparedContextReused:true,preparedContextBuildCount:0})})
  it('weist einen Targeting-Kontext eines anderen Baums kontrolliert zurück',()=>{const prepared=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes.slice(0,-1),'fixture'),result=run(configuration({preparedTargetingContext:prepared})).realPassivePlanning!;expect(result.pipelineResult).toMatchObject({status:'invalid-input',violations:expect.arrayContaining([expect.objectContaining({code:'prepared-targeting-context-tree-mismatch'})])})})
  it('liefert mit und ohne Graph denselben fachlichen Pipelinehash',()=>{const built=run(configuration()).realPassivePlanning!,reused=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture'})).realPassivePlanning!;expect(reused.pipelineResult?.pipelineDiagnostics.deterministicResultHash).toBe(built.pipelineResult?.pipelineDiagnostics.deterministicResultHash);expect(reused.pipelineResult?.selectedTargetIds).toEqual(built.pipelineResult?.selectedTargetIds)})
  it('teilt bei mehreren Profilen nur den unveränderlichen Graphen',()=>{const first=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture',requestId:'first'})).realPassivePlanning!,second=run(configuration({passiveGraph:REAL_PASSIVE_FIXTURE_GRAPH,passiveGraphSourceVersion:'fixture',requestId:'second',pointBudget:2})).realPassivePlanning!;expect(first.pipelineResult).not.toBe(second.pipelineResult);expect(first.pipelineResult?.pipelineDiagnostics.deterministicResultHash).not.toBe(second.pipelineResult?.pipelineDiagnostics.deterministicResultHash);expect(REAL_PASSIVE_FIXTURE_GRAPH.nodeCount).toBe(9)})
  it('eskaliert ausschließlich unerwartete interne Fehler in den fatalen Pfad',()=>{const profile=run().buildProfile;expect(()=>runRealPassivePlanningIntegration(configuration(),profile,context(),()=>{throw new Error('unexpected')})).toThrow('unexpected')})
})
