/* global performance,process,console,TextEncoder */
import{describe,expect,it}from'vitest';import officialTree from '../../../generated/poe2-tree/tree.json';import{buildPassiveGraph}from'../passive-pathfinding/graph';import{preparePassiveTargetingContext}from'../passive-targeting/prepared-context';import{engineModifierFixtures,fixtureA,fixtureB,fixtureC}from'../fixtures';import{analyzeBuild}from'./analyze-build';
const context={engineVersion:'5I.1-performance',fixtureMode:true},bytes=value=>new TextEncoder().encode(JSON.stringify(value)).length,stats=values=>({median:[...values].sort((a,b)=>a-b)[Math.floor(values.length/2)],minimum:Math.min(...values),maximum:Math.max(...values)}),round=value=>Math.round(value*100)/100,config=(requestId,graph,prepared,detailMode='compact')=>({enabled:true,requestId,passiveTree:officialTree,sourceVersion:'0.5.2',pointBudget:15,characterContext:{classId:'0',characterLevel:90},planningMode:'balanced',targetProfile:'balanced',passiveGraph:graph,passiveGraphSourceVersion:graph?'0.5.2':undefined,preparedTargetingContext:prepared,resultDetailMode:detailMode,candidatePoolLimit:10,maximumSelectedTargets:1,minimumTargetScore:0,minimumConfidence:'low',allowKeystoneReoptimization:false}),request=(fixture,planning)=>({...fixture,realPassivePlanning:planning}),measure=fn=>{const started=performance.now(),value=fn();return{ms:round(performance.now()-started),value}};
describe('5I.1 Orchestrator-Performance',()=>{it('misst reproduzierbare Baseline, Projektion und Prepared Context strukturell',()=>{
 const graphMeasure=measure(()=>buildPassiveGraph(officialTree)),graph=graphMeasure.value,contextMeasure=measure(()=>preparePassiveTargetingContext(officialTree.nodes,'0.5.2')),prepared=contextMeasure.value
 analyzeBuild(request(fixtureA,config('warmup',graph,prepared)),context,engineModifierFixtures)
 const noPipeline=[],withoutPrepared=[],withPrepared=[],compactSerialization=[],heapFull=[],heapCompact=[];let fullSample,compactSample
 for(let index=0;index<3;index++){
  noPipeline.push(measure(()=>analyzeBuild(fixtureA,context,engineModifierFixtures)).ms)
  const fullHeapStart=process.memoryUsage().heapUsed,full=measure(()=>analyzeBuild(request(fixtureA,config(`run-${index}`,graph,undefined,'full')),context,engineModifierFixtures));heapFull.push(round((process.memoryUsage().heapUsed-fullHeapStart)/1048576));withoutPrepared.push(full.value.realPassivePlanning.performance.pipelineDurationMs);fullSample=full.value.realPassivePlanning
  const compactHeapStart=process.memoryUsage().heapUsed,compact=measure(()=>analyzeBuild(request(fixtureA,config(`run-${index}`,graph,prepared)),context,engineModifierFixtures));heapCompact.push(round((process.memoryUsage().heapUsed-compactHeapStart)/1048576));withPrepared.push(compact.value.realPassivePlanning.performance.pipelineDurationMs);compactSerialization.push(compact.value.realPassivePlanning.performance.serializationMs);compactSample=compact.value.realPassivePlanning
 }
 const fullResult=fullSample.pipelineResult,compactResult=compactSample.pipelineResult,fullSize=bytes(fullResult),compactSize=bytes(compactResult),targeting=fullResult.targetingResult,planning=fullResult.planningResult
 const sizeBreakdown={targetingResult:{count:targeting.allCandidates.length,bytes:bytes(targeting)},allCandidates:{count:targeting.allCandidates.length,bytes:bytes(targeting.allCandidates)},eligibleCandidates:{count:targeting.eligibleCandidates.length,bytes:bytes(targeting.eligibleCandidates)},blockedCandidates:{count:targeting.blockedCandidates.length,bytes:bytes(targeting.blockedCandidates)},rankings:{count:12,bytes:['topDamageTargets','topDefensiveTargets','topMappingTargets','topBossTargets','topSpeedTargets','topResourceTargets','topAttributeTargets','topClassSynergyTargets','topAscendancyTargets','topNotables','topKeystones','jewelSocketTargets'].reduce((sum,key)=>sum+bytes(targeting[key]),0)},coverage:{count:targeting.coverage.unresolvedPatterns.length,bytes:bytes(targeting.coverage)},planningResult:{count:planning.selectedTargets.length,bytes:bytes(planning)},selectedTargets:{count:planning.selectedTargets.length,bytes:bytes(planning.selectedTargets)},selectionSteps:{count:planning.selectionSteps.length,bytes:bytes(planning.selectionSteps)},requiredDiagnostics:{count:fullResult.requiredTargetDiagnostics.length,bytes:bytes(fullResult.requiredTargetDiagnostics)},pipelineStages:{count:fullResult.pipelineStages.length,bytes:bytes(fullResult.pipelineStages)},issues:{count:fullResult.warnings.length+fullResult.violations.length,bytes:bytes([fullResult.warnings,fullResult.violations])},graphDiagnostics:{count:1,bytes:bytes(fullResult.graphDiagnostics)}}
 const consecutive=measure(()=>[0,1].map(index=>analyzeBuild(request(fixtureA,config(`consecutive-${index}`,graph,prepared)),context,engineModifierFixtures))).ms,threeProfiles=measure(()=>[fixtureA,fixtureB,fixtureC].map((fixture,index)=>analyzeBuild(request(fixture,config(`profile-${index}`,graph,prepared)),context,engineModifierFixtures))).ms
 const report={runtime:process.version,platform:`${process.platform}-${process.arch}`,warmupRuns:1,measuredRuns:3,noPipelineMs:stats(noPipeline),pipelineWithoutPreparedContextMs:stats(withoutPrepared),pipelineWithPreparedContextMs:stats(withPrepared),targetingWithoutPreparedContextMs:stats([fullSample.performance.targetingMs]),targetingWithPreparedContextMs:stats([compactSample.performance.targetingMs]),graphBuildMs:graphMeasure.ms,preparedContextBuildMs:contextMeasure.ms,planningMs:compactSample.performance.planningMs,validationMs:compactSample.performance.outputValidationMs,fullProjectionMs:fullSample.performance.projectionMs,compactProjectionMs:compactSample.performance.projectionMs,compactSerializationMs:stats(compactSerialization),fullSizeBytes:fullSize,compactSizeBytes:compactSize,sizeReductionPercent:round((1-compactSize/fullSize)*100),heapFullMiB:stats(heapFull),heapCompactMiB:stats(heapCompact),twoConsecutivePreparedMs:consecutive,threeProfilesSharedGraphAndContextMs:threeProfiles,sizeBreakdown};console.info('REAL_PASSIVE_5I1_PERFORMANCE',JSON.stringify(report))
 expect(compactSize).toBeLessThan(fullSize*.3);expect(compactSize).toBeLessThan(10_000_000);expect(compactSample.performance.targetingContextBuildCount).toBe(0);expect(compactSample.performance.targetingContextReused).toBe(true);expect(fullSample.performance.targetingContextBuildCount).toBe(1);expect(compactResult).not.toHaveProperty('targetingResult');expect(compactResult).not.toHaveProperty('passiveGraph');expect(compactResult.pipelineDiagnostics.deterministicResultHash).toBe(fullResult.pipelineDiagnostics.deterministicResultHash)
},120000)})
