import { describe,expect,it } from 'vitest'
import type { ClientToWorkerMessage,WorkerToClientMessage } from './contracts'
import { REAL_PASSIVE_WORKER_PROTOCOL_VERSION,envelope } from './contracts'
import { createRealPassiveWorkerClient } from './client'

class FakeWorker {listeners={message:[] as Array<(event:MessageEvent<WorkerToClientMessage>)=>void>,error:[] as Array<(event:Event)=>void>,messageerror:[] as Array<(event:Event)=>void>};messages:ClientToWorkerMessage[]=[];terminated=false;postMessage(message:ClientToWorkerMessage){this.messages.push(message)}terminate(){this.terminated=true}addEventListener(type:'message'|'error'|'messageerror',listener:never){this.listeners[type].push(listener as never)}emit(message:WorkerToClientMessage){this.listeners.message.forEach(listener=>listener({data:message} as MessageEvent<WorkerToClientMessage>))}crash(){this.listeners.error.forEach(listener=>listener(new Event('error')))}}
const init={sourceVersion:'fixture',expectedTreeIdentity:'tree',expectedPipelineVersion:'1',expectedContextFormatVersion:'1'}
describe('Real-Passive Workerclient',()=>{
 it('ordnet requestIds zu, publiziert Fortschritt und beendet ohne verwaiste Promises',async()=>{const worker=new FakeWorker(),client=createRealPassiveWorkerClient({workerFactory:()=>worker});const promise=client.initialize(init);worker.emit(envelope('initialize','initialization-progress',{stage:'loading-tree',sequence:1,elapsedMs:1,requestId:'initialize'}));expect(client.getState().progress?.stage).toBe('loading-tree');worker.emit(envelope('initialize','ready',{state:'ready',reused:false,sourceVersion:'fixture',treeIdentity:'tree',graphNodeCount:9,graphConnectionCount:7}));await expect(promise).resolves.toMatchObject({status:'ready'});const disposing=client.dispose();worker.emit(envelope('dispose','disposed',{state:'disposed'}));await disposing;expect(worker.terminated).toBe(true)})
 it('terminiert bei aktivem Abbruch hart und verlangt Neuinitialisierung',async()=>{const worker=new FakeWorker(),client=createRealPassiveWorkerClient({workerFactory:()=>worker});const ready=client.initialize(init);worker.emit(envelope('initialize','ready',{state:'ready',reused:false,sourceVersion:'fixture',treeIdentity:'tree',graphNodeCount:9,graphConnectionCount:7}));await ready;const running=client.analyze('a',{request:{} as never,planning:{} as never});const cancelled=await client.cancel('a','test');await expect(running).resolves.toMatchObject({status:'cancelled'});expect(cancelled).toMatchObject({status:'cancelled',reusable:false});expect(worker.terminated).toBe(true)})
 it('lehnt zweite lokale requestId und Analyse vor ready ab',async()=>{const worker=new FakeWorker(),client=createRealPassiveWorkerClient({workerFactory:()=>worker});await expect(client.analyze('a',{request:{} as never,planning:{} as never})).rejects.toThrow('worker-not-ready')})
 it('löst bei error und messageerror alle offenen Promises',async()=>{const worker=new FakeWorker(),client=createRealPassiveWorkerClient({workerFactory:()=>worker});const pending=client.initialize(init);worker.crash();await expect(pending).rejects.toThrow('worker-crashed');expect(client.getState()).toMatchObject({status:'failed',reusable:false})})
 it('sendet ausschließlich definierte versionierte Nachrichten',()=>{const worker=new FakeWorker(),client=createRealPassiveWorkerClient({workerFactory:()=>worker});void client.initialize(init);expect(worker.messages[0]).toMatchObject({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'initialize',messageType:'initialize'})})
})
