import type { AnalyzePayload,ClientToWorkerMessage,InitializePayload,RealPassiveWorkerClientState,RuntimeError,WorkerToClientMessage } from './contracts'
import { REAL_PASSIVE_WORKER_PROTOCOL_VERSION } from './contracts'

interface WorkerPort {postMessage(message:ClientToWorkerMessage):void;terminate():void;addEventListener(type:'message',listener:(event:MessageEvent<WorkerToClientMessage>)=>void):void;addEventListener(type:'error'|'messageerror',listener:(event:Event)=>void):void}
export interface RealPassiveWorkerClient {initialize(payload:InitializePayload):Promise<RealPassiveWorkerClientState>;analyze(requestId:string,payload:AnalyzePayload):Promise<RealPassiveWorkerClientState>;cancel(requestId:string,reason?:string):Promise<RealPassiveWorkerClientState>;getState():RealPassiveWorkerClientState;subscribe(listener:(state:RealPassiveWorkerClientState)=>void):()=>void;dispose():Promise<void>}
export interface RealPassiveWorkerClientOptions {workerFactory?:()=>WorkerPort;responseTimeoutMs?:number}
const defaultFactory=():WorkerPort=>new Worker(new URL('./worker.ts',import.meta.url),{type:'module'})
export function createRealPassiveWorkerClient(options:RealPassiveWorkerClientOptions={}):RealPassiveWorkerClient{
 let worker:WorkerPort|undefined,state:RealPassiveWorkerClientState={status:'uninitialized',reusable:false},generation=0;const listeners=new Set<(state:RealPassiveWorkerClientState)=>void>(),pending=new Map<string,{resolve:(state:RealPassiveWorkerClientState)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>}>(),factory=options.workerFactory??defaultFactory,timeout=options.responseTimeoutMs??120000
 const publish=(next:RealPassiveWorkerClientState)=>{state=next;listeners.forEach(listener=>listener(state))},failAll=(code:string)=>{const failure:RuntimeError={code,severity:'error',source:'client',stage:'worker-lifecycle',message:'Worker became unavailable.',recoverable:true,workerState:'failed'};publish({status:'failed',error:failure,reusable:false});pending.forEach(value=>{clearTimeout(value.timer);value.reject(new Error(code))});pending.clear()}
 const ensure=()=>{if(worker)return worker;const value=factory(),own=++generation;value.addEventListener('message',event=>{if(own!==generation)return;const message=event.data;if(message.protocolVersion!==REAL_PASSIVE_WORKER_PROTOCOL_VERSION){failAll('protocol-version-mismatch');return}if(message.messageType==='initialization-progress'||message.messageType==='analysis-progress'){publish({...state,progress:message.payload});return}if(message.messageType==='error'){const item=pending.get(message.requestId);publish({status:'failed',error:message.payload,reusable:message.payload.recoverable});if(item){clearTimeout(item.timer);pending.delete(message.requestId);item.resolve(state)}return}if(message.messageType==='ready'){publish({status:'ready',initialization:message.payload,reusable:true});settle(message.requestId);return}if(message.messageType==='result'){publish({status:'completed',result:message.payload.result,reusable:true});settle(message.requestId);return}if(message.messageType==='cancelled'){publish({status:'cancelled',currentRequestId:message.requestId,reusable:message.payload.workerStillReady});settle(message.requestId);return}if(message.messageType==='disposed'){publish({status:'disposed',reusable:false});settle(message.requestId)}});value.addEventListener('error',()=>own===generation&&failAll('worker-crashed'));value.addEventListener('messageerror',()=>own===generation&&failAll('worker-message-error'));worker=value;return value}
 function settle(requestId:string){const item=pending.get(requestId);if(item){clearTimeout(item.timer);pending.delete(requestId);item.resolve(state)}}
 const send=(message:ClientToWorkerMessage)=>new Promise<RealPassiveWorkerClientState>((resolve,reject)=>{if(pending.has(message.requestId)){reject(new Error('duplicate-request-id'));return}const timer=setTimeout(()=>{pending.delete(message.requestId);failAll('worker-response-timeout');reject(new Error('worker-response-timeout'))},timeout);pending.set(message.requestId,{resolve,reject,timer});ensure().postMessage(message)})
 const initialize=(payload:InitializePayload)=>{publish({status:'initializing',currentRequestId:'initialize',reusable:false});return send({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'initialize',messageType:'initialize',payload})}
 const analyze=(requestId:string,payload:AnalyzePayload)=>{if(state.status!=='ready'&&state.status!=='completed')return Promise.reject(new Error('worker-not-ready'));publish({...state,status:'analyzing',currentRequestId:requestId,result:undefined});return send({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId,messageType:'analyze',payload})}
 const cancel=async(requestId:string,reason?:string)=>{if(state.status!=='analyzing'||state.currentRequestId!==requestId)return send({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId,messageType:'cancel',payload:{reason}});publish({...state,status:'cancelling'});worker?.terminate();worker=undefined;generation++;pending.forEach(value=>{clearTimeout(value.timer);value.resolve({status:'cancelled',currentRequestId:requestId,reusable:false})});pending.clear();publish({status:'cancelled',currentRequestId:requestId,reusable:false});return state}
 const dispose=async()=>{if(!worker){publish({status:'disposed',reusable:false});return}const request=send({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'dispose',messageType:'dispose',payload:{}});await request;worker?.terminate();worker=undefined;generation++;pending.clear()}
 return{initialize,analyze,cancel,getState:()=>state,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener)},dispose}
}
