import { describe,expect,it,vi } from 'vitest'
import { engineModifierFixtures,fixtureA } from '../../engine/fixtures'
import { REAL_PASSIVE_FIXTURE_TREE } from '../../engine/real-passive-pipeline/fixtures'
import { passiveTargetingTreeIdentity,PASSIVE_TARGETING_CONTEXT_FORMAT_VERSION } from '../../engine/passive-targeting/prepared-context'
import { REAL_PASSIVE_PIPELINE_VERSION } from '../../engine/real-passive-pipeline/config'
import type { ClientToWorkerMessage,WorkerToClientMessage } from './contracts'
import { REAL_PASSIVE_WORKER_PROTOCOL_VERSION } from './contracts'
import { createRealPassiveWorkerDispatcher } from './dispatcher'
import { analyzeBuild } from '../../engine/orchestration/analyze-build'

const initialize=(values:Record<string,string>={}):ClientToWorkerMessage=>({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'init',messageType:'initialize',payload:{sourceVersion:'fixture',expectedTreeIdentity:passiveTargetingTreeIdentity(REAL_PASSIVE_FIXTURE_TREE.nodes),expectedPipelineVersion:REAL_PASSIVE_PIPELINE_VERSION,expectedContextFormatVersion:PASSIVE_TARGETING_CONTEXT_FORMAT_VERSION,...values}})
const analyze=(requestId='analysis'):ClientToWorkerMessage=>({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId,messageType:'analyze',payload:{request:fixtureA,modifiers:engineModifierFixtures,planning:{requestId,sourceVersion:'fixture',pointBudget:4,characterContext:{classId:'1',characterLevel:90},planningMode:'balanced',targetProfile:'balanced',candidatePoolLimit:10,maximumSelectedTargets:2,minimumTargetScore:0,minimumConfidence:'low'}}})
describe('Real-Passive Workerdispatcher',()=>{
 it('versioniert das Protokoll und weist unbekannte Versionen strukturiert ab',async()=>{const sent:WorkerToClientMessage[]=[],dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE},value=>sent.push(value));await dispatcher.dispatch({...initialize(),protocolVersion:'0'});expect(sent[0]).toMatchObject({requestId:'init',messageType:'error',payload:{code:'protocol-version-mismatch'}})})
 it('führt unbekannte Nachrichtentypen niemals dynamisch aus',async()=>{const sent:WorkerToClientMessage[]=[],dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE},value=>sent.push(value));await dispatcher.dispatch({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'unknown',messageType:'eval',payload:{functionName:'analyzeBuild'}} as never);expect(sent[0]).toMatchObject({messageType:'error',payload:{code:'unknown-message-type'}})})
 it('initialisiert Graph und Context einmal und verwendet dieselbe Baumidentität wieder',async()=>{const sent:WorkerToClientMessage[]=[],dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE},value=>sent.push(value));await dispatcher.dispatch(initialize());await dispatcher.dispatch(initialize());const ready=sent.filter(value=>value.messageType==='ready');expect(ready).toHaveLength(2);expect(ready.map(value=>value.payload)).toEqual(expect.arrayContaining([expect.objectContaining({reused:false}),expect.objectContaining({reused:true})]));expect(sent.filter(value=>value.messageType==='initialization-progress')).toHaveLength(5)})
 it('lehnt andere Version, Baumidentität und Analyse vor ready ab',async()=>{const sent:WorkerToClientMessage[]=[],dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE},value=>sent.push(value));await dispatcher.dispatch(analyze());expect(sent.at(-1)).toMatchObject({messageType:'error',payload:{code:'worker-not-ready'}});await dispatcher.dispatch(initialize({expectedTreeIdentity:'other'}));expect(sent.at(-1)).toMatchObject({messageType:'error',payload:{code:'tree-identity-mismatch'}})})
 it('ruft nur den Orchestrator auf und liefert ausschließlich Compact mit stabilem Hash',async()=>{const sent:WorkerToClientMessage[]=[],spy=vi.fn(analyzeBuild),dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE,analyze:spy},value=>sent.push(value));await dispatcher.dispatch(initialize());await dispatcher.dispatch(analyze());const result=sent.find(value=>value.messageType==='result');expect(spy).toHaveBeenCalledOnce();expect(result?.messageType==='result'&&result.payload.result.realPassivePlanning).toMatchObject({detailMode:'compact',performance:{graphBuildCount:0,targetingContextBuildCount:0}});expect(result?.messageType==='result'&&result.payload.result.realPassivePlanning?.pipelineResult?.targetingResult).toBeUndefined();expect(result?.messageType==='result'&&result.payload.result.realPassivePlanning?.pipelineResult?.pipelineDiagnostics.deterministicResultHash).toMatch(/^fnv1a32-/)})
 it('erhält Required-Ziele, Budgetfehler und dispose kontrolliert',async()=>{const sent:WorkerToClientMessage[]=[],dispatcher=createRealPassiveWorkerDispatcher({tree:REAL_PASSIVE_FIXTURE_TREE},value=>sent.push(value));await dispatcher.dispatch(initialize());const required=analyze() as Extract<ClientToWorkerMessage,{messageType:'analyze'}>;required.payload.planning.requiredTargetNodeIds=['L'];await dispatcher.dispatch(required);expect(sent.find(value=>value.messageType==='result'&&value.requestId==='analysis')).toMatchObject({payload:{result:{realPassivePlanning:{pipelineResult:{requiredTargetDiagnostics:[{nodeId:'L',selected:true}]}}}}});await dispatcher.dispatch({protocolVersion:REAL_PASSIVE_WORKER_PROTOCOL_VERSION,requestId:'dispose',messageType:'dispose',payload:{}});expect(dispatcher.state()).toBe('disposed');await dispatcher.dispatch(analyze('late'));expect(sent.at(-1)).toMatchObject({messageType:'error',payload:{code:'worker-disposed'}})})
})
