import { describe,expect,it,vi } from 'vitest'
import type { RealPassiveWorkerClient,RealPassiveWorkerClientState } from '../../runtime/real-passive-worker'
import { ascendancyDefinitions,initialEquipment,skillSetups } from '../../data'
import { createPassiveAnalysisController } from './controller'
import { createPassiveAnalysisInputSignature,type PassiveAnalysisUiInput } from './adapter'
class FakeClient implements RealPassiveWorkerClient{state:RealPassiveWorkerClientState={status:'uninitialized',reusable:false};listeners=new Set<(state:RealPassiveWorkerClientState)=>void>();initialize=vi.fn(async()=>this.emit({status:'ready',reusable:true}));analyze=vi.fn(async()=>this.emit({status:'completed',reusable:true,result:{realPassivePlanning:{pipelineResult:null}} as never}));cancel=vi.fn(async()=>this.emit({status:'cancelled',reusable:false}));dispose=vi.fn(async()=>undefined);getState=()=>this.state;subscribe=(value:(state:RealPassiveWorkerClientState)=>void)=>{this.listeners.add(value);return()=>this.listeners.delete(value)};emit(value:RealPassiveWorkerClientState){this.state=value;this.listeners.forEach(listener=>listener(value));return value}}
const input=():PassiveAnalysisUiInput=>({character:{classId:'class-official-6',ascendancyId:ascendancyDefinitions.find(value=>value.classId==='class-official-6')?.id??'',level:70,goalProfile:'balanced'},equipment:structuredClone(initialEquipment),setups:structuredClone(skillSetups),pointBudget:20,planningMode:'balanced'})
describe('Passive-Analyse-Controller',()=>{
 it('initialisiert kontrolliert und verhindert Analyse vor ready',async()=>{const client=new FakeClient(),controller=createPassiveAnalysisController(client);await controller.analyze(input());expect(client.analyze).not.toHaveBeenCalled();expect(controller.getState().validationErrors).toContain('worker-not-ready');await controller.initialize();expect(controller.getState().status).toBe('ready');expect(client.initialize).toHaveBeenCalledOnce()})
 it('führt Nutzeranalyse aus und markiert relevante Änderungen stale',async()=>{const client=new FakeClient(),controller=createPassiveAnalysisController(client);await controller.initialize();const value=input();controller.inputsChanged(createPassiveAnalysisInputSignature(value));await controller.analyze(value);expect(client.analyze).toHaveBeenCalledOnce();value.pointBudget++;controller.inputsChanged(createPassiveAnalysisInputSignature(value));expect(controller.getState().status).toBe('stale')})
 it('bricht hart ab und verlangt Neuinitialisierung',async()=>{const client=new FakeClient(),controller=createPassiveAnalysisController(client);await controller.initialize();client.analyze=vi.fn(async()=>new Promise<RealPassiveWorkerClientState>(()=>undefined));void controller.analyze(input());await Promise.resolve();await controller.cancel();expect(client.cancel).toHaveBeenCalledOnce();expect(controller.getState()).toMatchObject({status:'cancelled',reinitializationRequired:true,result:undefined})})
 it('entsorgt den Client beim Unmount-Vertrag',async()=>{const client=new FakeClient(),controller=createPassiveAnalysisController(client);await controller.dispose();expect(client.dispose).toHaveBeenCalledOnce()})
 it('verwendet für identische fachliche Eingaben dieselbe stabile Request-ID',async()=>{const client=new FakeClient(),controller=createPassiveAnalysisController(client),value=input(),requestId=`ui-${createPassiveAnalysisInputSignature(value)}`;await controller.initialize();await controller.analyze(value);await controller.analyze(value);expect(client.analyze).toHaveBeenCalledTimes(2);expect(client.analyze).toHaveBeenNthCalledWith(1,requestId,expect.anything());expect(client.analyze).toHaveBeenNthCalledWith(2,requestId,expect.anything())})
})
