import { createRealPassiveWorkerClient,type RealPassiveWorkerClient,type RealPassiveWorkerClientState } from '../../runtime/real-passive-worker'
import { buildRealPassiveWorkerRequest,realPassiveInitializePayload,type PassiveAnalysisUiInput } from './adapter'

export type PassiveAnalysisUiStatus=RealPassiveWorkerClientState['status']|'stale'
export interface PassiveAnalysisUiState extends Omit<RealPassiveWorkerClientState,'status'> {status:PassiveAnalysisUiStatus;inputSignature?:string;resultSignature?:string;reinitializationRequired:boolean;validationErrors:string[]}
export interface PassiveAnalysisController {initialize():Promise<void>;analyze(input:PassiveAnalysisUiInput):Promise<void>;cancel():Promise<void>;retry():Promise<void>;inputsChanged(signature:string):void;getState():PassiveAnalysisUiState;subscribe(listener:()=>void):()=>void;dispose():Promise<void>}
export function createPassiveAnalysisController(client:RealPassiveWorkerClient=createRealPassiveWorkerClient()):PassiveAnalysisController{
 let state:PassiveAnalysisUiState={status:'uninitialized',reusable:false,reinitializationRequired:false,validationErrors:[]},sequence=0,disposed=false
 const listeners=new Set<()=>void>(),publish=(next:PassiveAnalysisUiState)=>{state=next;listeners.forEach(value=>value())}
 let unsubscribe:()=>void=()=>undefined
 const attach=()=>{unsubscribe=client.subscribe(next=>{if(disposed)return;const stale=state.resultSignature&&state.inputSignature!==state.resultSignature;publish({...state,...next,status:stale&&next.status==='completed'?'stale':next.status,reinitializationRequired:next.status==='cancelled'&&!next.reusable,validationErrors:state.validationErrors})})};attach()
 const initialize=async()=>{if(disposed||state.status==='initializing'||state.status==='ready')return;publish({...state,status:'initializing',error:undefined,validationErrors:[]});await client.initialize(realPassiveInitializePayload())}
 const analyze=async(input:PassiveAnalysisUiInput)=>{if(disposed||state.status==='analyzing'||state.status==='cancelling')return;if(state.status!=='ready'&&state.status!=='completed'&&state.status!=='stale'){publish({...state,validationErrors:['worker-not-ready']});return}const requestId=`ui-${Date.now()}-${++sequence}`,adapted=buildRealPassiveWorkerRequest(input,requestId);if(adapted.errors.length){publish({...state,validationErrors:adapted.errors});return}publish({...state,status:'analyzing',inputSignature:adapted.signature,resultSignature:undefined,validationErrors:[],currentRequestId:requestId});await client.analyze(requestId,adapted.payload!);const latest=client.getState();if(latest.status==='completed')publish({...state,...latest,resultSignature:adapted.signature,status:state.inputSignature===adapted.signature?'completed':'stale'})}
 const cancel=async()=>{if(state.status!=='analyzing'||!state.currentRequestId)return;publish({...state,status:'cancelling'});await client.cancel(state.currentRequestId,'user-request');publish({...state,status:'cancelled',progress:undefined,result:undefined,reusable:false,reinitializationRequired:true})}
 const retry=async()=>{if(disposed)return;unsubscribe();await client.dispose();client=createRealPassiveWorkerClient();attach();publish({status:'uninitialized',reusable:false,reinitializationRequired:false,validationErrors:[]});await initialize()}
 return{initialize,analyze,cancel,retry,inputsChanged(signature){const stale=Boolean(state.resultSignature&&state.resultSignature!==signature);publish({...state,inputSignature:signature,status:stale?'stale':state.status})},getState:()=>state,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener)},async dispose(){disposed=true;unsubscribe();listeners.clear();await client.dispose()},}
}
