import { useEffect,useMemo,useState,useSyncExternalStore } from 'react'
import type { CharacterConfiguration,EquipmentEntry,SkillSetup } from '../../domain'
import { createPassiveAnalysisController,type PassiveAnalysisController } from './controller'
import { createPassiveAnalysisInputSignature,REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET,type PassiveAnalysisUiInput,type PassivePlanningMode } from './adapter'
import './real-passive-analysis.css'

const stageText:Record<string,string>={'loading-tree':'Baum wird geladen','validating-tree':'Baum wird geprüft','building-graph':'Graph wird aufgebaut','preparing-targeting-context':'Analysekontext wird vorbereitet',ready:'Bereit','validating-request':'Eingaben werden geprüft','running-orchestrator':'Analyse läuft','validating-result':'Ergebnis wird geprüft',completed:'Fertig'}
const errorText:Record<string,string>={'invalid-point-budget':'Das Punktebudget muss eine ganze Zahl zwischen 1 und 123 sein.','class-start-unavailable':'Für die gewählte Klasse ist kein eindeutiger unterstützter Startknoten verfügbar.','invalid-character-profile':'Das Charakterprofil ist ungültig.','worker-not-ready':'Der Analyse-Worker ist noch nicht bereit.','worker-crashed':'Der Analyse-Worker wurde unerwartet beendet.','worker-response-timeout':'Die Analysezeit wurde überschritten.','protocol-version-mismatch':'Worker und App verwenden nicht dieselbe Protokollversion.','tree-identity-mismatch':'Die lokale Baumversion stimmt nicht mit dem Worker überein.'}
const statusText:Record<string,string>={uninitialized:'Noch nicht initialisiert',initializing:'Initialisierung läuft',ready:'Bereit',analyzing:'Analyse läuft',cancelling:'Analyse wird abgebrochen',completed:'Analyse abgeschlossen',cancelled:'Analyse abgebrochen',failed:'Laufzeitfehler',stale:'Ergebnis veraltet',disposed:'Beendet'}
export function RealPassiveAnalysis({character,equipment,setups,controller:provided}:{character:CharacterConfiguration;equipment:EquipmentEntry[];setups:SkillSetup[];controller?:PassiveAnalysisController}){
 const [controller]=useState(()=>provided??createPassiveAnalysisController()),[pointBudget,setPointBudget]=useState(20),[planningMode,setPlanningMode]=useState<PassivePlanningMode>('balanced')
 const state=useSyncExternalStore(controller.subscribe,controller.getState,controller.getState)
 const input=useMemo<PassiveAnalysisUiInput>(()=>({character,equipment,setups,pointBudget,planningMode}),[character,equipment,setups,pointBudget,planningMode]),signature=createPassiveAnalysisInputSignature(input)
 useEffect(()=>controller.inputsChanged(signature),[controller,signature]);useEffect(()=>()=>{if(!provided)void controller.dispose()},[controller,provided])
 const pipeline=state.result?.realPassivePlanning?.pipelineResult,plan=pipeline&&'plan'in pipeline?pipeline.plan:undefined,targets=plan?.selectedTargets.slice(0,8)??[],issues=[...(pipeline?.violations??[]),...(pipeline?.warnings??[])]
 const validation=state.validationErrors.map(code=>errorText[code]??code),runtimeError=state.error&&(errorText[state.error.code]??state.error.message),canStart=['ready','completed','stale'].includes(state.status)&&Number.isInteger(pointBudget)&&pointBudget>=1&&pointBudget<=REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET
 return <section className="passive-analysis" id="real-passive-analysis"><h2>6. Reale Passive-Analyse</h2><p>Die Berechnung startet nur auf Knopfdruck und kann einige Sekunden dauern.</p><div className="analysis-status" aria-live="polite"><b>Status:</b> {statusText[state.status]}{state.progress&&<> · {stageText[state.progress.stage]??state.progress.stage}</>}</div>
  <div className="form-grid"><label>Punktebudget<input type="number" min="1" max={REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET} value={pointBudget} onChange={event=>setPointBudget(Number(event.target.value))} aria-describedby="budget-help"/></label><label>Planungsmodus<select value={planningMode} onChange={event=>setPlanningMode(event.target.value as PassivePlanningMode)}><option value="value-first">Höchster Nutzen</option><option value="efficiency-first">Höchste Effizienz</option><option value="balanced">Ausgewogen</option></select></label></div><p id="budget-help" className="muted">Gib an, wie viele normale passive Punkte für die Planung verwendet werden dürfen. Level, Quest- und Aszendenzpunkte werden nicht automatisch eingerechnet.</p>
  {(validation.length>0||runtimeError)&&<div className="analysis-error" role="alert" tabIndex={-1}>{runtimeError&&<p>{runtimeError}</p>}{validation.map(value=><p key={value}>{value}</p>)}</div>}
  <div className="analysis-actions">{state.status==='uninitialized'&&<button onClick={()=>void controller.initialize()}>Analyse vorbereiten</button>}<button disabled={!canStart} title={!canStart?'Worker muss bereit sein und alle Eingaben müssen gültig sein.':''} onClick={()=>void controller.analyze(input)}>Build analysieren</button>{state.status==='analyzing'||state.status==='cancelling'?<button className="danger" onClick={()=>void controller.cancel()} disabled={state.status==='cancelling'}>Analyse abbrechen</button>:null}{(state.status==='failed'||state.reinitializationRequired)&&<button className="secondary" onClick={()=>void controller.retry()}>Worker neu initialisieren</button>}</div>
  {state.status==='stale'&&<p className="analysis-stale" role="status">Dieses Ergebnis gehört zu älteren Eingaben. Bitte erneut analysieren.</p>}
  {pipeline&&<div className="analysis-result"><h3>Passive-Planung</h3><dl><div><dt>Gesamtstatus</dt><dd>{pipeline.status}</dd></div><div><dt>Budget</dt><dd>{pipeline.pointBudget}</dd></div><div><dt>Verbraucht</dt><dd>{pipeline.usedPointBudget}</dd></div><div><dt>Verbleibend</dt><dd>{pipeline.remainingPointBudget}</dd></div><div><dt>Ziele</dt><dd>{pipeline.selectedTargetIds.length}</dd></div><div><dt>Pfade</dt><dd>{targets.length}</dd></div><div><dt>Belegte Knoten</dt><dd>{pipeline.allocatedNodeIds.length}</dd></div></dl><h4>Wichtigste Ziele</h4>{targets.length?<ol>{targets.map((target,index)=><li key={target.nodeId}><b>{target.displayName||target.nodeId}</b> <small>#{target.nodeId}</small> · Reihenfolge {index+1} · {target.incrementalPointCost} Punkte · {target.pathNodeIds.length} Pfadknoten · Confidence {target.confidence}<br/><small>{target.reasons.join(', ')||'Keine zusätzliche Begründung im Compact-Ergebnis.'}</small></li>)}</ol>:<p>Keine Ziele ausgewählt.</p>}<p><b>Required-Ziele:</b> {pipeline.requiredTargetDiagnostics.length?pipeline.requiredTargetDiagnostics.map(value=>`${value.nodeId}: ${value.selected?'erfüllt':'nicht erfüllt'}`).join(', '):'Keine expliziten Required-Ziele.'}</p><p><b>Unresolved Stats:</b> {plan?.unresolvedStats.lineCount??0}</p>{issues.length>0&&<details><summary>Warnungen und technische Issues ({issues.length})</summary><ul>{issues.slice(0,50).map((issue,index)=><li key={`${issue.code}-${index}`}>{issue.code}</li>)}</ul></details>}<details><summary>Technische Details</summary><p>Quelle {pipeline.sourceVersion} · Hash {pipeline.pipelineDiagnostics.deterministicResultHash} · Compact</p></details><p className="heuristic-note">Die Passive-Planung ist heuristisch. Sie liefert einen nachvollziehbaren, aber nicht garantiert global optimalen Plan.</p></div>}
 </section>
}
