import { useEffect,useMemo,useState,useSyncExternalStore } from 'react'
import type { CharacterConfiguration,EquipmentEntry,SkillSetup } from '../../domain'
import { createPassiveAnalysisController,type PassiveAnalysisController } from './controller'
import { createPassiveAnalysisInputSignature,REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET,type PassiveAnalysisUiInput,type PassivePlanningMode } from './adapter'
import './real-passive-analysis.css'
import type { CompactRealPassivePipelineResult } from '../../engine/orchestration/real-passive-result-projection'

const stageText:Record<string,string>={'loading-tree':'Baum wird geladen','validating-tree':'Baum wird geprüft','building-graph':'Graph wird aufgebaut','preparing-targeting-context':'Analysekontext wird vorbereitet',ready:'Bereit','validating-request':'Eingaben werden geprüft','running-orchestrator':'Analyse läuft','validating-result':'Ergebnis wird geprüft',completed:'Fertig'}
const errorText:Record<string,string>={'invalid-point-budget':'Das Punktebudget muss eine ganze Zahl zwischen 1 und 123 sein.','invalid-ascendancy-point-budget':'Aszendenzpunkte müssen eine ganze Zahl zwischen 0 und 8 sein.','missing-ascendancy-for-points':'Für Aszendenzpunkte muss eine Aszendenz ausgewählt sein.','class-start-unavailable':'Für die gewählte Klasse ist kein eindeutiger unterstützter Startknoten verfügbar.','invalid-character-profile':'Das Charakterprofil ist ungültig.','worker-not-ready':'Der Analyse-Worker ist noch nicht bereit.','worker-crashed':'Der Analyse-Worker wurde unerwartet beendet.','worker-response-timeout':'Die Analysezeit wurde überschritten.','protocol-version-mismatch':'Worker und App verwenden nicht dieselbe Protokollversion.','tree-identity-mismatch':'Die lokale Baumversion stimmt nicht mit dem Worker überein.'}
const statusText:Record<string,string>={uninitialized:'Noch nicht initialisiert',initializing:'Initialisierung läuft',ready:'Bereit',analyzing:'Analyse läuft',cancelling:'Analyse wird abgebrochen',completed:'Analyse abgeschlossen',cancelled:'Analyse abgebrochen',failed:'Laufzeitfehler',stale:'Ergebnis veraltet',disposed:'Beendet'}
export interface PassivePlanPresentation {
 results:{shared:CompactRealPassivePipelineResult|null;'set-1':CompactRealPassivePipelineResult|null;'set-2':CompactRealPassivePipelineResult|null;ascendancy:CompactRealPassivePipelineResult|null}
 status:ReturnType<PassiveAnalysisController['getState']>['status']
}
export function RealPassiveAnalysis({character,equipment,setups,controller:provided,onPlanPresentation,planVisible=true,onTogglePlan,onShowPlan}:{character:CharacterConfiguration;equipment:EquipmentEntry[];setups:SkillSetup[];controller?:PassiveAnalysisController;onPlanPresentation?:(value:PassivePlanPresentation)=>void;planVisible?:boolean;onTogglePlan?:()=>void;onShowPlan?:()=>void}){
 const automaticPointBudget=Math.max(1,Math.min(REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET,Math.trunc(character.level)-1+Math.max(0,Math.trunc(character.additionalPassivePoints??0))))
 const [controller]=useState(()=>provided??createPassiveAnalysisController()),[pointBudgetOverride,setPointBudgetOverride]=useState<number|null>(null),[weaponSetPointOverride,setWeaponSetPointOverride]=useState<number|null>(null),[planningMode,setPlanningMode]=useState<PassivePlanningMode>('value-first'),pointBudget=pointBudgetOverride??automaticPointBudget,weaponSetPointBudget=Math.min(pointBudget,weaponSetPointOverride??24),ascendancyPointBudget=character.ascendancyPassivePoints??0
 const state=useSyncExternalStore(controller.subscribe,controller.getState,controller.getState)
 const setWeaponSetPointBudget=(value:number)=>setWeaponSetPointOverride(Math.min(24,value))
 const input=useMemo<PassiveAnalysisUiInput>(()=>({character,equipment,setups,pointBudget,weaponSetPointBudget,ascendancyPointBudget,planningMode}),[ascendancyPointBudget,character,equipment,setups,pointBudget,weaponSetPointBudget,planningMode]),signature=createPassiveAnalysisInputSignature(input)
 useEffect(()=>controller.inputsChanged(signature),[controller,signature]);useEffect(()=>()=>{if(!provided)void controller.dispose()},[controller,provided])
 const integration=state.result?.realPassivePlanning,weaponPlans=integration?.weaponSetPlanning,ascendancyPlan=integration?.ascendancyPlanning,profileFeedback=integration?.profileFeedback
 const pipeline=weaponPlans?.shared??integration?.pipelineResult,plan=pipeline&&'plan'in pipeline?pipeline.plan:undefined,targets=plan?.selectedTargets.slice(0,8)??[],issues=[...(pipeline?.violations??[]),...(pipeline?.warnings??[])]
 const compact=pipeline&&'plan'in pipeline?pipeline as CompactRealPassivePipelineResult:null
 const compactSet1=weaponPlans?.set1&&'plan'in weaponPlans.set1?weaponPlans.set1 as CompactRealPassivePipelineResult:null
 const compactSet2=weaponPlans?.set2&&'plan'in weaponPlans.set2?weaponPlans.set2 as CompactRealPassivePipelineResult:null
 const compactAscendancy=ascendancyPlan&&'plan'in ascendancyPlan?ascendancyPlan as CompactRealPassivePipelineResult:null
 useEffect(()=>{const visible=['completed','stale'].includes(state.status);onPlanPresentation?.({results:{shared:visible?compact:null,'set-1':visible?compactSet1:null,'set-2':visible?compactSet2:null,ascendancy:visible?compactAscendancy:null},status:state.status})},[compact,compactAscendancy,compactSet1,compactSet2,onPlanPresentation,state.status])
 const validation=state.validationErrors.map(code=>errorText[code]??code),runtimeError=state.error&&(errorText[state.error.code]??state.error.message),canStart=['ready','completed','stale'].includes(state.status)&&Number.isInteger(pointBudget)&&pointBudget>=1&&pointBudget<=REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET
 return <section className="passive-analysis" id="real-passive-analysis"><h2>6. Reale Passive-Analyse</h2><p>Die Berechnung startet nur auf Knopfdruck und kann einige Sekunden dauern.</p><div className="analysis-status" aria-live="polite"><b>Status:</b> {statusText[state.status]}{state.progress&&<> · {stageText[state.progress.stage]??state.progress.stage}</>}</div>
  {state.progress&&<output hidden className="analysis-performance" data-worker-elapsed-ms={state.progress.elapsedMs.toFixed(2)} data-cache-hit={String(state.progress.summary?.cacheHit===true)}/>}
  <div className="form-grid"><label>Normale Passivpunkte<input type="number" min="1" max={REAL_PASSIVE_UI_MAXIMUM_POINT_BUDGET} value={pointBudget} onChange={event=>setPointBudgetOverride(Number(event.target.value))} aria-describedby="budget-help"/></label><label>Davon Waffenset-Punkte (max. 24)<input type="number" min="0" max={Math.min(24,pointBudget)} value={weaponSetPointBudget} onChange={event=>setWeaponSetPointBudget(Math.max(0,Math.min(pointBudget,Number(event.target.value))))}/></label><label>Aszendenzpunkte<output>{ascendancyPointBudget} / 8</output></label><label>Planungsmodus<select value={planningMode} onChange={event=>setPlanningMode(event.target.value as PassivePlanningMode)}><option value="value-first">Höchster Nutzen</option><option value="efficiency-first">Höchste Effizienz</option><option value="balanced">Ausgewogen</option></select></label></div><p id="budget-help" className="muted">Die Waffenset-Punkte sind Teil des normalen Budgets: Bis zu 24 normale Punkte dürfen für Set 1 und Set 2 unterschiedlich belegt werden. Beispiel: 24 umschaltbare normale Punkte ergeben 24 aktive Set-1-Belegungen oder 24 aktive Set-2-Belegungen, niemals 48 gleichzeitig aktive Zusatzpunkte. Aszendenzpunkte sind ein eigener Topf mit höchstens 8 Punkten.</p>
  {(validation.length>0||runtimeError)&&<div className="analysis-error" role="alert" tabIndex={-1}>{runtimeError&&<p>{runtimeError}</p>}{validation.map(value=><p key={value}>{value}</p>)}</div>}
  <div className="analysis-actions">{state.status==='uninitialized'&&<button onClick={()=>void controller.initialize()}>Analyse vorbereiten</button>}<button disabled={!canStart} title={!canStart?'Worker muss bereit sein und alle Eingaben müssen gültig sein.':''} onClick={()=>void controller.analyze(input)}>Build analysieren</button>{state.status==='analyzing'||state.status==='cancelling'?<button className="danger" onClick={()=>void controller.cancel()} disabled={state.status==='cancelling'}>Analyse abbrechen</button>:null}{(state.status==='failed'||state.reinitializationRequired)&&<button className="secondary" onClick={()=>void controller.retry()}>Worker neu initialisieren</button>}</div>
  {state.status==='stale'&&<p className="analysis-stale" role="status">Dieses Ergebnis gehört zu älteren Eingaben. Bitte erneut analysieren.</p>}
  {weaponPlans&&<div className="weapon-set-plan-tabs" aria-label="Gemeinsame Passivpläne"><p><b>Alle Pläne werden gemeinsam im Baum angezeigt:</b> Gelb gemeinsam, Rot nur Waffenset 1, Grün nur Waffenset 2 und Violett Aszendenz.</p><p className="muted">{weaponPlans.sharedPointBudget} fest gemeinsame Punkte · {weaponPlans.specializationPointLimit} normale Punkte dürfen je Waffenset unterschiedlich belegt sein. Jedes aktive Set besitzt weiterhin höchstens {pointBudget} normale Punkte.</p></div>}
  {ascendancyPlan&&<div className="weapon-set-plan-tabs" aria-label="Aszendenzplan"><p><b>Aszendenz:</b> {ascendancyPlan.usedPointBudget}/{ascendancyPlan.pointBudget} Punkte werden gleichzeitig im eingebetteten Aszendenzbaum angezeigt.</p></div>}
  {profileFeedback&&<details className="passive-feedback-summary"><summary>Berücksichtigte Passive-Skalierungen</summary><p>Aszendenz: {profileFeedback.ascendancy?.appliedNodeIds.length??0} · Gemeinsamer Baum: {profileFeedback.shared?.appliedNodeIds.length??0} · Set 1: {profileFeedback.set1?.appliedNodeIds.length??0} · Set 2: {profileFeedback.set2?.appliedNodeIds.length??0} belegte Knoten.</p><p className="muted">Diese belegten Wirkungen fließen in Skill-, Support-, Juwel-, Unique- und Waffensetbewertungen ein. Unklare Knotenzeilen erzeugen keine Skalierung.</p></details>}
  {pipeline&&<div className="analysis-result"><h3>Passive-Planung</h3><dl><div><dt>Gesamtstatus</dt><dd>{pipeline.status}</dd></div><div><dt>Budget</dt><dd>{pipeline.pointBudget}</dd></div><div><dt>Verbraucht</dt><dd>{pipeline.usedPointBudget}</dd></div><div><dt>Verbleibend</dt><dd>{pipeline.remainingPointBudget}</dd></div><div><dt>Ziele</dt><dd>{pipeline.selectedTargetIds.length}</dd></div><div><dt>Pfade</dt><dd>{targets.length}</dd></div><div><dt>Belegte Knoten</dt><dd>{pipeline.allocatedNodeIds.length}</dd></div><div><dt>Hervorgehobene Verbindungen</dt><dd>{pipeline.allocatedConnectionIds.length}</dd></div><div><dt>Darstellung</dt><dd aria-live="polite">{state.status==='stale'?'Veralteter Plan':planVisible?'Aktuell und sichtbar':'Aktuell und ausgeblendet'}</dd></div></dl>{compact&&<><div className="analysis-actions"><button onClick={onShowPlan}>Plan im Baum anzeigen</button><button className="secondary" aria-pressed={planVisible} onClick={onTogglePlan}>{planVisible?'Plan ausblenden':'Plan anzeigen'}</button></div><div className="tree-plan-legend" aria-label="Legende der Planmarkierungen"><span><i/>Startpunkt</span><span className="path"><i/>Geplanter Weg</span><span><i/>Empfohlenes Ziel</span><span className="required"><i/>Pflichtziel</span><span className="blocked"><i/>Nicht erreichbar oder blockiert</span><span className="stale"><i/>Veralteter Plan</span></div></>}<h4>Wichtigste Ziele</h4>{targets.length?<ol>{targets.map((target,index)=><li key={target.nodeId}><b>{target.displayName||target.nodeId}</b> <small>#{target.nodeId}</small> · Reihenfolge {index+1} · {target.incrementalPointCost} Punkte · {target.pathNodeIds.length} Pfadknoten · Confidence {target.confidence}<br/><small>{target.reasons.join(', ')||'Keine zusätzliche Begründung im Compact-Ergebnis.'}</small></li>)}</ol>:<p>Keine Ziele ausgewählt.</p>}<p><b>Required-Ziele:</b> {pipeline.requiredTargetDiagnostics.length?pipeline.requiredTargetDiagnostics.map(value=>`${value.nodeId}: ${value.selected?'erfüllt':'nicht erfüllt'}`).join(', '):'Keine expliziten Required-Ziele.'}</p><p><b>Unresolved Stats:</b> {plan?.unresolvedStats.lineCount??0}</p>{issues.length>0&&<details><summary>Warnungen und technische Issues ({issues.length})</summary><ul>{issues.slice(0,50).map((issue,index)=><li key={`${issue.code}-${index}`}>{issue.code}</li>)}</ul></details>}<details><summary>Technische Details</summary><p>Quelle {pipeline.sourceVersion} · Hash {pipeline.pipelineDiagnostics.deterministicResultHash} · Compact</p></details><p className="heuristic-note">Die Passive-Planung ist heuristisch. Sie liefert einen nachvollziehbaren, aber nicht garantiert global optimalen Plan.</p></div>}
 </section>
}
