import { describe,expect,it } from 'vitest'
import { REAL_PASSIVE_FIXTURE_TREE,realPassivePipelineInput } from '../real-passive-pipeline/fixtures'
import { evaluatePassiveTargets } from './evaluator'
import { preparePassiveTargetingContext,validatePreparedPassiveTargetingContext } from './prepared-context'

describe('vorbereiteter Passive-Targeting-Kontext',()=>{
 it('enthält ausschließlich Baumidentität und Klassifikationsgrundlagen',()=>{const context=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes,'fixture');expect(Object.keys(context).sort()).toEqual(['classifications','formatVersion','nodeCount','signatureNodeIds','sourceVersion','treeIdentity']);expect(Object.isFrozen(context)).toBe(true);expect(context.nodeCount).toBe(9)})
 it('akzeptiert nur identische Version und Baumidentität',()=>{const context=preparePassiveTargetingContext(REAL_PASSIVE_FIXTURE_TREE.nodes,'fixture');expect(validatePreparedPassiveTargetingContext(context,REAL_PASSIVE_FIXTURE_TREE.nodes,'fixture')).toEqual([]);expect(validatePreparedPassiveTargetingContext(context,REAL_PASSIVE_FIXTURE_TREE.nodes,'other')).toContain('prepared-targeting-context-source-version-mismatch');expect(validatePreparedPassiveTargetingContext(context,REAL_PASSIVE_FIXTURE_TREE.nodes.slice(1),'fixture')).toContain('prepared-targeting-context-tree-mismatch')})
 it('liefert bei Context-Treffer und Context-Miss denselben fachlichen Output',()=>{const value=realPassivePipelineInput(),base={buildProfile:value.buildProfile,characterClassId:value.characterClassId,characterLevel:value.characterLevel,targetProfile:value.targetProfile,passiveNodes:value.passiveTree.nodes,minimumConfidence:value.minimumConfidence,analyzerContext:value.analyzerContext,sourceVersion:value.sourceVersion} as const,prepared=preparePassiveTargetingContext(value.passiveTree.nodes,value.sourceVersion);expect(evaluatePassiveTargets({...base,preparedContext:prepared})).toEqual(evaluatePassiveTargets(base))})
 it('vermischt aufeinanderfolgende Profile nicht',()=>{const value=realPassivePipelineInput(),prepared=preparePassiveTargetingContext(value.passiveTree.nodes,value.sourceVersion),base={characterClassId:value.characterClassId,characterLevel:value.characterLevel,targetProfile:'balanced' as const,passiveNodes:value.passiveTree.nodes,preparedContext:prepared,analyzerContext:value.analyzerContext,sourceVersion:value.sourceVersion},a=evaluatePassiveTargets({...base,buildProfile:value.buildProfile}),b=evaluatePassiveTargets({...base,buildProfile:{...value.buildProfile,damageTypes:{...value.buildProfile.damageTypes,lightning:0,cold:100}}});expect(a).not.toBe(b);expect(prepared.classifications).toHaveLength(9);expect(a.allCandidates).not.toBe(b.allCandidates)})
})
