import type { PassiveTargetRule, PassiveTargetTag } from './types'
const TYPES=['normal','notable','keystone','ascendancy','unknown'] as const
const rule=(id:string,patterns:string[],tags:PassiveTargetTag[],fields:string[],category:PassiveTargetRule['scoreCategory']='utility',mode:PassiveTargetRule['matchMode']='phrase',weight=20,excludedPatterns?:string[]):PassiveTargetRule=>({ruleId:`target-${id}`,descriptionKey:`engine.passiveTarget.rule.${id}`,applicableNodeTypes:[...TYPES],matchMode:mode,patterns,excludedPatterns,classificationTags:tags,affectedProfileFields:fields,scoreCategory:category,weight,confidenceWeight:1,priority:100,reasonCode:`passive-target-${id}`,enabled:true})
export const PASSIVE_TARGET_RULES:PassiveTargetRule[]=[
rule('generic-damage',['increased damage','more damage','reduced damage','less damage'],['generic-damage'],['goals.damageWeight'],'damage','phrase',20,['damage taken']),
rule('physical',['physical'],['physical'],['damageTypes.physical'],'damage','token'),rule('fire',['fire'],['fire'],['damageTypes.fire'],'damage','token'),rule('cold',['cold'],['cold'],['damageTypes.cold'],'damage','token'),rule('lightning',['lightning'],['lightning'],['damageTypes.lightning'],'damage','token'),rule('chaos',['chaos'],['chaos'],['damageTypes.chaos'],'damage','token'),rule('elemental',['elemental'],['elemental'],['damageTypes.fire','damageTypes.cold','damageTypes.lightning'],'damage','token'),
rule('attack',['attack','attacks'],['attack'],['mechanics.attack'],'damage','token'),rule('spell',['spell','spells'],['spell'],['mechanics.spell'],'damage','token'),rule('projectile',['projectile','projectiles'],['projectile'],['mechanics.projectile'],'damage','token'),rule('melee',['melee'],['melee'],['mechanics.melee'],'damage','token'),rule('area',['area damage'],['area'],['mechanics.area'],'damage'),rule('critical',['critical'],['critical'],['mechanics.critical'],'damage','token'),rule('dot',['damage over time','damage-over-time'],['damage-over-time'],['mechanics.damage-over-time'],'damage'),rule('minion',['minion','minions','companion','companions'],['minion'],['mechanics.minion'],'damage','token'),rule('ailment',['ailment','ailments','ignite','ignites','shock','freeze','chill','poison','bleeding'],['ailment'],['mechanics.damage-over-time'],'utility','token'),rule('movement',['movement'],['movement'],['mechanics.movement'],'speed','token'),rule('channeling',['channeling','channelling'],['channeling'],[],'utility','token'),rule('totem',['totem','totems'],['totem'],[],'utility','token'),rule('trap',['trap','traps'],['trap'],[],'utility','token'),rule('mark',['mark','marked'],['mark'],['mechanics.debuff'],'boss','token'),rule('curse',['curse','curses','flammability','conductivity','vulnerability'],['curse'],['mechanics.debuff'],'boss','token'),
rule('stun-buildup',['stun buildup'],['stun-buildup'],[],'utility','phrase',8),rule('daze',['daze','dazed'],['daze'],[],'utility','token',8),rule('pin',['pin','pinned'],['pin'],[],'utility','token',8),rule('slow',['slow','slowing'],['slow'],[],'utility','token',8),rule('warcry',['warcry','warcries'],['warcry'],[],'utility','token',8),rule('grenade',['grenade','grenades'],['grenade'],[],'utility','token',8),
rule('meta-skill',['meta skills'],['meta-skill'],[],'utility','phrase',8),rule('glory',['glory'],['glory'],[],'utility','token',8),rule('hazard',['hazard','hazards'],['hazard'],[],'utility','token',8),rule('rage',['rage'],['rage'],[],'utility','token',8),rule('debuff',['debuff','debuffs'],['debuff'],[],'utility','token',8),rule('remnant',['remnant','remnants'],['remnant'],[],'utility','token',8),rule('charm',['charm','charms'],['charm'],[],'utility','token',8),rule('crossbow',['crossbow','crossbows'],['crossbow'],[],'utility','token',8),rule('electrocute',['electrocute','electrocuted'],['electrocute'],[],'utility','token',8),rule('flask',['flask','flasks'],['flask'],[],'utility','token',8),
rule('buff',['buff','buffs'],['buff'],[],'utility','token',8),rule('puppet-master',['puppet master'],['puppet-master'],[],'utility','phrase',8),rule('command',['command'],['command'],[],'utility','token',8),rule('ballista',['ballista'],['ballista'],[],'utility','token',8),rule('arcane-surge',['arcane surge'],['arcane-surge'],[],'utility','phrase',8),rule('thorns',['thorns'],['thorns'],[],'utility','token',8),rule('knockback',['knockback'],['knockback'],[],'utility','token',8),rule('volatility',['volatility'],['volatility'],[],'utility','token',8),rule('blind',['blind','blinded'],['blind'],[],'utility','token',8),rule('exposure',['exposure'],['exposure'],[],'utility','token',8),rule('archon',['archon'],['archon'],[],'utility','token',8),
rule('pierce',['pierce'],['pierce'],[],'utility','token',8),rule('immobilisation',['immobilisation','immobilised','immobilise'],['immobilisation'],[],'utility','token',8),rule('combo',['combo'],['combo'],[],'utility','token',8),rule('endurance-charge',['endurance charge','endurance charges'],['endurance-charge'],[],'utility','phrase',8),rule('frenzy-charge',['frenzy charge','frenzy charges'],['frenzy-charge'],[],'utility','phrase',8),rule('power-charge',['power charge','power charges'],['power-charge'],[],'utility','phrase',8),rule('reservation',['reservation','reserved','reserves','unreserved'],['reservation'],[],'resource','token',8),rule('herald',['herald'],['herald'],[],'utility','token',8),rule('quiver',['quiver'],['quiver'],[],'utility','token',8),rule('passive-point',['passive skill point','passive skill points'],['passive-point'],[],'utility','phrase',8),
rule('quality',['quality'],['quality'],[],'utility','token',8),rule('jagged-ground',['jagged ground'],['jagged-ground'],[],'utility','phrase',8),rule('parry',['parry','parried','parrying'],['parry'],[],'utility','token',8),rule('culling-strike',['culling strike'],['culling-strike'],[],'utility','phrase',8),rule('seal',['seal','sealed'],['seal'],[],'utility','token',8),rule('withered',['withered'],['withered'],[],'utility','token',8),rule('darkness',['darkness'],['darkness'],[],'resource','token',8),
rule('life',['maximum life','life regeneration','life recovery','recouped as life','life leeched'],['life'],['defence.lifeAffinity','defence.generalDefenceNeed'],'defence'),rule('armour',['armour'],['armour'],['defence.armourAffinity','defence.generalDefenceNeed'],'defence','token'),rule('evasion',['evasion'],['evasion'],['defence.evasionAffinity','defence.generalDefenceNeed'],'defence','token'),rule('energy-shield',['energy shield'],['energy-shield'],['defence.energyShieldAffinity','defence.generalDefenceNeed'],'defence'),rule('block',['block'],['block'],['defence.generalDefenceNeed'],'defence','token'),rule('max-resistance',['maximum resistance','maximum fire resistance','maximum cold resistance','maximum lightning resistance','maximum chaos resistance'],['maximum-resistance','resistance'],['defence.resistanceNeed'],'defence'),rule('resistance',['resistance','resistances'],['resistance'],['defence.resistanceNeed'],'defence','token'),rule('recovery',['recovery','recoup'],['recovery'],['defence.generalDefenceNeed'],'defence','token'),rule('regeneration',['regeneration','regenerate'],['regeneration'],['defence.generalDefenceNeed','requirements.resourceNeed'],'defence','token'),rule('leech',['leech','leeched'],['leech'],['defence.generalDefenceNeed','requirements.resourceNeed'],'defence','token'),rule('stun-defence',['stun threshold','stun recovery'],['stun-defence'],['defence.generalDefenceNeed'],'defence'),rule('ailment-defence',['ailment threshold','ailments on you','chance to avoid'],['ailment-defence'],['defence.generalDefenceNeed'],'defence'),
rule('mana',['mana'],['mana'],['requirements.resourceNeed'],'resource','token'),rule('spirit',['spirit'],['spirit'],['requirements.resourceNeed'],'resource','token'),rule('resource-cost',['mana cost','life cost','skill cost','cost efficiency'],['resource-cost'],['requirements.resourceNeed'],'resource'),rule('strength',['strength'],['strength'],['requirements.strengthNeed'],'attribute','token'),rule('dexterity',['dexterity'],['dexterity'],['requirements.dexterityNeed'],'attribute','token'),rule('intelligence',['intelligence'],['intelligence'],['requirements.intelligenceNeed'],'attribute','token'),rule('attributes',['attribute','attributes'],['attributes'],['requirements.strengthNeed','requirements.dexterityNeed','requirements.intelligenceNeed'],'attribute','token'),
rule('attack-speed',['attack speed'],['attack-speed'],['speed.attackSpeedAffinity'],'speed'),rule('cast-speed',['cast speed'],['cast-speed'],['speed.castSpeedAffinity'],'speed'),rule('movement-speed',['movement speed'],['movement-speed'],['speed.movementAffinity'],'speed'),rule('cooldown',['cooldown'],['cooldown'],[],'utility','token'),rule('duration',['duration'],['duration'],['mechanics.damage-over-time'],'utility','token'),rule('skill-effect',['skill effect'],['skill-effect'],[],'utility'),rule('accuracy',['accuracy'],['accuracy'],['mechanics.attack'],'utility','token'),rule('range',['range'],['range'],[],'utility','token'),rule('area-of-effect',['area of effect'],['area-of-effect'],['mechanics.area'],'mapping'),
rule('skill-speed',['skill speed'],['attack-speed','cast-speed'],['speed.attackSpeedAffinity','speed.castSpeedAffinity'],'speed'),
rule('aura-magnitude',['aura skills have','aura effect'],['skill-effect'],['mechanics.buff'],'utility'),
]
