import type { AnalyzerContext, BuildProfile, Confidence, ConstraintViolation, ScoreReason } from '../common/types'

export type PassiveTargetNodeType = 'normal' | 'notable' | 'keystone' | 'class-start' | 'ascendancy-start' | 'ascendancy' | 'jewel-socket' | 'unknown'
export type PassiveTargetTag = 'generic-damage'|'physical'|'fire'|'cold'|'lightning'|'chaos'|'attack'|'spell'|'projectile'|'melee'|'area'|'critical'|'damage-over-time'|'minion'|'ailment'|'elemental'|'movement'|'channeling'|'totem'|'trap'|'mark'|'curse'|'stun-buildup'|'daze'|'pin'|'slow'|'warcry'|'grenade'|'meta-skill'|'glory'|'hazard'|'rage'|'debuff'|'remnant'|'charm'|'crossbow'|'electrocute'|'flask'|'buff'|'puppet-master'|'command'|'ballista'|'arcane-surge'|'thorns'|'knockback'|'volatility'|'blind'|'exposure'|'archon'|'pierce'|'immobilisation'|'combo'|'endurance-charge'|'frenzy-charge'|'power-charge'|'reservation'|'herald'|'quiver'|'passive-point'|'quality'|'jagged-ground'|'parry'|'culling-strike'|'seal'|'withered'|'darkness'|'corpse'|'bolt'|'banner'|'life-on-kill'|'poison-limit'|'deflection'|'decimating-strike'|'maim'|'invocation'|'offering'|'orb'|'plant'|'lucky-hit'|'random-element-gain'|'light-radius'|'spirit-possession'|'reveal-weakness'|'sinister-jewel-socket'|'strike'|'splash-damage'|'dodge-roll'|'ring-slot'|'aftershock'|'socketed-jewel-effect'|'slam'|'shapeshift'|'surrounded'|'full-life-recovery'|'unlucky-enemy-hits'|'ice-crystal'|'trigger-energy-refund'|'shocked-ground'|'equipped-jewellery-effect'|'infernal-flame'|'delayed-damage'|'low-life'|'onslaught'|'incision'|'small-passive-effect'|'focus-effect'|'flames-of-chayula'|'debilitate'|'concentration-break'|'life'|'armour'|'evasion'|'energy-shield'|'block'|'resistance'|'maximum-resistance'|'recovery'|'regeneration'|'leech'|'stun-defence'|'ailment-defence'|'mana'|'spirit'|'resource-cost'|'strength'|'dexterity'|'intelligence'|'attributes'|'attack-speed'|'cast-speed'|'movement-speed'|'cooldown'|'duration'|'skill-effect'|'accuracy'|'range'|'area-of-effect'
export type PassiveTargetScoreCategory = 'damage'|'defence'|'mapping'|'boss'|'speed'|'utility'|'resource'|'attribute'|'class-synergy'|'ascendancy-synergy'|'profile-synergy'|'data-quality'
export type PassiveTargetMatchMode = 'exact'|'token'|'phrase'|'regular-expression'
export type PassiveTargetEligibility = 'eligible'|'blocked'|'socket-target'
export type PassiveEffectDirection = 'positive'|'negative'|'mixed'|'unknown'

export interface PassiveTargetSourceText { sourceText: string|null; sourceLocale?: string }
export interface PassiveTargetNode { id: string; name: PassiveTargetSourceText; stats: PassiveTargetSourceText[]; nodeType: string; isClassStart: boolean; classStartIndex: number|number[]|null; isAscendancyStart: boolean; ascendancyId: string|null; isJewelSocket: boolean; enabled?: boolean }
export interface PassiveTargetRule { ruleId:string; descriptionKey:string; applicableNodeTypes:PassiveTargetNodeType[]; matchMode:PassiveTargetMatchMode; patterns:string[]; excludedPatterns?:string[]; classificationTags:PassiveTargetTag[]; affectedProfileFields:string[]; scoreCategory:PassiveTargetScoreCategory; weight:number; confidenceWeight:number; priority:number; reasonCode:string; enabled:boolean }
export interface PassiveStatClassification { sourceText:string; normalizedText:string; matchedRuleIds:string[]; tags:PassiveTargetTag[]; numericValues?:number[]; affectedProfileFields:string[]; effectDirection:PassiveEffectDirection; positiveEffects:string[]; negativeEffects:string[]; restrictions:string[]; confidence:Confidence; unresolved:boolean }
export interface PassiveNodeClassification { nodeId:string; nodeType:PassiveTargetNodeType; name:PassiveStatClassification; stats:PassiveStatClassification[]; tags:PassiveTargetTag[]; matchedRuleIds:string[]; unresolvedStatCount:number; recognizedStatCount:number; fullyUnresolved:boolean }
export interface PreparedPassiveTargetingContext { formatVersion:'1';sourceVersion:string;treeIdentity:string;nodeCount:number;classifications:readonly PassiveNodeClassification[];signatureNodeIds:ReadonlyMap<string,readonly string[]> }
export interface PassiveTargetingInput { buildProfile:BuildProfile; characterClassId:string; ascendancyId?:string; characterLevel:number; targetProfile:'mapping'|'boss'|'balanced'; passiveNodes:PassiveTargetNode[]; preparedContext?:PreparedPassiveTargetingContext; excludedNodeIds?:string[]; requiredNodeTypes?:PassiveTargetNodeType[]; maximumResults?:number; minimumConfidence?:Confidence; analyzerContext:AnalyzerContext; sourceVersion:string; profileClarity?:number }
export interface PassiveTargetRecommendation { recommendationId:string; nodeId:string; nodeType:PassiveTargetNodeType; displayName:string; sourceStats:string[]; sourceLocale:string; totalScore:number; eligibility:PassiveTargetEligibility; damageScore:number; defenceScore:number; mappingScore:number; bossScore:number; speedScore:number; utilityScore:number; resourceScore:number; attributeScore:number; classSynergyScore:number; ascendancySynergyScore:number; profileSynergyScore:number; dataQualityScore:number; matchedTags:PassiveTargetTag[]; weaklyMatchedTags:PassiveTargetTag[]; conflictingTags:PassiveTargetTag[]; matchedProfileFields:string[]; conflictingProfileFields:string[]; gainedMechanics:string[]; lostMechanics:string[]; restrictions:string[]; tradeOffs:string[]; requiresReoptimization:boolean; unresolvedStatCount:number; redundantWithNodeIds:string[]; conflictingNodeIds:string[]; weaklyUsefulReasonCodes:string[]; reasons:ScoreReason[]; violations:ConstraintViolation[]; warnings:ConstraintViolation[]; confidence:Confidence; status:'experimental'; analyzerVersion:string; sourceVersion:string }
export interface PassiveTargetCoverageReport { totalNodeCount:number; evaluatedNodeCount:number; blockedNodeCount:number; classifiedNodeCount:number; unclassifiedNodeCount:number; totalStatLineCount:number; classifiedStatLineCount:number; unresolvedStatLineCount:number; classificationCoveragePercent:number; nodeTypeCounts:Record<string,number>; categoryCounts:Record<string,number>; unresolvedPatterns:string[]; mostFrequentUnresolvedTexts:Array<{text:string;count:number}>; sourceVersion:string; classifierVersion:string; status:'measured' }
export interface PassiveTargetAnalysis { allCandidates:PassiveTargetRecommendation[]; eligibleCandidates:PassiveTargetRecommendation[]; blockedCandidates:PassiveTargetRecommendation[]; topDamageTargets:PassiveTargetRecommendation[]; topDefensiveTargets:PassiveTargetRecommendation[]; topMappingTargets:PassiveTargetRecommendation[]; topBossTargets:PassiveTargetRecommendation[]; topSpeedTargets:PassiveTargetRecommendation[]; topResourceTargets:PassiveTargetRecommendation[]; topAttributeTargets:PassiveTargetRecommendation[]; topClassSynergyTargets:PassiveTargetRecommendation[]; topAscendancyTargets:PassiveTargetRecommendation[]; topNotables:PassiveTargetRecommendation[]; topKeystones:PassiveTargetRecommendation[]; jewelSocketTargets:PassiveTargetRecommendation[]; lowDataQualityCandidates:PassiveTargetRecommendation[]; unresolvedStatCandidates:PassiveTargetRecommendation[]; coverage:PassiveTargetCoverageReport; status:'experimental'; analyzerVersion:string; sourceVersion:string }
