import type { ExplanationSection, ExplanationTone } from '../common/types'

export interface ExplanationTemplate {
  templateId: string
  section: ExplanationSection
  supportedReasonCodes: string[]
  requiredPlaceholders: string[]
  priority: number
  severity: ExplanationTone
  textTemplateDe: string
  shortTemplateDe?: string
  titleTemplateDe: string
  enabled: boolean
}

export const EXPLANATION_TEMPLATES: ExplanationTemplate[] = [
  { templateId: 'summary-build', section: 'summary', supportedReasonCodes: ['summary:build'], requiredPlaceholders: ['skillName', 'reason'], priority: 120, severity: 'neutral', titleTemplateDe: 'Zusammenfassung der strukturierten Auswertung', textTemplateDe: 'Die zentrale Empfehlung ist {skillName}. Grundlage der Zusammenfassung ist der vorhandene Grund „{reason}“.', enabled: true },
  { templateId: 'limitation-synthetic', section: 'limitations', supportedReasonCodes: ['engine-synthetic-limitations'], requiredPlaceholders: [], priority: 100, severity: 'warning', titleTemplateDe: 'Grenzen dieser Auswertung', textTemplateDe: 'Diese Erklärung verwendet ausschließlich synthetische Regeln und Platzhalterdaten. Sie enthält keine echten PoE2-Daten, keine DPS-Berechnung und ist keine fachlich verifizierte Buildempfehlung.', shortTemplateDe: 'Synthetische Platzhalterauswertung ohne echte Spieldaten oder DPS.', enabled: true },
  { templateId: 'constraint-blocking', section: 'warnings', supportedReasonCodes: ['violation:*'], requiredPlaceholders: ['reason', 'entityName'], priority: 1000, severity: 'blocking', titleTemplateDe: 'Blockierung bei {entityName}', textTemplateDe: '{entityName} kann wegen „{reason}“ nicht verwendet werden. Diese blockierende Einschränkung stammt direkt aus der Engine-Prüfung.', enabled: true },
  { templateId: 'constraint-warning', section: 'warnings', supportedReasonCodes: ['warning:*'], requiredPlaceholders: ['reason', 'entityName'], priority: 900, severity: 'warning', titleTemplateDe: 'Warnung zu {entityName}', textTemplateDe: 'Für {entityName} meldet die Engine „{reason}“. Die Empfehlung bleibt nur im Rahmen dieser Einschränkung gültig.', enabled: true },
  { templateId: 'affix-improvement', section: 'affix-improvements', supportedReasonCodes: ['equipment:unused-modifier', 'equipment:weakly-used-modifier'], requiredPlaceholders: ['entityName', 'reason'], priority: 200, severity: 'warning', titleTemplateDe: 'Affix-Prüfung: {entityName}', textTemplateDe: '{entityName} ist durch „{reason}“ als ungenutzt oder schwach genutzt markiert und sollte deshalb geprüft werden.', enabled: true },
  { templateId: 'equipment-conflict', section: 'conflicts', supportedReasonCodes: ['equipment:conflicting-modifier', 'equipment:conflict-level'], requiredPlaceholders: ['entityName', 'reason'], priority: 900, severity: 'warning', titleTemplateDe: 'Ausrüstungskonflikt', textTemplateDe: 'Bei {entityName} liegt der strukturierte Konflikt „{reason}“ vor.', enabled: true },
  { templateId: 'equipment-reason', section: 'equipment', supportedReasonCodes: ['equipment:*'], requiredPlaceholders: ['reason', 'mechanic', 'scoreImpact'], priority: 600, severity: 'positive', titleTemplateDe: 'Ausrüstungsprofil', textTemplateDe: 'Die Ausrüstung liefert den strukturierten Grund „{reason}“ für {mechanic}. Der synthetische Einfluss beträgt {scoreImpact}.', enabled: true },
  { templateId: 'skill-reason', section: 'main-skill', supportedReasonCodes: ['skill:*', 'damage-*', 'mapping-fit', 'boss-fit', 'recommended-role', 'unused-dominant-profile', 'conflicting-profile'], requiredPlaceholders: ['skillName', 'reason', 'weaponSet'], priority: 800, severity: 'positive', titleTemplateDe: 'Fertigkeit: {skillName}', textTemplateDe: '{skillName} wird durch „{reason}“ gestützt. Die strukturierte Waffen-Set-Angabe lautet {weaponSet}.', enabled: true },
  { templateId: 'additional-skill', section: 'additional-skills', supportedReasonCodes: ['additional-skill'], requiredPlaceholders: ['skillName', 'reason', 'weaponSet'], priority: 790, severity: 'neutral', titleTemplateDe: 'Zusätzliche Fertigkeit: {skillName}', textTemplateDe: '{skillName} ist als zusätzliche Fertigkeit strukturiert. Grundlage ist „{reason}“, die Set-Zuordnung lautet {weaponSet}.', enabled: true },
  { templateId: 'support-reason', section: 'supports', supportedReasonCodes: ['support:*', 'tradeoff-*'], requiredPlaceholders: ['supportName', 'reason', 'mechanic'], priority: 500, severity: 'positive', titleTemplateDe: 'Unterstützung: {supportName}', textTemplateDe: '{supportName} nutzt {mechanic}. Grundlage ist der vorhandene Grund „{reason}“.', enabled: true },
  { templateId: 'passive-reason', section: 'passives', supportedReasonCodes: ['passive:*', 'path-efficiency', 'node-type', 'useful-path-node', 'keystone-trade-off', 'defence-need', 'requirement-need', 'ascendancy-synergy'], requiredPlaceholders: ['entityName', 'reason', 'pathCost'], priority: 400, severity: 'positive', titleTemplateDe: 'Passiver Kandidat: {entityName}', textTemplateDe: '{entityName} wird durch „{reason}“ erklärt. Die strukturierten Gesamtkosten des Pfads betragen {pathCost}.', enabled: true },
  { templateId: 'jewel-reason', section: 'jewels', supportedReasonCodes: ['jewel:*', 'build-enabler'], requiredPlaceholders: ['entityName', 'reason', 'pathCost'], priority: 300, severity: 'positive', titleTemplateDe: 'Juwel: {entityName}', textTemplateDe: '{entityName} passt wegen „{reason}“. Sockel- und Pfadkosten werden mit dem strukturierten Wert {pathCost} berücksichtigt.', enabled: true },
  { templateId: 'unique-reason', section: 'uniques', supportedReasonCodes: ['unique:*', 'weapon-set-fit'], requiredPlaceholders: ['uniqueName', 'reason', 'itemSlot'], priority: 300, severity: 'positive', titleTemplateDe: 'Unique: {uniqueName}', textTemplateDe: '{uniqueName} wird für den Slot {itemSlot} durch „{reason}“ eingeordnet.', enabled: true },
  { templateId: 'unique-verdict', section: 'uniques', supportedReasonCodes: ['unique-replacement-verdict', 'unique-reoptimization', 'unique-gained-mechanics', 'unique-lost-mechanics'], requiredPlaceholders: ['uniqueName', 'reason'], priority: 310, severity: 'warning', titleTemplateDe: 'Auswirkung von {uniqueName}', textTemplateDe: 'Für {uniqueName} lautet die strukturierte Einordnung „{reason}“. Ein Build-Enabler ist dadurch nicht automatisch die beste Empfehlung.', enabled: true },
  { templateId: 'rotation-step-mapping', section: 'mapping-rotation', supportedReasonCodes: ['rotation:mapping:*'], requiredPlaceholders: ['order', 'action', 'skillName', 'weaponSet', 'reason', 'condition'], priority: 700, severity: 'neutral', titleTemplateDe: 'Mapping-Schritt {order}', textTemplateDe: 'Schritt {order}: {action} mit {skillName} auf {weaponSet}. Grund: „{reason}“. Bedingung: {condition}.', enabled: true },
  { templateId: 'rotation-step-boss', section: 'boss-rotation', supportedReasonCodes: ['rotation:boss:*'], requiredPlaceholders: ['order', 'action', 'skillName', 'weaponSet', 'reason', 'condition'], priority: 700, severity: 'neutral', titleTemplateDe: 'Boss-Schritt {order}', textTemplateDe: 'Schritt {order}: {action} mit {skillName} auf {weaponSet}. Grund: „{reason}“. Bedingung: {condition}.', enabled: true },
  { templateId: 'weapon-swap', section: 'weapon-swap', supportedReasonCodes: ['rotation:weapon-swap'], requiredPlaceholders: ['previousWeaponSet', 'nextWeaponSet', 'previousSkill', 'nextSkill', 'reason', 'effectStatus'], priority: 700, severity: 'neutral', titleTemplateDe: 'Waffenwechsel: {previousWeaponSet} zu {nextWeaponSet}', textTemplateDe: 'Nach {previousSkill} wird von {previousWeaponSet} zu {nextWeaponSet} gewechselt, bevor {nextSkill} folgt. Grund: „{reason}“. {effectStatus}', enabled: true },
  { templateId: 'confidence', section: 'confidence', supportedReasonCodes: ['confidence:*'], requiredPlaceholders: ['confidence', 'confidenceText', 'entityName'], priority: 110, severity: 'neutral', titleTemplateDe: 'Confidence: {confidence}', textTemplateDe: '{entityName}: {confidenceText}', enabled: true },
]
