import { describe, expect, it } from 'vitest'
import { analyzeBuild } from '../orchestration/analyze-build'
import { fixtureA, fixtureB, engineModifierFixtures, syntheticPassiveFixtures } from '../fixtures'
import { passiveAnalyzer } from './analyzer'
import type { AnalyzerContext, PassiveCandidate } from '../common/types'
const context = (): AnalyzerContext => ({ engineVersion: 'test', fixtureMode: true })
const buildA = () => analyzeBuild(fixtureA, context(), engineModifierFixtures)
const buildB = () => analyzeBuild(fixtureB, context(), engineModifierFixtures)
const analysis = (candidates: PassiveCandidate[] = syntheticPassiveFixtures, useCold = false) => { const build = useCold ? buildB() : buildA(); return passiveAnalyzer.analyzeRanked(build.buildProfile, candidates, context(), { equipmentAnalysis: build.equipmentAnalysis, skillRecommendation: build.skillAnalysis.eligibleCandidates[0], supportRecommendations: build.supportAnalysis.topCandidates, character: (useCold ? fixtureB : fixtureA).input.character, goalProfile: (useCold ? fixtureB : fixtureA).input.goalProfile }) }
const get = (id: string, useCold = false) => analysis(undefined, useCold).allCandidates.find(item => item.recommendationId === id)!
const mutate = (id: string, update: (value: PassiveCandidate) => PassiveCandidate) => syntheticPassiveFixtures.map(item => item.id === id ? update(structuredClone(item)) : structuredClone(item))
describe('regelbasierter synthetischer Passive Analyzer', () => {
  it('passende Schadensart erhöht Score', () => expect(get('fixture-passive-lightning-projectile').damageScore).toBeGreaterThan(0))
  it('passende Mechanik erhöht Score', () => expect(get('fixture-passive-lightning-projectile').equipmentSynergyScore).toBeGreaterThan(0))
  it('unpassende Mechanik gibt keinen Bonus', () => expect(get('fixture-passive-cold-spell').damageScore).toBe(0))
  it('Cold Spell profitiert im passenden Profil', () => expect(get('fixture-passive-cold-spell', true).damageScore).toBeGreaterThan(0))
  it('defensive Knoten profitieren von DefenceNeed', () => expect(get('fixture-passive-defensive-life').defenceScore).toBeGreaterThan(0))
  it('Widerstandsknoten profitieren von resistanceNeed', () => { const values = mutate('fixture-passive-defensive-life', item => { item.nodes![2].tags = ['resistance']; return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-defensive-life')!.defenceScore).toBeGreaterThan(0) })
  it('Attributknoten besitzen Resource-Score', () => expect(get('fixture-passive-attribute-path').resourceScore).toBeGreaterThanOrEqual(0))
  it('Notable wird anders als normaler Knoten bewertet', () => expect(get('fixture-passive-energy-shield').utilityCategoryScore).toBeGreaterThan(4))
  it('Keystone-Trade-off erzeugt negativen Reason', () => expect(get('fixture-passive-keystone').reasons.some(item => item.impact < 0)).toBe(true))
  it('Keystone bleibt technisch gültig', () => expect(get('fixture-passive-keystone').valid).toBe(true))
  it('falsche Aszendenz blockiert', () => expect(get('fixture-passive-wrong-ascendancy').violations.some(item => item.code === 'wrong-ascendancy-node')).toBe(true))
  it('falsche Klasse blockiert', () => { const values = mutate('fixture-passive-set-1', item => { item.nodes![0].requiredClassId = 'other'; return item }); expect(analysis(values).blockedCandidates.some(item => item.recommendationId === 'fixture-passive-set-1')).toBe(true) })
  it('deaktivierter Knoten blockiert', () => { const values = mutate('fixture-passive-set-1', item => { item.nodes![0].enabled = false; return item }); expect(analysis(values).blockedCandidates.some(item => item.recommendationId === 'fixture-passive-set-1')).toBe(true) })
  it('fehlende Knotenreferenz blockiert', () => { const values = mutate('fixture-passive-efficient', item => { item.cluster!.targetNodeIds = ['missing']; return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-efficient')!.violations.some(item => item.code === 'invalid-node-reference')).toBe(true) })
  it('fehlende Verbindung blockiert', () => { const values = mutate('fixture-passive-efficient', item => { item.connections = []; return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-efficient')!.violations.some(item => item.code === 'missing-connection')).toBe(true) })
  it('nicht zusammenhängender Pfad blockiert', () => { const values = mutate('fixture-passive-efficient', item => { item.connections = item.connections!.slice(0, 1); return item }); expect(analysis(values).blockedCandidates.some(item => item.recommendationId === 'fixture-passive-efficient')).toBe(true) })
  it('Selbstverbindung wird erkannt', () => { const values = mutate('fixture-passive-efficient', item => { item.connections!.push({ id: 'self', fromNodeId: item.nodes![0].id, toNodeId: item.nodes![0].id, selected: false }); return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-efficient')!.violations.some(item => item.code === 'self-connection')).toBe(true) })
  it('doppelte Pfadknoten werden erkannt', () => { const values = mutate('fixture-passive-efficient', item => { item.cluster!.requiredPathNodeIds.push(item.cluster!.requiredPathNodeIds[0]); return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-efficient')!.violations.some(item => item.code === 'duplicate-path-node')).toBe(true) })
  it('totalPointCost wird korrekt berechnet', () => expect(get('fixture-passive-efficient').totalPointCost).toBeGreaterThanOrEqual(2))
  it('pathPointCost wird berücksichtigt', () => expect(get('fixture-passive-expensive').pathPointCost).toBeGreaterThan(get('fixture-passive-efficient').pathPointCost))
  it('scorePerPoint sinkt bei höheren Kosten', () => expect(get('fixture-passive-expensive').scorePerPoint).toBeLessThan(get('fixture-passive-efficient').scorePerPoint))
  it('effizienter Cluster rankt vor ineffizientem', () => expect(get('fixture-passive-efficient').pathEfficiencyScore).toBeGreaterThan(get('fixture-passive-expensive').pathEfficiencyScore))
  it('nützliche Durchgangsknoten tragen Nutzen bei', () => { const values = mutate('fixture-passive-efficient', item => { item.nodes![1].tags = ['lightning']; return item }); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-efficient')!.reasons.some(item => item.code === 'useful-path-node')).toBe(true) })
  it('wertlose Durchgangsknoten bleiben Kosten', () => expect(get('fixture-passive-efficient').weaklyUsefulNodeIds.length).toBeGreaterThan(0))
  it('Waffen-Sets werden getrennt bewertet', () => expect(get('fixture-passive-set-1').scoreSet1).not.toBe(get('fixture-passive-set-1').scoreSet2))
  it('Set-1-Knoten bevorzugt Set 1', () => expect(get('fixture-passive-set-1').preferredWeaponSet).toBe('set-1'))
  it('gleiche Scores verwenden stabilen ID-Tie-Breaker', () => { const original = structuredClone(syntheticPassiveFixtures.find(item => item.id === 'fixture-passive-set-1')!); const candidates = [original, { ...structuredClone(original), id: 'fixture-passive-a' }]; expect(analysis(candidates).allCandidates.map(item => item.recommendationId)).toEqual(['fixture-passive-a', 'fixture-passive-set-1']) })
  it('blockierte Kandidaten stehen hinter gültigen', () => { const result = analysis(); expect(result.allCandidates.findIndex(item => !item.valid)).toBeGreaterThan(result.allCandidates.findIndex(item => item.valid)) })
  it('Redundanz wird erkannt', () => expect(get('fixture-passive-redundant').warnings.some(item => item.code === 'redundant')).toBe(true))
  it('Konflikte werden erkannt', () => expect(get('fixture-passive-cold-spell').conflictingProfileFields).toContain('mechanics.attack'))
  it('geringe profileClarity senkt Confidence', () => { const build = buildA(); const low = { ...build.equipmentAnalysis, profileClarity: 1 }; expect(passiveAnalyzer.analyzeRanked(build.buildProfile, syntheticPassiveFixtures, context(), { equipmentAnalysis: low }).allCandidates[0].confidence).toBe('low') })
  it('gleicher Input erzeugt gleiche Ausgabe', () => expect(analysis()).toEqual(analysis()))
  it('alle geforderten Ranglisten werden erzeugt', () => { const result = analysis(); expect([result.topDamageCandidates, result.topDefensiveCandidates, result.topMappingCandidates, result.topBossCandidates, result.topPathEfficiencyCandidates, result.topAscendancyCandidates, result.topKeystoneCandidates, result.topClusterCandidates].every(Array.isArray)).toBe(true) })
  it('nicht erreichbarer Cluster blockiert', () => expect(get('fixture-passive-unreachable').valid).toBe(false))
  it('Punktbudget blockiert teure Kandidaten', () => { const values = mutate('fixture-passive-expensive', item => ({ ...item, availablePointBudget: 2 })); expect(analysis(values).allCandidates.find(item => item.recommendationId === 'fixture-passive-expensive')!.violations.some(item => item.code === 'point-budget-exceeded')).toBe(true) })
  it('Orchestrator liefert PassiveAnalysis', () => expect(buildA().passiveAnalysis.topClusterCandidates.length).toBeGreaterThan(0))
})
