import { useMemo, useState } from 'react'
import { affixesFor, baseItemsFor, itemClassesForSlot, technicalAffixById } from '../affixes/registry'
import type { TechnicalAffix } from '../affixes/model'
import type { EquipmentEntry } from '../domain'

export function AffixDialog({entry,slotName,onSave,onClose}:{entry:EquipmentEntry;slotName:string;onSave:(entry:EquipmentEntry)=>void;onClose:()=>void}){
 const classes=itemClassesForSlot(entry.slotId),[itemClassId,setItemClassId]=useState(entry.itemClassId??classes[0]?.itemClassId??''),[baseItemId,setBaseItemId]=useState(entry.itemDefinitionId??''),[itemLevel,setItemLevel]=useState<number|undefined>(entry.itemLevel),[side,setSide]=useState<'prefix'|'suffix'|'implicit'>('prefix'),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[values,setValues]=useState<number[]>([]),[added,setAdded]=useState(entry.modifierValues),baseItems=baseItemsFor(itemClassId)
 const visible=useMemo(()=>affixesFor(itemClassId,side,itemLevel).filter(a=>side!=='implicit'||!baseItemId||a.baseItemIds?.includes(baseItemId)).filter(a=>`${a.technicalText} ${a.sourceModId} ${a.statLines.map(s=>s.statId).join(' ')}`.toLowerCase().includes(search.toLowerCase())).slice(0,300),[itemClassId,side,itemLevel,baseItemId,search]),chosen=technicalAffixById.get(selected)??visible[0],conflicts=new Set(added.flatMap(value=>technicalAffixById.get(value.modifierId)?.conflictGroups??[])),blocked=chosen?.conflictGroups.some(group=>conflicts.has(group))??false
 function add(affix:TechnicalAffix){const statValues=affix.statLines.map((line,index)=>({statId:line.statId,value:values[index]??line.minimum}));setAdded([...added,{id:`applied-${entry.slotId}-${crypto.randomUUID()}`,modifierId:affix.affixId,value:statValues[0]?.value??0,sourceModId:affix.sourceModId,statValues,itemClassId,affixSide:affix.affixSide,tierId:affix.tierId,requiredItemLevel:affix.requiredItemLevel,isLocal:affix.isLocal,isHybrid:affix.isHybrid,sourceVersion:affix.sourceVersion,dataStatus:affix.dataStatus}])}
 return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true"><div className="row"><h2>{slotName}</h2><button className="icon" aria-label="Dialog schließen" onClick={onClose}>×</button></div><p className="warning">Deutsche Übersetzung noch nicht verfügbar</p>
 <label>Technische Itemklasse<select value={itemClassId} onChange={event=>{setItemClassId(event.target.value);setBaseItemId('');setSelected('')}}>{classes.map(value=><option key={value.itemClassId}>{value.technicalName}</option>)}</select></label>{baseItems.length>0&&<label>Technischer Basistyp<select value={baseItemId} onChange={event=>setBaseItemId(event.target.value)}><option value="">Bitte wählen</option>{baseItems.map(value=><option key={value.baseItemId} value={value.baseItemId}>{value.baseItemId} · Drop-Level {value.dropLevel??'?'}</option>)}</select></label>}<label>Item Level (optional)<input type="number" min="1" value={itemLevel??''} onChange={event=>setItemLevel(event.target.value?Number(event.target.value):undefined)}/></label><label>Affixseite<select value={side} onChange={event=>setSide(event.target.value as 'prefix'|'suffix'|'implicit')}><option value="prefix">Prefix</option><option value="suffix">Suffix</option>{itemClassId==='Charms'&&<option value="implicit">Basis-Implicit</option>}</select></label><label>Technische Suche<input autoFocus value={search} onChange={event=>setSearch(event.target.value)}/></label>
 <label>Affix<select className="affix-list" size={6} value={chosen?.affixId??''} onChange={event=>{setSelected(event.target.value);setValues([])}}>{visible.map(a=><option value={a.affixId} key={a.affixId}>{a.technicalText} · {a.tierId.split(':').at(-1)} · ilvl {a.requiredItemLevel??'?'}</option>)}</select></label>{chosen?.statLines.map((line,index)=><label key={`${line.statId}-${index}`}>{line.statId} ({line.minimum}–{line.maximum})<input type="number" min={line.minimum} max={line.maximum} step={line.step??(line.numericType==='integer'?1:'any')} value={values[index]??line.minimum} onChange={event=>setValues(current=>Object.assign([...current],{[index]:Number(event.target.value)}))}/></label>)}{blocked&&<p className="warning">Konfliktgruppe bereits belegt.</p>}<button disabled={!chosen||blocked} onClick={()=>chosen&&add(chosen)}>Affix hinzufügen</button>
 <h3>Gespeicherte Affixe</h3>{added.length===0?<p className="muted">Noch keine Affixe.</p>:<ul className="clean">{added.map(item=><li key={item.id}><span>{technicalAffixById.get(item.modifierId)?.technicalText??'Nicht auflösbares Legacy-Affix'}: <b>{item.statValues?.map(v=>v.value).join(' / ')??String(item.value)}</b><small> · {item.affixSide??'legacy'} · {item.tierId?.split(':').at(-1)??'legacy'} · Übersetzung fehlt</small></span><button className="danger" onClick={()=>setAdded(added.filter(value=>value.id!==item.id))}>Entfernen</button></li>)}</ul>}<div className="dialog-actions"><button className="secondary" onClick={onClose}>Abbrechen</button><button disabled={baseItems.length>0&&!baseItemId} onClick={()=>{onSave({...entry,itemClassId,itemDefinitionId:baseItemId||undefined,itemLevel,modifierValues:added});onClose()}}>Speichern</button></div></div></div>
}
