import { clusterJewelDefinitions, jewelDefinitions, passiveNodeDefinitions, skillDefinitions, supportDefinitions, uniqueClusterJewelDefinitions } from '../data'
import type { BuildResult } from '../domain'

function List({ title, items }: { title: string; items: string[] }) { return <article><h3>{title}</h3><ul>{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul></article> }
const names = <T extends { id: string; displayNameDe: string }>(ids: string[], definitions: T[]) => ids.map(id => definitions.find(item => item.id === id)?.displayNameDe ?? id)
export function BuildResultSection({ result }: { result: BuildResult }) {
  const set1 = result.weaponSetRecommendations.find(item => item.weaponSet === 'set-1')?.skillIds ?? []; const set2 = result.weaponSetRecommendations.find(item => item.weaponSet === 'set-2')?.skillIds ?? []
  return <section id="result" className="result"><div className="placeholder">{result.isPlaceholder ? 'TESTBERECHNUNG · FESTE PLATZHALTERDATEN' : 'BERECHNUNG'}</div><h2>7. Build-Ergebnis</h2><div className="result-grid">
    <List title="Empfohlene Hauptfertigkeit" items={names([result.mainSkillId], skillDefinitions)}/><List title="Weitere Fertigkeitsgems" items={names(result.additionalSkillIds, skillDefinitions)}/><List title="Unterstützungsgems" items={names(result.supportGemIds, supportDefinitions)}/><List title="Waffen-Set 1" items={names(set1, skillDefinitions)}/><List title="Waffen-Set 2" items={names(set2, skillDefinitions)}/><List title="Passiver Pfad" items={[names(result.passivePathNodeIds, passiveNodeDefinitions).join(' → ')]}/><List title="Normale Juwele" items={names(result.jewelRecommendationIds, jewelDefinitions)}/><List title="Cluster-Juwele" items={names(result.clusterRecommendationIds, clusterJewelDefinitions)}/><List title="Unique-Cluster-Juwele" items={names(result.uniqueClusterRecommendationIds, uniqueClusterJewelDefinitions)}/><List title="Unique-Empfehlung" items={result.uniqueRecommendations.map(item => item.title)}/><List title="Affix-Verbesserungen" items={result.affixRecommendations.map(item => item.title)}/>
  </div><div className="rotation-grid"><article><h3>Mapping-Rotation</h3>{result.mappingRotation.map(step => <p key={step.id}><b>{step.order}. {step.action}</b><br/><span>{step.reason}</span></p>)}</article><article><h3>Boss-Rotation</h3>{result.bossRotation.map(step => <p key={step.id}><b>{step.order}. {step.action}</b><br/><span>{step.reason}</span></p>)}</article></div><article><h3>Build-Erklärung</h3><p>{result.explanation}</p><p><b>Fertigkeitsreihenfolge:</b> {result.skillOrderExplanation}</p><p><b>Warum Set 2 vor Set 1:</b> {result.weaponSwapExplanation}</p></article></section>
}
