import { memo, useEffect, useMemo, useRef, useState } from 'react'
import { loadPoe2TreeViewModel, treeLoadMetrics } from '../tree-view/data'
import { calculateTreeBounds } from '../tree-view/geometry'
import { panTreeCamera, pointerDistance, pointerMidpoint, TREE_ZOOM, zoomTreeCameraAt, type ScreenPoint } from '../tree-view/gestures'
import { centeredTreeCamera, initialTreeCamera, nodeMatchesFilter, searchTreeNodes, TREE_NODE_RADIUS } from '../tree-view/view-logic'
import type { PassiveTreeViewModel, TreeDisplayFilter, TreeNodeViewModel } from '../tree-view/types'
import { resolveAscendancyDisplayTransform, transformAscendancyPoint } from '../tree-view/ascendancy'
import { officialClassRegistry, resolveBackgroundSprite, resolveNodeSpriteRenderData, Sprite } from '../tree-view/assets'
import { resolveTreeConnectionGeometry, resolveTreeConnectionRenderDecision, resolveTreeConnectionStyle } from '../tree-view/connections'
import type { CompactRealPassivePipelineResult } from '../engine/orchestration/real-passive-result-projection'
import { buildPassivePlanVisualization,cameraForPassivePlan,planNodeDescription,resolvePassivePlanNodeRole,type PassivePlanVisualization } from '../tree-view/plan-visualization'
import type { PassiveAnalysisUiStatus } from '../features/real-passive-analysis/controller'
import './passive-tree.css'

type Camera = ReturnType<typeof initialTreeCamera>
type DisplayContext = { characterClassId?: string; characterAscendancyId?: string }
type PlanKey='shared'|'set-1'|'set-2'|'ascendancy'
type PlanDisplayContext={planResult?:CompactRealPassivePipelineResult|null;planResults?:Partial<Record<PlanKey,CompactRealPassivePipelineResult|null>>;planStatus?:PassiveAnalysisUiStatus;activePlan?:PlanKey;planVisible?:boolean;focusPlanRequest?:number}
const FILTERS: Array<{ id: TreeDisplayFilter; label: string }> = [{ id: 'all', label: 'Alle Knoten' }, { id: 'class-start', label: 'Klassenstarts' }, { id: 'ascendancy', label: 'Aszendenzen' }, { id: 'jewel-socket', label: 'Juwelsockel' }, { id: 'keystone', label: 'Keystones' }, { id: 'notable', label: 'Notables' }]

const ConnectionLayer = memo(function ConnectionLayer({ tree, nodes, selected, activeNodeIds = new Set<string>(),plan,planDimmed=false }: { tree: PassiveTreeViewModel; nodes: TreeNodeViewModel[]; selected: TreeNodeViewModel | null; activeNodeIds?: ReadonlySet<string>;plan?:PassivePlanVisualization;planDimmed?:boolean }) {
  const positions = useMemo(() => new Map(nodes.map(node => [node.id, node])), [nodes]), selectedConnections = selected ? new Set(selected.neighbourIds.map(id => [selected.id, id].sort().join(':'))) : new Set<string>()
  return <g className="tree-connections" aria-hidden="true">{tree.connections.flatMap(connection => { const from=positions.get(connection.fromNodeId),to=positions.get(connection.toNodeId);if(!from||!to)return[];const decision=resolveTreeConnectionRenderDecision(connection,activeNodeIds);if(!decision.visible)return[];const geometry=resolveTreeConnectionGeometry(connection,from,to),style=resolveTreeConnectionStyle(decision,selectedConnections.has([connection.fromNodeId, connection.toNodeId].sort().join(':'))),planned=plan?.pathConnectionIds.has(connection.id);return <g key={connection.id}><path d={geometry.d} data-connection-id={connection.id} data-connection-status={decision.status} data-connection-geometry={geometry.kind} data-connection-layer={style.layer} className={style.className} strokeWidth={style.strokeWidth} opacity={style.opacity}/>{planned&&<path d={geometry.d} data-plan-connection={connection.id} data-connection-geometry={geometry.kind} className={`tree-plan-connection${planDimmed?' stale':''}`}/>}</g> })}</g>
})

const NodeLayer = memo(function NodeLayer({ nodes, selectedId, highlightedId, filter, detailLevel, onSelect,plan,planDimmed=false }: { nodes: TreeNodeViewModel[]; selectedId: string | null; highlightedId?: string; filter: TreeDisplayFilter; detailLevel:'far'|'medium'|'near'; onSelect: (node: TreeNodeViewModel) => void;plan?:PassivePlanVisualization;planDimmed?:boolean }) {
  return <g className="tree-nodes">{nodes.filter(node=>node.nodeType!=='mastery').map(node => {
    const dimmed=!nodeMatchesFilter(node,filter),radius=TREE_NODE_RADIUS[node.nodeType],state=selectedId===node.id?'selected':highlightedId===node.id?'highlighted':dimmed?'dimmed':'inactive',sprites=resolveNodeSpriteRenderData(node,state,detailLevel,radius)
    const extras=new Set<'inspected'|'dimmed'>([...(selectedId===node.id?['inspected' as const]:[]),...(dimmed?['dimmed' as const]:[])]),planRole=resolvePassivePlanNodeRole(plan?.nodeRoles.get(node.id),extras),planned=Boolean(plan&&planRole!=='normal'&&planRole!=='inspected'&&planRole!=='dimmed'),description=planNodeDescription(node,plan)
    const className=`tree-node tree-node-${node.nodeType}${selectedId===node.id?' selected':''}${highlightedId===node.id?' context-selected':''}${dimmed&&!planned?' dimmed':''}${planned?` ${planRole}${planDimmed?' plan-stale':''}`:''}`
    return <g key={node.id} className={className} data-plan-node-role={planned?planRole:''} data-icon-fallback={sprites.fallbackReason??''} role="button" aria-label={`${node.displayName}, ${node.nodeType}, ID ${node.id}${description?`, ${description}`:''}`} tabIndex={0} onPointerDown={event=>event.stopPropagation()} onClick={()=>onSelect(node)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(node)}}}>
      {planned&&<circle className="tree-plan-node-marker" cx={node.x} cy={node.y} r={radius+28}/>} {detailLevel==='far'?<circle className="tree-node-frame" cx={node.x} cy={node.y} r={radius}/>:<><Sprite data={sprites.icon}/><Sprite data={sprites.frame}/>{!sprites.icon&&!sprites.frame&&<circle className="tree-node-frame" cx={node.x} cy={node.y} r={radius}/>}</>}{plan?.targetOrder.has(node.id)&&<text className="tree-plan-order" x={node.x+radius} y={node.y-radius}>{plan.targetOrder.get(node.id)}</text>}
    </g>
  })}</g>
})

const PlanOverlay = memo(function PlanOverlay({tree,nodes,plan,kind,excludedNodeIds=new Set<string>(),excludedConnectionIds=new Set<string>(),dimmed=false}:{tree:PassiveTreeViewModel;nodes:TreeNodeViewModel[];plan:PassivePlanVisualization;kind:PlanKey;excludedNodeIds?:ReadonlySet<string>;excludedConnectionIds?:ReadonlySet<string>;dimmed?:boolean}){
 const positions=new Map(nodes.map(node=>[node.id,node]))
 return <g className={`tree-plan-${kind}${dimmed?' plan-stale':''}`} data-plan-layer={kind}>
  {tree.connections.flatMap(connection=>{if(!plan.pathConnectionIds.has(connection.id)||excludedConnectionIds.has(connection.id))return[];const from=positions.get(connection.fromNodeId),to=positions.get(connection.toNodeId);if(!from||!to)return[];return <path key={connection.id} d={resolveTreeConnectionGeometry(connection,from,to).d} data-plan-connection={connection.id} className={`tree-plan-connection${dimmed?' stale':''}`}/>})}
  {nodes.flatMap(node=>{if(!plan.allocatedNodeIds.has(node.id)||excludedNodeIds.has(node.id))return[];const radius=TREE_NODE_RADIUS[node.nodeType],role=resolvePassivePlanNodeRole(plan.nodeRoles.get(node.id));return <circle key={node.id} data-plan-node={node.id} data-plan-node-role={role} className="tree-plan-node-marker" cx={node.x} cy={node.y} r={radius+28}/>})}
 </g>
})

export function PassiveTree({ loader = loadPoe2TreeViewModel, ...context }: { loader?: () => Promise<PassiveTreeViewModel> } & DisplayContext & PlanDisplayContext) {
  const [tree, setTree] = useState<PassiveTreeViewModel | null>(null), [error, setError] = useState(''), [full, setFull] = useState(false), [firstRenderMs, setFirstRenderMs] = useState(0)
  const requestedAt = useRef(0)
  useEffect(() => { let active = true; requestedAt.current = performance.now(); loader().then(value => { if (active) setTree(value) }).catch(value => { if (active) setError(value instanceof Error ? value.message : 'Unbekannter Ladefehler') }); return () => { active = false } }, [loader])
  useEffect(() => { if (tree) requestAnimationFrame(() => setFirstRenderMs(performance.now() - requestedAt.current)) }, [tree])
  if (error) return <PassiveTreeLoadState error={error}/>
  if (!tree) return <PassiveTreeLoadState/>
  return <PassiveTreeContent tree={tree} {...context} full={full} onToggleFull={() => setFull(value => !value)} performanceMetrics={{ ...treeLoadMetrics, firstRenderMs }}/>
}

export function PassiveTreeLoadState({ error = '' }: { error?: string }) { return <section><h2>5. Offizieller PoE2-Passivbaum</h2>{error ? <div className="tree-error" role="alert"><h3>Baumdaten konnten nicht angezeigt werden</h3><p>{error}</p><small>Es wird kein synthetischer Ersatzbaum verwendet.</small></div> : <div className="tree-loading" role="status">Lokale Baumdaten werden geladen …</div>}</section> }

export function PassiveTreeContent({ tree, characterClassId, characterAscendancyId,planResult,planResults,planStatus,activePlan='shared',planVisible=true,focusPlanRequest=0, full = false, onToggleFull = () => undefined, performanceMetrics }: { tree: PassiveTreeViewModel; full?: boolean; onToggleFull?: () => void; performanceMetrics?: { dataLoadMs: number; adapterMs: number; totalMs: number; firstRenderMs: number } } & DisplayContext & PlanDisplayContext) {
  const [camera, setCamera] = useState<Camera>(() => initialTreeCamera(tree)), [selected, setSelected] = useState<TreeNodeViewModel | null>(null), [filter, setFilter] = useState<TreeDisplayFilter>('all'), [query, setQuery] = useState('')
  const viewportRef = useRef<HTMLDivElement>(null), pointers = useRef(new Map<number, ScreenPoint>()), gesture = useRef<{ midpoint: ScreenPoint; distance: number } | null>(null)
  const treeContext=officialClassRegistry.find(value=>value.classId===characterClassId),selectedAscendancyRecord=treeContext?.ascendancies.find(value=>value.ascendancyId===characterAscendancyId),selectedAscendancyId=selectedAscendancyRecord?.officialExportId
  const selectedClass=treeContext?tree.classes.find(value=>value.id===String(treeContext.officialClassIndex)):undefined,selectedAscendancy=selectedAscendancyId?tree.ascendancies.find(value=>value.id===selectedAscendancyId):undefined
  const mainNodes = useMemo(() => tree.nodes.filter(node => !node.isAscendancyNode), [tree.nodes]), ascendancyNodes = selectedAscendancyId ? tree.nodes.filter(node => node.ascendancyId === selectedAscendancyId) : []
  const ascendancyBounds=ascendancyNodes.length?calculateTreeBounds(ascendancyNodes,0):null,ascendancyTransform=ascendancyBounds?resolveAscendancyDisplayTransform(ascendancyBounds,tree.bounds):null,results=searchTreeNodes([...mainNodes,...ascendancyNodes],query)
  const plans=useMemo(()=>{const source=planResults??(planResult?{[activePlan]:planResult}:{});return Object.fromEntries(Object.entries(source).flatMap(([key,result])=>result?[[key,buildPassivePlanVisualization(result,tree)]]:[])) as Partial<Record<PlanKey,PassivePlanVisualization>>},[activePlan,planResult,planResults,tree])
  const plan=plans.shared??plans[activePlan]??plans.ascendancy,showPlan=Boolean(planVisible&&Object.values(plans).some(value=>value?.valid)&&['completed','stale'].includes(planStatus??'')),planDimmed=planStatus==='stale'
  const sharedNodeIds=plans.shared?.allocatedNodeIds??new Set<string>(),sharedConnectionIds=plans.shared?.pathConnectionIds??new Set<string>()
  useEffect(()=>{if(focusPlanRequest<=0||!showPlan)return;const ids=new Set(Object.entries(plans).filter(([key])=>key!=='ascendancy').flatMap(([,value])=>[...(value?.allocatedNodeIds??[])]));if(!ids.size)return;const timer=window.setTimeout(()=>setCamera(cameraForPassivePlan(tree,ids)),0);return()=>window.clearTimeout(timer)},[focusPlanRequest,plans,showPlan,tree])
  const viewWidth = tree.bounds.width / camera.zoom, viewHeight = tree.bounds.height / camera.zoom, viewBox = `${camera.centerX - viewWidth / 2} ${camera.centerY - viewHeight / 2} ${viewWidth} ${viewHeight}`
  const focusNode=(node:TreeNodeViewModel)=>{setSelected(node);const point=node.isAscendancyNode&&ascendancyTransform?transformAscendancyPoint(ascendancyTransform,node):node;setCamera(centeredTreeCamera(tree,{...node,...point}))},rect=()=>viewportRef.current!.getBoundingClientRect()
  const zoomAt = (factor: number, point?: ScreenPoint) => setCamera(value => zoomTreeCameraAt(value, factor, tree.bounds, rect(), point ?? { x: rect().left + rect().width / 2, y: rect().top + rect().height / 2 }))
  const availableAscendancies=treeContext?tree.ascendancies.filter(value=>value.classId===String(treeContext.officialClassIndex)):[]
  const endPointer = (id: number) => { pointers.current.delete(id); gesture.current = null; const remaining = [...pointers.current.values()]; if (remaining.length === 1) gesture.current = { midpoint: remaining[0], distance: 0 } }
  return <section className={`${full ? 'tree-section tree-full' : 'tree-section'} tree-plan-${activePlan}`} data-active-plan="all"><div className="row"><div><h2>5. Offizieller PoE2-Passivbaum</h2><p className="muted">GGG-Export · Release {tree.sourceVersion} · {tree.nodeCount.toLocaleString('de-DE')} Knoten · englische Originaltexte</p></div><button className="secondary" onClick={onToggleFull}>{full ? 'Verkleinern' : 'Vergrößern'}</button></div>
    <div className="tree-status"><b>Offizielle Baumansicht:</b> Lokale GGG-Atlanten aus dem gepinnten Export; Fernansicht vereinfacht, Mittel-/Nahansicht mit Originalmotiven und -rahmen. Keine Pfadsuche oder Buildoptimierung.</div>
    <div className="tree-tools"><label>Knotensuche<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Englischer Name, Stat oder ID"/></label><label>Darstellungsfilter<select value={filter} onChange={event => setFilter(event.target.value as TreeDisplayFilter)}>{FILTERS.map(value => <option key={value.id} value={value.id}>{value.label}</option>)}</select></label><label>Klassenstart<select value={selectedClass?.id ?? ''} onChange={event => { const option = tree.classes.find(value => value.id === event.target.value), node = tree.nodes.find(value => value.id === option?.nodeId); if (node) focusNode(node) }}><option value="">Klasse auswählen</option>{tree.classes.map(value => <option key={`${value.displayName}-${value.id}`} value={value.id}>{value.displayName}</option>)}</select></label><label>Aszendenzstart<select value={selectedAscendancy?.id ?? ''} onChange={event => { const option = tree.ascendancies.find(value => value.id === event.target.value), node = tree.nodes.find(value => value.id === option?.nodeId); if (node) focusNode(node) }}><option value="">Aszendenz auswählen</option>{availableAscendancies.map(value => <option key={`${value.displayName}-${value.id}`} value={value.id}>{value.displayName}</option>)}</select></label></div>
    {query.trim() && <div className="tree-search-results" aria-label="Suchergebnisse"><span>{results.length} Treffer angezeigt</span>{results.map(node => <button key={node.id} className="secondary" onClick={() => focusNode(node)}>{node.displayName} <small>#{node.id}</small></button>)}</div>}
    <div className="tree-controls"><button onClick={() => zoomAt(TREE_ZOOM.buttonFactor)}>Zoom +</button><button onClick={() => zoomAt(1 / TREE_ZOOM.buttonFactor)}>Zoom −</button><button className="secondary" onClick={() => { setCamera(initialTreeCamera(tree)); setSelected(null) }}>Gesamtansicht</button><output>{Math.round(camera.zoom * 100)} %</output></div>
    {performanceMetrics && <output className="tree-performance-data" hidden data-data-load-ms={performanceMetrics.dataLoadMs.toFixed(1)} data-adapter-ms={performanceMetrics.adapterMs.toFixed(1)} data-total-ms={performanceMetrics.totalMs.toFixed(1)} data-first-render-ms={performanceMetrics.firstRenderMs.toFixed(1)}/>} 
    <div ref={viewportRef} className="tree-viewport" data-node-count={tree.nodeCount} data-visible-ascendancy={selectedAscendancyId ?? ''} data-ascendancy-node-count={ascendancyNodes.length} onWheel={event => { event.preventDefault(); zoomAt(event.deltaY < 0 ? TREE_ZOOM.wheelFactor : 1 / TREE_ZOOM.wheelFactor, { x: event.clientX, y: event.clientY }) }} onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); pointers.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); const values = [...pointers.current.values()]; gesture.current = values.length >= 2 ? { midpoint: pointerMidpoint(values[0], values[1]), distance: pointerDistance(values[0], values[1]) } : { midpoint: values[0], distance: 0 } }} onPointerMove={event => { if (!pointers.current.has(event.pointerId)) return; pointers.current.set(event.pointerId, { x: event.clientX, y: event.clientY }); const values = [...pointers.current.values()].slice(0, 2), prior = gesture.current; if (!prior) return; if (values.length === 1) { const current = values[0]; setCamera(value => panTreeCamera(value, tree.bounds, rect(), { x: current.x - prior.midpoint.x, y: current.y - prior.midpoint.y })); gesture.current = { midpoint: current, distance: 0 } } else { const midpoint = pointerMidpoint(values[0], values[1]), distance = pointerDistance(values[0], values[1]); if (prior.distance > 0) setCamera(value => zoomTreeCameraAt(value, Math.pow(distance / prior.distance, TREE_ZOOM.pinchSensitivity), tree.bounds, rect(), midpoint)); gesture.current = { midpoint, distance } } }} onPointerUp={event => endPointer(event.pointerId)} onPointerCancel={event => endPointer(event.pointerId)}>
      {(()=>{const detailLevel=camera.zoom<2.5?'far':camera.zoom<6?'medium':'near',allPlanNodes=new Set(Object.values(plans).flatMap(value=>[...(value?.allocatedNodeIds??[])]));return <svg data-detail-level={detailLevel} data-plan-visible={String(showPlan)} data-plan-layer-count={showPlan?Object.keys(plans).length:0} viewBox={viewBox} preserveAspectRatio="xMidYMid meet" aria-label={`Offizieller PoE2-Passivbaum mit ${tree.nodeCount} Knoten`}><ConnectionLayer tree={tree} nodes={mainNodes} selected={selected} activeNodeIds={allPlanNodes}/><NodeLayer nodes={mainNodes} selectedId={selected?.id??null} highlightedId={selectedClass?.nodeId} filter={filter} detailLevel={detailLevel} onSelect={focusNode}/>{showPlan&&plans.shared&&<PlanOverlay tree={tree} nodes={mainNodes} plan={plans.shared} kind="shared" dimmed={planDimmed}/>} {showPlan&&plans['set-1']&&<PlanOverlay tree={tree} nodes={mainNodes} plan={plans['set-1']} kind="set-1" excludedNodeIds={sharedNodeIds} excludedConnectionIds={sharedConnectionIds} dimmed={planDimmed}/>} {showPlan&&plans['set-2']&&<PlanOverlay tree={tree} nodes={mainNodes} plan={plans['set-2']} kind="set-2" excludedNodeIds={sharedNodeIds} excludedConnectionIds={sharedConnectionIds} dimmed={planDimmed}/>} {ascendancyTransform&&<g className="tree-ascendancy-central" transform={`translate(${ascendancyTransform.translateX} ${ascendancyTransform.translateY}) scale(${ascendancyTransform.scale})`} aria-label={`Ausgewählte Aszendenz ${selectedAscendancy?.displayName??selectedAscendancyId}`}><Sprite data={resolveBackgroundSprite(selectedAscendancyRecord?.backgroundFrameKey,ascendancyTransform.image.x,ascendancyTransform.image.y,ascendancyTransform.image.width,ascendancyTransform.image.height)}/><ConnectionLayer tree={tree} nodes={ascendancyNodes} selected={selected} activeNodeIds={allPlanNodes}/><NodeLayer nodes={ascendancyNodes} selectedId={selected?.id??null} highlightedId={selectedAscendancy?.nodeId} filter="all" detailLevel={detailLevel==='far'?'medium':detailLevel} onSelect={focusNode}/>{showPlan&&plans.ascendancy&&<PlanOverlay tree={tree} nodes={ascendancyNodes} plan={plans.ascendancy} kind="ascendancy" dimmed={planDimmed}/>}</g>}</svg>})()}
    </div>
    <div className="legend"><span>● Normal</span><span>● Notable</span><span>● Keystone</span><span>● Klassenstart</span><span>● Aszendenz</span><span>● Juwelsockel</span></div>{showPlan&&<div className="tree-plan-color-legend" aria-label="Farben der gleichzeitig sichtbaren Pläne"><span className="shared">Gelb: gemeinsam</span><span className="set-1">Rot: nur Waffenset 1</span><span className="set-2">Grün: nur Waffenset 2</span><span className="ascendancy">Violett: Aszendenz</span></div>}
    <div className="tree-details" aria-live="polite">{selected ? <><h3>{selected.displayName}</h3><p><b>Technische ID:</b> {selected.id} · <b>Typ:</b> {selected.nodeType}</p>{showPlan&&planNodeDescription(selected,plan)&&<p><b>Planrolle:</b> {planNodeDescription(selected,plan)}</p>}{selected.ascendancyId && <p><b>Aszendenz:</b> {selected.ascendancyId}</p>}<h4>Offizielle Stats</h4>{selected.stats.length ? <ul>{selected.stats.map((stat, index) => <li key={`${selected.id}-${index}`}>{stat}</li>)}</ul> : <p className="muted">Keine Stats im offiziellen Export.</p>}</> : <p className="muted">Knoten anklicken oder antippen, um englische Originaldetails anzuzeigen.</p>}</div>
  </section>
}
