import { describe,expect,it } from 'vitest'
import approval from '../../data-sources/source-approval.json'
import manifest from '../../generated/poe2-items/additional-item-source-manifest.json'
import coverage from '../../generated/poe2-items/additional-item-coverage-report.json'
import index from '../../generated/poe2-items/additional-item-class-index.json'
import { additionalTechnicalAffixes,affixesFor,baseItemsFor,technicalAffixById } from '../affixes/registry'
import { buildRealPassiveWorkerRequest } from '../features/real-passive-analysis/adapter'
import { initialEquipment,skillSetups,ascendancyDefinitions } from '../data'

const category=(id:string)=>approval.categoryAssignments.find(value=>value.categoryId===id)
describe('5M.1B additional item import',()=>{
 it('pins the exact approved export and parser',()=>expect(manifest).toMatchObject({exportVersion:'4.5.4.4.4',exportCommit:'b3f38149a9e5ffbba1eae3a9f2ddcdd66481884c',parserCommit:'14e3edc89ed705bd4e4eda5c8135756431c76e81',approvalStatus:'conditionally-approved'}))
 it('accepts only the three narrow scopes',()=>{expect(category('poe2-technical-jewel-mod-data-for-build-planner')?.status).toBe('conditionally-approved');expect(category('poe2-technical-charm-mod-data-for-build-planner')?.status).toBe('conditionally-approved');expect(category('poe2-technical-flask-mod-data-for-build-planner')?.status).toBe('conditionally-approved');expect(category('poe2-technical-relic-mod-data-for-build-planner')?.status).toBe('pending')})
 it('keeps unique items, socketables and German texts excluded',()=>{expect(manifest.excludedCategories).toEqual(expect.arrayContaining(['uniques','relics','socketables','german-texts','raw-export-mirror']));expect(additionalTechnicalAffixes.filter(value=>value.generationType==='unique').every(value=>value.affixSide==='implicit'&&value.itemClassIds.length===1&&value.itemClassIds[0]==='Charms')).toBe(true);expect(additionalTechnicalAffixes.map(value=>value.affixSide)).not.toContain('special')})
 it('contains the audited category counts without duplicate runtime IDs',()=>{expect(coverage.categories).toMatchObject({Jewels:{references:320,baseItems:8,prefixes:142,suffixes:178},Charms:{references:51,baseItems:13,implicits:13},'Life Flasks':{references:57,baseItems:9},'Mana Flasks':{references:52,baseItems:9}});expect(new Set(additionalTechnicalAffixes.map(value=>value.affixId)).size).toBe(additionalTechnicalAffixes.length);expect(additionalTechnicalAffixes).toHaveLength(427)})
 it('resolves every index and base implicit reference',()=>{for(const value of Object.values(index))for(const id of [...value.prefix,...value.suffix,...value.implicit])expect(technicalAffixById.has(id)).toBe(true);for(const base of baseItemsFor('Charms'))for(const id of base.implicitModIds)expect(valueIds(index.Charms.implicit)).toContain(id)})
 it('keeps Life and Mana Flask registries separate',()=>{expect(baseItemsFor('Life Flasks').every(value=>value.itemKind==='life-flask')).toBe(true);expect(baseItemsFor('Mana Flasks').every(value=>value.itemKind==='mana-flask')).toBe(true);expect(new Set(baseItemsFor('Life Flasks').map(value=>value.baseItemId))).not.toEqual(new Set(baseItemsFor('Mana Flasks').map(value=>value.baseItemId)))})
 it('filters tiers by item level and exposes real ranges',()=>{const all=affixesFor('Jewels','prefix');expect(all.length).toBe(142);expect(all.every(value=>value.tierId&&value.statLines.every(line=>line.minimum<=line.maximum))).toBe(true);expect(affixesFor('Jewels','prefix',1).every(value=>(value.requiredItemLevel??0)<=1)).toBe(true)})
 it('transports technical jewel identity, tier, stat and value through the worker payload',()=>{const equipment=structuredClone(initialEquipment),entry=equipment.find(value=>value.slotId==='slot-jewel-1')!,affix=affixesFor('Jewels','prefix')[0];Object.assign(entry,{itemClassId:'Jewels',itemDefinitionId:baseItemsFor('Jewels')[0].baseItemId,itemLevel:80,modifierValues:[{id:'real-jewel-mod',modifierId:affix.affixId,value:affix.statLines[0].minimum,tierId:affix.tierId,sourceVersion:affix.sourceVersion,dataStatus:affix.dataStatus,statValues:affix.statLines.map(line=>({statId:line.statId,value:line.minimum}))}]});const character={classId:'class-official-6',ascendancyId:ascendancyDefinitions.find(value=>value.classId==='class-official-6')?.id??'',level:70,goalProfile:'balanced' as const};const result=buildRealPassiveWorkerRequest({character,equipment,setups:skillSetups,pointBudget:20,planningMode:'balanced'},'test');expect(result.payload?.request.input.selectedJewels[0]).toMatchObject({baseItemId:entry.itemDefinitionId,itemClassId:'Jewels',itemLevel:80,sourceVersion:'4.5.4.4.4',modifiers:[{modifierId:affix.affixId,tierId:affix.tierId,statValues:[{statId:affix.statLines[0].statId,value:affix.statLines[0].minimum}]}]})})
})
const valueIds=(values:string[])=>values
