import { describe, expect, it } from 'vitest'
import { analyzeBuild } from '../orchestration/analyze-build'
import { engineModifierFixtures, fixtureA, fixtureB, syntheticJewelFixtures } from '../fixtures'
import { jewelAnalyzer } from './analyzer'
import type { AnalyzerContext, PassiveAnalysis } from '../common/types'
const context=():AnalyzerContext=>({engineVersion:'test',fixtureMode:true}); const build=(cold=false)=>analyzeBuild(cold?fixtureB:fixtureA,context(),engineModifierFixtures)
const run=(cold=false, jewels=syntheticJewelFixtures, passive?:PassiveAnalysis)=>{const b=build(cold);return jewelAnalyzer.analyzeRanked(b.buildProfile,jewels,context(),{equipmentAnalysis:b.equipmentAnalysis,skillRecommendation:b.skillAnalysis.eligibleCandidates[0],supportRecommendations:b.supportAnalysis.topCandidates,passiveAnalysis:passive??b.passiveAnalysis,character:(cold?fixtureB:fixtureA).input.character})}; const get=(id:string,cold=false)=>run(cold).allCandidates.find(x=>x.jewelId===id)!
describe('regelbasierter synthetischer Jewel Analyzer',()=>{
it('erkennt normale Juwele',()=>expect(get('fixture-jewel-normal').jewelType).toBe('normal'))
it('erkennt Cluster-Juwele',()=>expect(get('fixture-jewel-cluster').jewelType).toBe('cluster'))
it('erkennt Unique-Cluster',()=>expect(get('fixture-jewel-enabler').jewelType).toBe('unique-cluster'))
it('passende Schadensart erhöht Score',()=>expect(get('fixture-jewel-normal').damageScore).toBeGreaterThan(0))
it('passende Mechanik erhöht Score',()=>expect(get('fixture-jewel-normal').equipmentSynergyScore).toBeGreaterThan(0))
it('unpassende Mechanik gibt keinen Bonus',()=>expect(get('fixture-jewel-cold-spell').damageScore).toBe(0))
it('Cold Spell passt zum Cold-Build',()=>expect(get('fixture-jewel-cold-spell',true).damageScore).toBeGreaterThan(0))
it('defensive Juwele profitieren',()=>expect(get('fixture-jewel-defence').defenceScore).toBeGreaterThan(0))
it('Widerstandsjuwele profitieren',()=>expect(get('fixture-jewel-resistance').defenceScore).toBeGreaterThan(0))
it('Attributjuwele werden bewertet',()=>expect(get('fixture-jewel-attribute').resourceScore).toBeGreaterThanOrEqual(0))
it('falscher Sockeltyp blockiert',()=>expect(get('fixture-jewel-wrong-socket').valid).toBe(false))
it('fehlender Sockel blockiert',()=>{const b=build();const empty={...b.passiveAnalysis,eligibleCandidates:[]} as PassiveAnalysis;expect(run(false,[syntheticJewelFixtures.find(x=>x.id==='fixture-jewel-missing-socket')!],empty).blockedCandidates).toHaveLength(1)})
it('deaktiviertes Juwel blockiert',()=>{const j={...syntheticJewelFixtures[0],enabled:false};expect(run(false,[j]).blockedCandidates).toHaveLength(1)})
it('falsche Klasse blockiert',()=>{const j={...syntheticJewelFixtures[0],requiredClassId:'other'};expect(run(false,[j]).blockedCandidates).toHaveLength(1)})
it('ausgeschlossene Aszendenz blockiert',()=>{const j={...syntheticJewelFixtures[0],excludedAscendancyIds:['fixture-ascendancy-storm']};expect(run(false,[j]).blockedCandidates).toHaveLength(1)})
it('Levelanforderung blockiert',()=>{const j={...syntheticJewelFixtures[0],levelRequirement:99};expect(run(false,[j]).blockedCandidates).toHaveLength(1)})
it('Cluster-entryPointCost zählt',()=>expect(get('fixture-jewel-expensive').entryPointCost).toBe(3))
it('internalPathCost zählt',()=>expect(get('fixture-jewel-expensive').internalPathCost).toBe(8))
it('totalPointCost ist korrekt',()=>expect(get('fixture-jewel-expensive').totalPointCost).toBe(11))
it('scorePerPoint sinkt bei Kosten',()=>expect(get('fixture-jewel-expensive').scorePerPoint).toBeLessThan(get('fixture-jewel-cluster').scorePerPoint))
it('effizientes Cluster hat höhere Effizienz',()=>expect(get('fixture-jewel-cluster').pathEfficiencyScore).toBeGreaterThan(get('fixture-jewel-expensive').pathEfficiencyScore))
it('zusätzliche Sockel sind begrenzt',()=>expect(get('fixture-jewel-socket-cluster').addedSocketValue).toBeLessThanOrEqual(16))
it('Unique-Trade-off ist negativ',()=>expect(get('fixture-jewel-enabler').reasons.some(x=>x.impact<0)).toBe(true))
it('Build-Enabler erzeugt Warnung',()=>expect(get('fixture-jewel-enabler').warnings.some(x=>x.code==='build-enabler')).toBe(true))
it('Build-Enabler senkt Confidence',()=>expect(get('fixture-jewel-enabler').confidence).not.toBe('high'))
it('harter Unique-Konflikt blockiert',()=>expect(get('fixture-jewel-hard-conflict').valid).toBe(false))
it('Redundanz wird erkannt',()=>expect(get('fixture-jewel-redundant').warnings.some(x=>x.code==='redundant')).toBe(true))
it('Konflikte werden erkannt',()=>expect(get('fixture-jewel-cold-spell').conflictingMechanics).toContain('spell'))
it('Waffen-Sets werden getrennt bewertet',()=>expect(get('fixture-jewel-set-1').scoreSet1).not.toBe(get('fixture-jewel-set-1').scoreSet2))
it('Set 1 wird bevorzugt',()=>expect(get('fixture-jewel-set-1').preferredWeaponSet).toBe('set-1'))
it('gleiche Scores ergeben both',()=>expect(get('fixture-jewel-normal').preferredWeaponSet).toBe('both'))
it('geringe Klarheit senkt Confidence',()=>{const b=build();const e={...b.equipmentAnalysis,profileClarity:1};expect(jewelAnalyzer.analyzeRanked(b.buildProfile,[syntheticJewelFixtures[0]],context(),{equipmentAnalysis:e}).allCandidates[0].confidence).toBe('low')})
it('experimentell senkt Confidence',()=>{const j={...syntheticJewelFixtures[0],experimental:true};expect(run(false,[j]).allCandidates[0].confidence).not.toBe('high')})
it('Tie-Breaker verwendet ID',()=>{const j=syntheticJewelFixtures[0];expect(run(false,[{...j,id:'z'},{...j,id:'a'}]).allCandidates.map(x=>x.jewelId)).toEqual(['a','z'])})
it('blockierte stehen hinten',()=>{const r=run();expect(r.allCandidates.findIndex(x=>!x.valid)).toBeGreaterThan(r.allCandidates.findIndex(x=>x.valid))})
it('gleiche Eingabe ist deterministisch',()=>expect(run()).toEqual(run()))
it('liefert Normal-Rangliste',()=>expect(run().topNormalJewels.every(x=>x.jewelType==='normal')).toBe(true))
it('liefert Cluster-Rangliste',()=>expect(run().topClusterJewels.every(x=>x.jewelType==='cluster')).toBe(true))
it('liefert Unique-Rangliste',()=>expect(run().topUniqueClusterJewels.every(x=>x.jewelType==='unique-cluster')).toBe(true))
it('liefert Damage-Rangliste',()=>expect(run().topDamageJewels).toBeInstanceOf(Array))
it('liefert Defensive-Rangliste',()=>expect(run().topDefensiveJewels).toBeInstanceOf(Array))
it('liefert Mapping-Rangliste',()=>expect(run().topMappingJewels).toBeInstanceOf(Array))
it('liefert Boss-Rangliste',()=>expect(run().topBossJewels).toBeInstanceOf(Array))
it('liefert Effizienz-Rangliste',()=>expect(run().topPathEfficiencyJewels).toBeInstanceOf(Array))
it('liefert Ascendancy-Rangliste',()=>expect(run().topAscendancySynergyJewels).toBeInstanceOf(Array))
it('liefert Enabler-Rangliste',()=>expect(run().topBuildEnablerJewels).toBeInstanceOf(Array))
it('Orchestrator liefert JewelAnalysis',()=>expect(build().jewelAnalysis.allCandidates.length).toBe(14))
})
