import { describe,expect,it } from 'vitest'
import manifest from '../../generated/poe2-tree/asset-manifest.json'
import report from '../../generated/poe2-tree/asset-import-report.json'
import registry from '../../generated/poe2-tree/class-registry.json'
import renderData from '../../generated/poe2-tree/tree-render-data.json'
import referenceAudit from '../../generated/poe2-tree/node-sprite-reference-audit.json'
import { resolveAscendancyDisplayTransform,transformAscendancyPoint } from './ascendancy'
import { renderToStaticMarkup } from 'react-dom/server'
import { resolveNodeSpriteRenderData,Sprite } from './assets'
import type { TreeNodeViewModel } from './types'

const node=(input:Partial<TreeNodeViewModel>&Pick<TreeNodeViewModel,'id'|'nodeType'>)=>({x:100,y:200,displayName:input.id,sourceText:null,sourceLocale:'en',localizationStatus:'pending',stats:[],neighbourIds:[],isClassStart:false,isAscendancyStart:false,isAscendancyNode:false,isJewelSocket:false,selectable:true,visible:true,warningCodes:[],sourceReference:`nodes.${input.id}`,...input}) as TreeNodeViewModel

describe('offizielle PoE2-Baumassets',()=>{
  it('bindet Release und Commit fest',()=>{expect(manifest.release).toBe('0.5.2');expect(manifest.commit).toBe('1e9eb2d8c1946398c3aaaacfbaead5c75c0d1fa6')})
  it('inventarisiert ausschließlich lokale Exportdateien mit SHA-256',()=>{expect(manifest.files).toHaveLength(36);for(const file of manifest.files){expect(file.relativePath).toMatch(/^assets\/[a-z-]+\.(json|webp)$/);expect(file.sha256).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(file)).not.toMatch(/(?:https?:\/\/|[A-Z]:\\)/)}})
  it('hält alle Spritekoordinaten innerhalb der Atlanten',()=>{for(const frame of Object.values(renderData.atlases)){expect(frame.x+frame.w).toBeLessThanOrEqual(frame.atlasWidth);expect(frame.y+frame.h).toBeLessThanOrEqual(frame.atlasHeight)}})
  it('meldet fehlende Mastery-Icons mit konkreten Node-IDs kontrolliert',()=>{expect(report.status).toBe('validated-with-warnings');expect(report.unresolvedNodeIconReferences).toHaveLength(51);expect(report.unresolvedNodeIcons).toHaveLength(365);expect(report.unresolvedNodeIcons.every(value=>value.isMastery&&value.nodeId&&value.fallbackReason==='official-icon-sprite-unresolved')).toBe(true)})
  it('erkennt zwölf Klassen ohne Sechsergrenze und aktiviert neue Klassen nicht ohne Assets',()=>{expect(registry.classes).toHaveLength(12);expect(registry.classes.filter(value=>value.selectableInCurrentUi)).toHaveLength(8);expect(registry.classes.find(value=>value.displayName==='Marauder')?.selectableInCurrentUi).toBe(false)})
  it('ordnet jede Aszendenz nur ihrer Klasse zu',()=>{const ids=new Set<string>();for(const item of registry.classes)for(const ascendancy of item.ascendancies){expect(ascendancy.classId).toBe(item.classId);expect(ids.has(ascendancy.ascendancyId)).toBe(false);ids.add(ascendancy.ascendancyId)}})
  it('dokumentiert 20 Referenzknoten in der geforderten Typverteilung',()=>{expect(referenceAudit.nodeCount).toBe(20);expect(referenceAudit.nodes.filter(value=>value.nodeType==='normal')).toHaveLength(8);expect(referenceAudit.nodes.filter(value=>value.nodeType==='notable')).toHaveLength(4);expect(referenceAudit.nodes.filter(value=>value.nodeType==='keystone')).toHaveLength(3);expect(referenceAudit.nodes.filter(value=>value.nodeType==='jewel-socket')).toHaveLength(2);expect(referenceAudit.nodes.filter(value=>value.nodeType==='class-start')).toHaveLength(1);expect(referenceAudit.nodes.filter(value=>value.nodeType.startsWith('ascendancy-'))).toHaveLength(2)})
  it('löst Skill Speed 26798 über die technische Node-ID auf',()=>{const inactive=resolveNodeSpriteRenderData(node({id:'26798',nodeType:'normal'}),'inactive','near',34),active=resolveNodeSpriteRenderData(node({id:'26798',nodeType:'normal'}),'active','near',34);expect(inactive.officialIconReference).toBe('Art/2DArt/SkillIcons/passives/attackspeed.png');expect(inactive.icon).toMatchObject({atlasName:'skills-disabled.webp',sourceX:884,sourceY:136,sourceWidth:34,sourceHeight:34,layer:'icon'});expect(active.icon).toMatchObject({atlasName:'skills.webp',sourceX:884,sourceY:136,sourceWidth:34,sourceHeight:34,layer:'icon'});expect(inactive.fallbackReason).toBeUndefined()})
  it('behält die Motivreferenz über Mittel- und Nahstufe bei',()=>{const value=node({id:'26798',nodeType:'normal'});expect(resolveNodeSpriteRenderData(value,'inactive','medium',34).icon?.spriteKey).toBe(resolveNodeSpriteRenderData(value,'inactive','near',34).icon?.spriteKey)})
  it('trennt Notable- und Keystone-Motiv vom offiziellen Rahmenatlas',()=>{for(const value of [node({id:'55',nodeType:'notable'}),node({id:'52',nodeType:'keystone'})]){const result=resolveNodeSpriteRenderData(value,'inactive','near',50);expect(result.icon?.atlasName).toBe('skills-disabled.webp');expect(result.frame?.atlasName).toBe('frame.webp');expect(result.icon?.layer).toBe('icon');expect(result.frame?.layer).toBe('frame')}})
  it('liefert für gültige normale Referenzen keinen Fallback und nur lokale URLs',()=>{for(const id of ['26798','4','60','65','71','95','144','151']){const result=resolveNodeSpriteRenderData(node({id,nodeType:'normal'}),'inactive','near',34);expect(result.icon).not.toBeNull();expect(result.fallbackReason).toBeUndefined();expect(result.icon!.assetUrl).not.toMatch(/^(?:https?:|file:|[A-Z]:\\)/)}})
  it('legt den offiziellen PSSkillFrame über normale Motive',()=>{const result=resolveNodeSpriteRenderData(node({id:'26798',nodeType:'normal'}),'inactive','near',34);expect(result.frame?.spriteKey).toBe('frame:PSSkillFrame');expect(result.frame?.atlasName).toBe('frame.webp')})
  it('clippt den Atlas auf einen lokalen Sprite-viewBox mit negativem Atlasoffset',()=>{const data=resolveNodeSpriteRenderData(node({id:'26798',nodeType:'normal'}),'inactive','near',34).icon,markup=renderToStaticMarkup(<Sprite data={data}/>);expect(markup).toContain('viewBox="0 0 34 34"');expect(markup).toContain('data-source-rect="884 136 34 34"');expect(markup).toContain('x="-884"');expect(markup).toContain('y="-136"');expect(markup).toContain('<clipPath');expect(markup).toContain('clip-path="url(#');expect(markup).toContain('overflow="hidden"');expect(markup).toContain('preserveAspectRatio="none"')})
})

describe('zentrale Aszendenztransformation',()=>{it('erhält Geometrie und zentriert deterministisch',()=>{const source={minX:100,minY:200,maxX:1100,maxY:1200,width:1000,height:1000,padding:0},tree={minX:-10000,minY:-9000,maxX:10000,maxY:11000,width:20000,height:20000,padding:420},transform=resolveAscendancyDisplayTransform(source,tree),a=transformAscendancyPoint(transform,{x:100,y:200}),b=transformAscendancyPoint(transform,{x:1100,y:1200});expect(transform.navigationCenter).toEqual({x:0,y:1000});expect((b.x-a.x)/(b.y-a.y)).toBeCloseTo(1);expect(transform).toEqual(resolveAscendancyDisplayTransform(source,tree))})})
