import type { CompactRealPassivePipelineResult } from '../engine/orchestration/real-passive-result-projection'
import { clampTreeZoom,type TreeCamera } from './gestures'
import type { PassiveTreeViewModel,TreeConnectionViewModel,TreeNodeViewModel } from './types'

export type PassivePlanNodeRole='normal'|'plan-start'|'plan-path'|'plan-target'|'plan-required-target'|'plan-selected-target'|'plan-blocked-target'|'plan-unreachable-target'|'plan-overlap'|'inspected'|'searched'|'dimmed'
export type PassivePlanConnectionRole='normal'|'plan-path'|'plan-required-path'|'plan-overlap'|'hidden-effect'|'layout-transition'|'unknown'
export interface PassivePlanVisualizationIssue {code:string;nodeId?:string;connectionId?:string;blocking:boolean}
export interface PassivePlanPathSegment {targetNodeId:string;order:number;nodeIds:readonly string[]}
export interface PassivePlanVisualization {startNodeId:string;targetNodeIds:ReadonlySet<string>;requiredTargetNodeIds:ReadonlySet<string>;allocatedNodeIds:ReadonlySet<string>;pathConnectionIds:ReadonlySet<string>;pathSegments:readonly PassivePlanPathSegment[];blockedNodeIds:ReadonlySet<string>;unreachableNodeIds:ReadonlySet<string>;targetOrder:ReadonlyMap<string,number>;nodeRoles:ReadonlyMap<string,ReadonlySet<PassivePlanNodeRole>>;connectionRoles:ReadonlyMap<string,PassivePlanConnectionRole>;visualizationIssues:readonly PassivePlanVisualizationIssue[];resultHash:string;sourceVersion:string;valid:boolean}

const addRole=(roles:Map<string,Set<PassivePlanNodeRole>>,id:string,role:PassivePlanNodeRole)=>{const current=roles.get(id)??new Set<PassivePlanNodeRole>();current.add(role);roles.set(id,current)}
const pair=(a:string,b:string)=>[a,b].sort().join(':')
export function resolvePassivePlanNodeRole(roles:ReadonlySet<PassivePlanNodeRole>|undefined,extras:ReadonlySet<PassivePlanNodeRole>=new Set()):PassivePlanNodeRole{
 const all=new Set([...(roles??[]),...extras]);for(const role of ['plan-unreachable-target','plan-blocked-target','plan-required-target','plan-selected-target','plan-target','plan-overlap','plan-start','plan-path','inspected','searched','dimmed','normal'] as const)if(all.has(role))return role;return'normal'
}

export function buildPassivePlanVisualization(result:CompactRealPassivePipelineResult,tree:PassiveTreeViewModel):PassivePlanVisualization{
 const issues:PassivePlanVisualizationIssue[]=[],nodes=new Map(tree.nodes.map(node=>[node.id,node])),connections=new Map(tree.connections.map(connection=>[connection.id,connection])),roles=new Map<string,Set<PassivePlanNodeRole>>(),connectionRoles=new Map<string,PassivePlanConnectionRole>(),targetOrder=new Map<string,number>()
 const startNodeId=result.plan.startNodeId??'',targetNodeIds=new Set(result.plan.selectedTargetIds),requiredTargetNodeIds=new Set(result.plan.requiredTargetDiagnostics.map(value=>value.nodeId)),allocatedNodeIds=new Set(result.plan.allocatedNodeIds),pathConnectionIds=new Set<string>(),blockedNodeIds=new Set<string>(),unreachableNodeIds=new Set<string>()
 if(result.sourceVersion!==tree.sourceVersion)issues.push({code:'source-version-mismatch',blocking:true})
 if(!result.pipelineDiagnostics.deterministicResultHash)issues.push({code:'missing-result-hash',blocking:true})
 if(!startNodeId||!nodes.has(startNodeId))issues.push({code:'missing-start-node',nodeId:startNodeId||undefined,blocking:true});else addRole(roles,startNodeId,'plan-start')
 for(const id of allocatedNodeIds){const node=nodes.get(id);if(!node){issues.push({code:'allocated-node-not-in-tree',nodeId:id,blocking:false});continue}if(node.isAscendancyNode){issues.push({code:'ascendancy-node-in-normal-plan',nodeId:id,blocking:false});continue}addRole(roles,id,'plan-path')}
 result.plan.selectedTargetIds.forEach((id,index)=>{targetOrder.set(id,index+1);const node=nodes.get(id);if(!node)issues.push({code:'target-node-not-in-tree',nodeId:id,blocking:false});else if(!node.isAscendancyNode)addRole(roles,id,'plan-selected-target')})
 for(const diagnostic of result.plan.requiredTargetDiagnostics){if(diagnostic.targetingStatus==='blocked'){blockedNodeIds.add(diagnostic.nodeId);addRole(roles,diagnostic.nodeId,'plan-blocked-target')}if(diagnostic.pathStatus==='unreachable'){unreachableNodeIds.add(diagnostic.nodeId);addRole(roles,diagnostic.nodeId,'plan-unreachable-target')}if(diagnostic.treeStatus==='missing')issues.push({code:'required-node-not-in-tree',nodeId:diagnostic.nodeId,blocking:false});else addRole(roles,diagnostic.nodeId,'plan-required-target')}
 const connectionByPair=new Map(tree.connections.map(connection=>[pair(connection.fromNodeId,connection.toNodeId),connection]))
 const selectedById=new Map(result.plan.selectedTargets.map(target=>[target.nodeId,target])),pathSegments=result.plan.selectedTargetIds.flatMap((targetNodeId,index)=>{const target=selectedById.get(targetNodeId);if(!target){issues.push({code:'selected-target-path-missing',nodeId:targetNodeId,blocking:false});return[]}for(let offset=1;offset<target.pathNodeIds.length;offset++){const connection=connectionByPair.get(pair(target.pathNodeIds[offset-1],target.pathNodeIds[offset]));if(!connection||!result.plan.allocatedConnectionIds.includes(connection.id))issues.push({code:'disconnected-path-segment',nodeId:target.nodeId,connectionId:connection?.id,blocking:false})}return[{targetNodeId:target.nodeId,order:index+1,nodeIds:[...target.pathNodeIds]}]})
 for(const id of result.plan.allocatedConnectionIds){const connection=connections.get(id);if(!connection){issues.push({code:'allocated-connection-not-in-tree',connectionId:id,blocking:false});continue}if(!allocatedNodeIds.has(connection.fromNodeId)||!allocatedNodeIds.has(connection.toNodeId))issues.push({code:'connection-endpoint-not-allocated',connectionId:id,blocking:false});const role=resolveConnectionRole(connection);connectionRoles.set(id,role);if(role==='layout-transition'||role==='hidden-effect'||role==='unknown'){issues.push({code:`plan-connection-${role}`,connectionId:id,blocking:false});continue}pathConnectionIds.add(id)}
 if(startNodeId&&nodes.has(startNodeId)){const seen=new Set([startNodeId]);let changed=true;while(changed){changed=false;for(const id of pathConnectionIds){const connection=connections.get(id)!;if(seen.has(connection.fromNodeId)&&allocatedNodeIds.has(connection.toNodeId)&&!seen.has(connection.toNodeId)){seen.add(connection.toNodeId);changed=true}if(seen.has(connection.toNodeId)&&allocatedNodeIds.has(connection.fromNodeId)&&!seen.has(connection.fromNodeId)){seen.add(connection.fromNodeId);changed=true}}}for(const id of allocatedNodeIds)if(nodes.has(id)&&!nodes.get(id)!.isAscendancyNode&&!seen.has(id))issues.push({code:'allocated-node-disconnected',nodeId:id,blocking:false})}
 for(const nodeRoles of roles.values())if(nodeRoles.has('plan-path')&&nodeRoles.size>1)nodeRoles.add('plan-overlap')
 const valid=!issues.some(issue=>issue.blocking)
 return{startNodeId,targetNodeIds,requiredTargetNodeIds,allocatedNodeIds,pathConnectionIds,pathSegments,blockedNodeIds,unreachableNodeIds,targetOrder,nodeRoles:roles,connectionRoles,visualizationIssues:issues,resultHash:result.pipelineDiagnostics.deterministicResultHash,sourceVersion:result.sourceVersion,valid}
}

export function resolveConnectionRole(connection:TreeConnectionViewModel):PassivePlanConnectionRole{if(connection.connectionType==='layout-transition')return'layout-transition';if(connection.touchesMastery||connection.hideInDefaultState||connection.connectionType==='glow-only')return'hidden-effect';if(connection.connectionType!=='passive-tree')return'unknown';return'plan-path'}
export function cameraForPassivePlan(tree:PassiveTreeViewModel,nodeIds:ReadonlySet<string>):TreeCamera{const nodes=tree.nodes.filter(node=>nodeIds.has(node.id)&&!node.isAscendancyNode);if(!nodes.length)return{centerX:(tree.bounds.minX+tree.bounds.maxX)/2,centerY:(tree.bounds.minY+tree.bounds.maxY)/2,zoom:1};const minX=Math.min(...nodes.map(node=>node.x)),maxX=Math.max(...nodes.map(node=>node.x)),minY=Math.min(...nodes.map(node=>node.y)),maxY=Math.max(...nodes.map(node=>node.y)),width=Math.max(400,maxX-minX+800),height=Math.max(400,maxY-minY+800);return{centerX:(minX+maxX)/2,centerY:(minY+maxY)/2,zoom:clampTreeZoom(Math.min(tree.bounds.width/width,tree.bounds.height/height))}}
export const planNodeDescription=(node:TreeNodeViewModel,visualization:PassivePlanVisualization|undefined)=>{if(!visualization)return'';const role=resolvePassivePlanNodeRole(visualization.nodeRoles.get(node.id));const labels:Record<PassivePlanNodeRole,string>={'normal':'','plan-start':'Startpunkt','plan-path':'Geplanter Weg','plan-target':'Empfohlenes Ziel','plan-required-target':'Pflichtziel','plan-selected-target':'Empfohlenes Ziel','plan-blocked-target':'Blockiertes Ziel','plan-unreachable-target':'Nicht erreichbares Ziel','plan-overlap':'Mehrfach genutzter Planknoten',inspected:'Inspiziert',searched:'Suchtreffer',dimmed:'Gedimmt'};const order=visualization.targetOrder.get(node.id);return`${labels[role]}${order?`, Zielreihenfolge ${order}`:''}`}
