import {describe,expect,it} from 'vitest'
import type {CompactRealPassivePipelineResult} from '../engine/orchestration/real-passive-result-projection'
import type {PassiveTreeViewModel,TreeNodeViewModel} from './types'
import {buildPassivePlanVisualization,cameraForPassivePlan,resolvePassivePlanNodeRole} from './plan-visualization'

const node=(id:string,extra:Partial<TreeNodeViewModel>={}):TreeNodeViewModel=>({id,x:Number(id)*10,y:Number(id)*5,nodeType:'normal',displayName:id,sourceText:id,sourceLocale:'en',localizationStatus:'pending',stats:[],neighbourIds:[],isClassStart:false,isAscendancyStart:false,isAscendancyNode:false,isJewelSocket:false,selectable:true,visible:true,warningCodes:[],sourceReference:`nodes.${id}`,...extra})
const tree=():PassiveTreeViewModel=>{const nodes=[node('1',{nodeType:'class-start',isClassStart:true}),node('2'),node('3'),node('4',{isAscendancyNode:true,nodeType:'ascendancy'})];return{sourceVersion:'0.5.2',sourceCommit:'x',sourceLocale:'en',bounds:{minX:0,minY:0,maxX:1000,maxY:1000,width:1000,height:1000,padding:0},worldBounds:{minX:0,minY:0,maxX:1000,maxY:1000,width:1000,height:1000,padding:0},nodeCount:4,connectionCount:4,drawableConnectionCount:2,groupCount:0,nodes,connections:[{id:'1:2',fromNodeId:'1',toNodeId:'2',connectionType:'passive-tree',hideInDefaultState:false,sourceReference:'a'},{id:'2:3',fromNodeId:'2',toNodeId:'3',connectionType:'passive-tree',hideInDefaultState:false,orbitCenter:{x:20,y:30},sourceReference:'b'},{id:'3:4',fromNodeId:'3',toNodeId:'4',connectionType:'layout-transition',hideInDefaultState:false,sourceReference:'c'},{id:'effect',fromNodeId:'2',toNodeId:'3',connectionType:'passive-tree',hideInDefaultState:true,sourceReference:'d'}],groups:[],classStartNodes:[nodes[0]],ascendancyStartNodes:[],jewelSockets:[],classes:[],ascendancies:[],warnings:[],status:'validated'}}
const compact=(extra:Partial<CompactRealPassivePipelineResult>={}):CompactRealPassivePipelineResult=>({sourceVersion:'0.5.2',pipelineDiagnostics:{deterministicResultHash:'fnv1a32-test'} as never,plan:{startNodeId:'1',selectedTargetIds:['3'],selectedTargets:[{nodeId:'3',pathNodeIds:['1','2','3']}],allocatedNodeIds:['1','2','3'],allocatedConnectionIds:['1:2','2:3'],requiredTargetDiagnostics:[],status:'partial'} as never,...extra} as CompactRealPassivePipelineResult)

describe('zentraler Passive-Plan-Darstellungsadapter',()=>{
 it('übernimmt Start, belegte IDs, Verbindungen und Zielreihenfolge ohne Neuberechnung',()=>{const view=buildPassivePlanVisualization(compact(),tree());expect(view.startNodeId).toBe('1');expect([...view.allocatedNodeIds]).toEqual(['1','2','3']);expect([...view.pathConnectionIds]).toEqual(['1:2','2:3']);expect(view.targetOrder.get('3')).toBe(1);expect(view.valid).toBe(true)})
 it('erhält Required-Ziele und unterscheidet blockiert sowie nicht erreichbar',()=>{const result=compact();result.plan.requiredTargetDiagnostics=[{nodeId:'3',treeStatus:'present',targetingStatus:'blocked',planningStatus:'failed',selected:false,pathStatus:'unreachable',violationCodes:['blocked'],warningCodes:[]}];const view=buildPassivePlanVisualization(result,tree());expect(view.requiredTargetNodeIds.has('3')).toBe(true);expect(view.blockedNodeIds.has('3')).toBe(true);expect(view.unreachableNodeIds.has('3')).toBe(true);expect(resolvePassivePlanNodeRole(view.nodeRoles.get('3'))).toBe('plan-unreachable-target')})
 it('meldet fehlende Knoten und Verbindungen statt sie still zu ignorieren',()=>{const result=compact();result.plan.allocatedNodeIds.push('999');result.plan.allocatedConnectionIds.push('missing');const codes=buildPassivePlanVisualization(result,tree()).visualizationIssues.map(value=>value.code);expect(codes).toContain('allocated-node-not-in-tree');expect(codes).toContain('allocated-connection-not-in-tree')})
 it('blockiert abweichende Source-Version und fehlenden Hash',()=>{const view=buildPassivePlanVisualization(compact({sourceVersion:'other',pipelineDiagnostics:{deterministicResultHash:''} as never}),tree());expect(view.valid).toBe(false);expect(view.visualizationIssues.filter(value=>value.blocking)).toHaveLength(2)})
 it('zeichnet weder Layoutübergang noch verborgene Effektkante als Plan',()=>{const result=compact();result.plan.allocatedConnectionIds=['3:4','effect'];const view=buildPassivePlanVisualization(result,tree());expect(view.pathConnectionIds.size).toBe(0);expect(view.connectionRoles.get('3:4')).toBe('layout-transition');expect(view.connectionRoles.get('effect')).toBe('hidden-effect')})
 it('übernimmt keinen Aszendenzknoten als normale Belegung',()=>{const result=compact();result.plan.allocatedNodeIds.push('4');const view=buildPassivePlanVisualization(result,tree());expect(view.nodeRoles.has('4')).toBe(false);expect(view.visualizationIssues.map(value=>value.code)).toContain('ascendancy-node-in-normal-plan')})
 it('meldet getrennte Pfadfolgen und normalisiert gemeinsame IDs über Sets',()=>{const result=compact();result.plan.allocatedNodeIds.push('2');result.plan.allocatedConnectionIds.push('2:3');const view=buildPassivePlanVisualization(result,tree());expect(view.allocatedNodeIds.size).toBe(3);expect(view.pathConnectionIds.size).toBe(2);expect(view.pathSegments[0].nodeIds).toEqual(['1','2','3'])})
 it('mutiert das Quellresultat nicht und ist deterministisch',()=>{const result=compact(),before=JSON.stringify(result),one=buildPassivePlanVisualization(result,tree()),two=buildPassivePlanVisualization(result,tree());expect(JSON.stringify(result)).toBe(before);expect([...one.pathConnectionIds]).toEqual([...two.pathConnectionIds]);expect([...one.nodeRoles]).toEqual([...two.nodeRoles])})
 it('wendet die zentrale Rollenpriorität stabil an',()=>{expect(resolvePassivePlanNodeRole(new Set(['plan-start','plan-selected-target']))).toBe('plan-selected-target');expect(resolvePassivePlanNodeRole(new Set(['plan-required-target','plan-selected-target']))).toBe('plan-required-target');expect(resolvePassivePlanNodeRole(new Set(['plan-blocked-target','plan-required-target']))).toBe('plan-blocked-target');expect(resolvePassivePlanNodeRole(new Set(['plan-path','dimmed']))).toBe('plan-path');expect(resolvePassivePlanNodeRole(new Set(['plan-selected-target','inspected']))).toBe('plan-selected-target')})
 it('berechnet Plan-Bounds kontrolliert innerhalb der Zoomgrenzen',()=>{const camera=cameraForPassivePlan(tree(),new Set(['1','2','3']));expect(camera.centerX).toBe(20);expect(camera.centerY).toBe(10);expect(camera.zoom).toBeGreaterThanOrEqual(1);expect(camera.zoom).toBeLessThanOrEqual(12)})
})
