import type { LocalizationStatus } from '../import/poe2-tree/types'

export type TreeNodeViewType = 'normal' | 'notable' | 'keystone' | 'mastery' | 'class-start' | 'ascendancy-start' | 'ascendancy' | 'jewel-socket' | 'unknown'
export type TreeDisplayFilter = 'all' | 'class-start' | 'ascendancy' | 'jewel-socket' | 'keystone' | 'notable'

export interface TreeBoundsViewModel { minX: number; minY: number; maxX: number; maxY: number; width: number; height: number; padding: number }
export interface TreeNodeViewModel { id: string; x: number; y: number; nodeType: TreeNodeViewType; groupId?: string; orbit?: number; orbitIndex?: number; displayName: string; sourceText: string | null; sourceLocale: string; localizationStatus: LocalizationStatus; stats: string[]; neighbourIds: string[]; isClassStart: boolean; classId?: string; isAscendancyStart: boolean; ascendancyId?: string; isAscendancyNode: boolean; isJewelSocket: boolean; selectable: true; visible: true; warningCodes: string[]; sourceReference: string }
export interface TreeConnectionViewModel { id: string; fromNodeId: string; toNodeId: string; connectionType: string; hideInDefaultState: boolean; touchesMastery?: boolean; orbit?: number; orbitCenter?: { x:number; y:number }; sourceReference: string }
export interface TreeGroupViewModel { id: string; x: number; y: number; nodeIds: string[]; bounds?: TreeBoundsViewModel }
export interface TreeOrientationOption { id: string; displayName: string; nodeId: string; classId?: string }
export interface PassiveTreeViewModel { sourceVersion: string; sourceCommit: string; sourceLocale: string; bounds: TreeBoundsViewModel; worldBounds: TreeBoundsViewModel; nodeCount: number; connectionCount: number; drawableConnectionCount: number; groupCount: number; nodes: TreeNodeViewModel[]; connections: TreeConnectionViewModel[]; groups: TreeGroupViewModel[]; classStartNodes: TreeNodeViewModel[]; ascendancyStartNodes: TreeNodeViewModel[]; jewelSockets: TreeNodeViewModel[]; classes: TreeOrientationOption[]; ascendancies: TreeOrientationOption[]; warnings: string[]; status: 'validated' | 'rejected' }

export interface ImportedPoe2Tree { metadata: { releaseTag: string; commitHash: string; sourceLocale: string }; bounds: { minX: number; minY: number; maxX: number; maxY: number }; classes: Array<{ classStartIndex: number; name: { sourceText: string | null }; ascendancies: Array<{ id: string; name: { sourceText: string | null } }> }>; nodes: Array<{ id: string; name: { sourceText: string | null; sourceLocale: string; localizedText: string | null; localizationStatus: LocalizationStatus }; stats: Array<{ sourceText: string | null }>; nodeType: string; position: { x: number; y: number }; groupId: string; orbit?: number; orbitIndex?: number; neighbourNodeIds: string[]; isClassStart: boolean; classStartIndex: number | number[] | null; isAscendancyStart: boolean; ascendancyId: string | null; isJewelSocket: boolean; sourceReference: string }>; connections: Array<{ id: string; fromNodeId: string; toNodeId: string; connectionType: string; hideInDefaultState?: boolean; touchesMastery?: boolean; orbit?:number; orbitCenter?:{x:number;y:number}; sourceReference: string }>; groups: Array<{ groupId: string; position: { x: number; y: number }; nodeIds: string[];orbits?:number[] }> }

export interface TreeImportReport { status: string; warnings: Array<{ code: string; message: string }> }
