import type { Affix, Ascendancy, BuildResult, ClusterJewel, Jewel, PassiveNode, Skill, UniqueClusterJewel } from './models'
export const classes=['Krieger','Waldläuferin','Zauberin','Mönch','Söldner','Hexe']
export const ascendancies:Ascendancy[]=classes.flatMap((c,i)=>[{id:`a${i}1`,name:['Titan','Pfadfinderin','Sturmweberin','Beschwörer','Hexenjäger','Infernalistin'][i],classId:c},{id:`a${i}2`,name:`${c}-Testaszendenz`,classId:c}])
export const affixes:Affix[]=['Erhöhter physischer Schaden','Zusätzlicher Feuerschaden','Zusätzlicher Kälteschaden','Zusätzlicher Blitzschaden','Angriffsgeschwindigkeit','Zaubergeschwindigkeit','Kritische Trefferchance','Kritischer Treffermultiplikator','Maximales Leben','Energieschild','Rüstung','Ausweichwert','Feuerwiderstand','Kältewiderstand','Blitzwiderstand','Stärke','Geschick','Intelligenz'].map((name,i)=>({id:`affix-${i}`,name,value:0}))
export const equipmentNames=['Helm','Brust','Handschuhe','Schuhe','Amulett','Ring 1','Ring 2','Gürtel','Waffe Set 1 links','Waffe Set 1 rechts','Waffe Set 2 links','Waffe Set 2 rechts']
const supportNames=['Mehrfachprojektil','Elementarfokus','Schnellere Angriffe','Kritischer Schaden','Durchdringung']
export const skills:Skill[]=['Blitzpfeil','Kugelblitz','Sturmrufer','Flammenwand','Zeitverzerrung','Sprungschlag'].map((name,i)=>({id:`skill-${i}`,name,role:i===0?'Hauptfertigkeit':'Zusatzfertigkeit',weaponSet:i<2?'Waffen-Set 1':i<4?'Waffen-Set 2':'Beide',supports:supportNames.map((n,j)=>({id:`s${i}-${j}`,name:n}))}))
export const jewels:Jewel[]=[['Rubinjuwel','Mehr Feuerschaden'],['Saphirjuwel','Mehr Kälteschaden'],['Smaragdjuwel','Mehr Geschick']].map(([name,description],i)=>({id:`j${i}`,name,description}))
export const clusters:ClusterJewel[]=[{id:'c1',name:'Sturm-Cluster',description:'Blitz-Knoten',size:'groß'},{id:'c2',name:'Lebens-Cluster',description:'Defensive Knoten',size:'mittel'}]
export const uniqueClusters:UniqueClusterJewel[]=[{id:'u1',name:'Auge des Sturms',description:'Einzigartige Blitz-Synergie',unique:true},{id:'u2',name:'Unbeugsamer Kern',description:'Einzigartige Defensive',unique:true}]
export const passiveNodes:PassiveNode[]=[{id:'n1',name:'Start',type:'normal',x:70,y:150,selected:true},{id:'n2',name:'Geschick',type:'normal',x:150,y:110,selected:true},{id:'n3',name:'Sturmgriff',type:'notable',x:240,y:90,selected:true},{id:'n4',name:'Überladung',type:'keystone',x:335,y:130,selected:true},{id:'n5',name:'Leben',type:'normal',x:155,y:205,selected:false},{id:'n6',name:'Juwel',type:'jewel',x:250,y:220,selected:false},{id:'n7',name:'Cluster',type:'cluster',x:350,y:230,selected:false}]
export const buildResult:BuildResult={mainSkill:'Blitzpfeil',additionalSkills:['Sturmrufer','Flammenwand','Zeitverzerrung'],supports:['Mehrfachprojektil','Elementarfokus','Schnellere Angriffe','Kritischer Schaden','Durchdringung'],weaponSet1:['Blitzpfeil','Sprungschlag'],weaponSet2:['Flammenwand','Sturmrufer'],passivePath:'Start → Geschick → Sturmgriff → Überladung',jewels:['Smaragdjuwel'],clusters:['Sturm-Cluster'],uniqueClusters:['Auge des Sturms'],uniqueItem:'Gewitterkrone (Test-Unique)',affixImprovements:['Mehr Blitzschaden auf Waffe','Mehr maximales Leben auf Brust','Feuerwiderstand auf Ring ergänzen'],mappingRotation:[{order:1,action:'Flammenwand (Set 2)',reason:'Bereitet Bonusprojektilschaden vor'},{order:2,action:'Waffenwechsel zu Set 1',reason:'Wechselt zur Hauptwaffe'},{order:3,action:'Blitzpfeil',reason:'Räumt Gegnergruppen'}],bossRotation:[{order:1,action:'Sturmrufer (Set 2)',reason:'Markiert das Ziel'},{order:2,action:'Flammenwand',reason:'Bereitet den Angriff vor'},{order:3,action:'Waffenwechsel + Blitzpfeil',reason:'Hauptschadensfenster'}],explanation:'Der Test-Build kombiniert schnelle Blitzangriffe mit vorbereitenden Effekten und einer soliden Lebensbasis.',skillOrderExplanation:'Vorbereitungseffekte werden zuerst gesetzt, damit der anschließende Hauptangriff von ihnen profitiert.',weaponSwapExplanation:'Set 2 legt anhaltende Effekte. Diese bleiben in dieser Platzhalterlogik nach dem Wechsel bestehen; Set 1 liefert danach den Hauptschaden.',recommendations:[]}
