import { blankProfile } from '../common/scoring'
import { buildPassiveGraph } from '../passive-pathfinding/graph'
import type { PassivePathSource, PassivePathSourceNode } from '../passive-pathfinding/types'
import type { PassiveTargetAnalysis, PassiveTargetRecommendation } from '../passive-targeting/types'
import type { PassivePlanningInput } from './types'

const node=(id:string,neighbours:string[],values:Partial<PassivePathSourceNode>={}):PassivePathSourceNode=>({id,nodeType:'normal',neighbourNodeIds:neighbours,isClassStart:false,classStartIndex:null,isAscendancyStart:false,ascendancyId:null,isJewelSocket:false,...values})
const edge=(a:string,b:string)=>({id:`${a}-${b}`,fromNodeId:a,toNodeId:b})
export const PASSIVE_PLANNING_SOURCE:PassivePathSource={nodes:[
 node('S',['p1','q1','R','K','AS'],{nodeType:'class-start',isClassStart:true,classStartIndex:1}),node('p1',['S','A']),node('A',['p1','C'],{nodeType:'notable'}),node('C',['A'],{nodeType:'notable'}),
 node('q1',['S','q2']),node('q2',['q1','q3']),node('q3',['q2','B']),node('B',['q3'],{nodeType:'notable'}),node('R',['S'],{nodeType:'notable'}),node('K',['S'],{nodeType:'keystone'}),node('X',[]),
 node('AS',['S','ASC'],{nodeType:'ascendancy-start',isAscendancyStart:true,ascendancyId:'other'}),node('ASC',['AS'],{ascendancyId:'other'}),node('J',['S'],{nodeType:'jewel-socket',isJewelSocket:true}),
],connections:[edge('S','p1'),edge('p1','A'),edge('A','C'),edge('S','q1'),edge('q1','q2'),edge('q2','q3'),edge('q3','B'),edge('S','R'),edge('S','K'),edge('S','AS'),edge('AS','ASC'),edge('S','J')]}
export const PASSIVE_PLANNING_GRAPH=buildPassiveGraph(PASSIVE_PLANNING_SOURCE)

export function planningRecommendation(id:string,score:number,values:Partial<PassiveTargetRecommendation>={}):PassiveTargetRecommendation{return{recommendationId:`rec-${id}`,nodeId:id,nodeType:(PASSIVE_PLANNING_GRAPH.nodes.get(id)?.nodeType??'normal'),displayName:id,sourceStats:['fixture'],sourceLocale:'en',totalScore:score,eligibility:'eligible',damageScore:score,defenceScore:0,mappingScore:score,bossScore:score,speedScore:0,utilityScore:0,resourceScore:0,attributeScore:0,classSynergyScore:0,ascendancySynergyScore:0,profileSynergyScore:score,dataQualityScore:100,matchedTags:['attack'],weaklyMatchedTags:[],conflictingTags:[],matchedProfileFields:['mechanics.attack'],conflictingProfileFields:[],gainedMechanics:[],lostMechanics:[],restrictions:[],tradeOffs:[],requiresReoptimization:false,unresolvedStatCount:0,redundantWithNodeIds:[],conflictingNodeIds:[],weaklyUsefulReasonCodes:[],reasons:[{code:`target-${id}`,category:'damage',messageKey:'fixture',impact:score,polarity:'positive',sourceType:'passive',affectedTags:[]}],violations:[],warnings:[],confidence:'high',status:'experimental',analyzerVersion:'fixture',sourceVersion:'fixture',...values}}

export function planningTargetAnalysis(recommendations:PassiveTargetRecommendation[]):PassiveTargetAnalysis {const eligible=recommendations.filter(value=>value.eligibility==='eligible');const rank=[...eligible].sort((a,b)=>b.totalScore-a.totalScore||a.nodeId.localeCompare(b.nodeId));return{allCandidates:recommendations,eligibleCandidates:eligible,blockedCandidates:recommendations.filter(value=>value.eligibility==='blocked'),topDamageTargets:rank,topDefensiveTargets:rank,topMappingTargets:rank,topBossTargets:rank,topSpeedTargets:rank,topResourceTargets:rank,topAttributeTargets:rank,topClassSynergyTargets:rank,topAscendancyTargets:rank,topNotables:rank.filter(value=>value.nodeType==='notable'),topKeystones:rank.filter(value=>value.nodeType==='keystone'),jewelSocketTargets:recommendations.filter(value=>value.nodeType==='jewel-socket'),lowDataQualityCandidates:[],unresolvedStatCandidates:[],coverage:{totalNodeCount:recommendations.length,evaluatedNodeCount:recommendations.length,blockedNodeCount:recommendations.length-eligible.length,classifiedNodeCount:recommendations.length,unclassifiedNodeCount:0,totalStatLineCount:recommendations.length,classifiedStatLineCount:recommendations.length,unresolvedStatLineCount:0,classificationCoveragePercent:100,nodeTypeCounts:{},categoryCounts:{},unresolvedPatterns:[],mostFrequentUnresolvedTexts:[],sourceVersion:'fixture',classifierVersion:'fixture',status:'measured'},status:'experimental',analyzerVersion:'fixture',sourceVersion:'fixture'}}

export const PASSIVE_PLANNING_RECOMMENDATIONS=[
 planningRecommendation('A',90),planningRecommendation('B',120),planningRecommendation('C',62),planningRecommendation('R',58),planningRecommendation('K',95,{nodeType:'keystone',requiresReoptimization:true,confidence:'medium',tradeOffs:['fixture-keystone-trade-off']}),planningRecommendation('X',80),planningRecommendation('ASC',100,{nodeType:'ascendancy'}),planningRecommendation('J',40,{nodeType:'jewel-socket',eligibility:'socket-target'}),
]
export const passivePlanningInput=(values:Partial<PassivePlanningInput>={}):PassivePlanningInput=>({requestId:'fixture-plan',buildProfile:blankProfile(),characterClassId:'1',startNodeId:'S',pointBudget:6,targetProfile:'balanced',targetingResult:planningTargetAnalysis(PASSIVE_PLANNING_RECOMMENDATIONS),passiveGraph:PASSIVE_PLANNING_GRAPH,maximumSelectedTargets:3,candidatePoolLimit:10,minimumTargetScore:0,minimumConfidence:'low',planningMode:'balanced',analyzerContext:{engineVersion:'fixture',fixtureMode:true},sourceVersion:'fixture',...values})
