/* global performance,process,console */
import{describe,expect,it}from'vitest';import officialTree from '../../../generated/poe2-tree/tree.json';import{buildPassiveGraph}from'../passive-pathfinding/graph';import{evaluatePassiveTargets}from'../passive-targeting/evaluator';import{PASSIVE_TARGET_TEST_PROFILES}from'../passive-targeting/fixtures';import{createPassivePlanningPathCache,planPassiveTargets}from'./planner';
const elapsed=start=>Math.round((performance.now()-start)*100)/100;
describe('Passive-Planning Performance auf dem offiziellen Baum',()=>{it('misst begrenzte Pools, Budgets und Cache ohne Produktgrenzwert',()=>{
 const heapStart=process.memoryUsage().heapUsed;const graph=buildPassiveGraph(officialTree);const targeting=evaluatePassiveTargets({buildProfile:PASSIVE_TARGET_TEST_PROFILES.lightningProjectileAttack,characterClassId:'0',characterLevel:90,targetProfile:'balanced',passiveNodes:officialTree.nodes,analyzerContext:{engineVersion:'planning-performance',fixtureMode:true},sourceVersion:'0.5.2',profileClarity:100,maximumResults:50});
 const run=(pool,budget,pathCache)=>{const started=performance.now();const result=planPassiveTargets({requestId:`perf-${pool}-${budget}`,buildProfile:PASSIVE_TARGET_TEST_PROFILES.lightningProjectileAttack,characterClassId:'0',startNodeId:'47175',pointBudget:budget,targetProfile:'balanced',targetingResult:targeting,passiveGraph:graph,maximumSelectedTargets:1,candidatePoolLimit:pool,minimumTargetScore:0,minimumConfidence:'low',planningMode:'balanced',analyzerContext:{engineVersion:'planning-performance',fixtureMode:true},sourceVersion:'0.5.2',pathCache});return{result,ms:elapsed(started)}};
 const ten=run(10,20),twentyFive=run(25,20),fifty=run(50,20),small=run(25,5),large=run(25,50),shared=createPassivePlanningPathCache(),uncached=run(25,20),cacheWarm=run(25,20,shared),cacheHit=run(25,20,shared);const heapEnd=process.memoryUsage().heapUsed;
 const report={runtime:process.version,platform:`${process.platform}-${process.arch}`,pool10Ms:ten.ms,pool25Ms:twentyFive.ms,pool50Ms:fifty.ms,smallBudgetMs:small.ms,largeBudgetMs:large.ms,uncachedMs:uncached.ms,cacheWarmMs:cacheWarm.ms,cacheHitMs:cacheHit.ms,pathSearches:{pool10:ten.result.pathSearchCount,pool25:twentyFive.result.pathSearchCount,pool50:fifty.result.pathSearchCount,small:small.result.pathSearchCount,large:large.result.pathSearchCount,uncached:uncached.result.pathSearchCount,cacheWarm:cacheWarm.result.pathSearchCount,cacheHit:cacheHit.result.pathSearchCount},cacheHits:cacheHit.result.pathCacheHitCount,heapDeltaMiB:Math.round((heapEnd-heapStart)/10485.76)/100};console.info('PASSIVE_PLANNING_PERFORMANCE',JSON.stringify(report));
 expect(graph.nodeCount).toBe(5150);expect([ten.result.candidateCount,twentyFive.result.candidateCount,fifty.result.candidateCount]).toEqual([10,25,50]);expect(cacheHit.result.pathSearchCount).toBe(0);expect(cacheHit.result.pathCacheHitCount).toBeGreaterThan(0)
 },120000)})
